"use strict";

const DEFAULT_TOOL_MAX_STEPS = 4;
const DEFAULT_VISION_MAX_IMAGES = 3;
const MODEL_MESSAGE_TEXT_MAX = 220;
const MODEL_MESSAGE_QUOTE_MAX = 120;
const MODEL_KNOWLEDGE_SNIPPET_MAX = 220;
const DEFAULT_LLM_TIMEOUT_MS = 90000;
const DEFAULT_LLM_TIMEOUT_RETRY_ATTEMPTS = 5;
const DEFAULT_LLM_TIMEOUT_RETRY_BASE_DELAY_MS = 1000;
const DEFAULT_LLM_TIMEOUT_RETRY_MAX_DELAY_MS = 16000;

module.exports = {
  DEFAULT_LLM_TIMEOUT_MS,
  DEFAULT_LLM_TIMEOUT_RETRY_ATTEMPTS,
  DEFAULT_LLM_TIMEOUT_RETRY_BASE_DELAY_MS,
  DEFAULT_LLM_TIMEOUT_RETRY_MAX_DELAY_MS,
  DEFAULT_TOOL_MAX_STEPS,
  DEFAULT_VISION_MAX_IMAGES,
  MODEL_KNOWLEDGE_SNIPPET_MAX,
  MODEL_MESSAGE_QUOTE_MAX,
  MODEL_MESSAGE_TEXT_MAX,
};
