const fs = require("fs");
const os = require("os");
const path = require("path");
const crypto = require("crypto");
const { spawnSync } = require("child_process");
const { buildAgentSessionBinding } = require("./lib/agent_session_key");
const { createAgentRouteService } = require("./lib/agent_route_service");
const { createAgentTaskContextService } = require("./lib/agent_task_context_service");
const { buildAckTaskPatch, requeueStaleClaimedTasks } = require("./lib/agent_task_state");
const { createAgentVisionUtils } = require("./lib/agent_vision_utils");
const { createArchiveNotificationService } = require("./lib/archive_notification_service");
const { createBatchProcessorService } = require("./lib/batch_processor_service");
const { createCaseQueryService } = require("./lib/case_query_service");
const { createConfigConnectivityService } = require("./lib/config_connectivity_service");
const { createDashboardDataService } = require("./lib/dashboard_data_service");
const { createDashboardRoomActionsService } = require("./lib/dashboard_room_actions_service");
const { createDashboardSummaryUtils } = require("./lib/dashboard_summary_utils");
const { evaluateCallbackLanes } = require("./lib/knowledge_harvest");
const mysqlRuntimeStore = require("./lib/mysql_runtime_store");
const {
  createFlowbotConfigManager,
  maskSecret,
  normalizeBooleanInput,
} = require("./lib/config_manager");
const { createFeishuMessageNormalizer } = require("./lib/feishu_message_normalizer");
const { createFeishuOauthService } = require("./lib/feishu_oauth_service");
const { createFlowbotHttpServer } = require("./lib/flowbot_http_server");
const { createFlowbotNetworkClients } = require("./lib/flowbot_network_clients");
const { startFlowbotServer } = require("./lib/flowbot_server_startup");
const { createFlowbotRuntimeBootstrap } = require("./lib/flowbot_runtime_bootstrap");
const { createFlowbotStorageBootstrap } = require("./lib/flowbot_storage_bootstrap");
const { createHashText, createServerLocalHelpers } = require("./lib/server_local_helpers");
const {
  collectBody,
  escapeHtml,
  pruneEmpty,
  safeParseJson,
  sendFile,
  sendHtml,
  sendJson,
  sendRedirect,
} = require("./lib/http_utils");
const { createFlowbotLogWriters } = require("./lib/log_writers");
const { createKnowledgeAnswerService } = require("./lib/knowledge_answer_service");
const { createKnowledgeBotService } = require("./lib/knowledge_bot_service");
const { createKnowledgeHarvestService } = require("./lib/knowledge_harvest_service");
const { createMediaEnrichmentService } = require("./lib/media_enrichment_service");
const { createFlowbotServerHelpers } = require("./lib/flowbot_server_helpers");
const { createLocalKnowledgeService } = require("./lib/local_knowledge_service");
const {
  invokeWithLlmTimeoutRetry,
} = require("./lib/llm_retry");
const { createKnowledgeSearchClients } = require("./lib/knowledge_search_clients");
const { createMediaMessageUtils } = require("./lib/media_message_utils");
const { createMessageSearchService } = require("./lib/message_search_service");
const { createMessageSummaryService } = require("./lib/message_summary_service");
const { createMessageTextUtils } = require("./lib/message_text_utils");
const { createRuntimeStateService } = require("./lib/runtime_state_service");
const { createUpstreamLoginClient } = require("./lib/upstream_login_client");
const { createWecomMessageNormalizer } = require("./lib/wecom_message_normalizer");

const runtimeConfig = createFlowbotRuntimeBootstrap({ baseDir: __dirname });

const {
  ACCEPT_NOTIFY_TYPES, ACTIVE_CASE_STATUSES, CASE_ARCHIVE_NOTIFY_ENABLED, CASE_KEYWORDS, CASE_STATUS_LABELS,
  CATEGORY_LABELS, FEATURE_KEYWORDS, INCIDENT_KEYWORDS, MEMORY_SOURCE_VALUES, PRIORITY_ALIASES,
  PRIORITY_KEYWORDS, SUMMARY_STOPWORDS, SUPPORTED_MSG_TYPES, THREAD_TYPE_LABELS,
  AGENT_LANE_ENABLED, AGENT_PRIMARY_WAKE_NAME, AGENT_RUNTIME_ID, AGENT_SESSION_KEY_STRATEGY,
  AGENT_TASK_CLAIM_TIMEOUT_MS, AGENT_TASK_FETCH_LIMIT, AGENT_TASK_STATE_PATH, AGENT_WAKE_NAMES,
  ARCHIVE_ENABLED, ARCHIVE_LOG_PATH, ARCHIVE_MODE, ARCHIVE_PYTHON, ARCHIVE_SCRIPT_PATH,
  BATCH_ACTION_LABELS, BATCH_LOG_PATH, BATCH_MAX_OPEN_CASES, BATCH_MAX_PENDING_PER_ROOM,
  BATCH_MEDIA_ONLY_HOLD_MS, BATCH_MODE_ENABLED, BATCH_OPEN_CASE_LOOKBACK_MS,
  BATCH_PROCESSING_STALE_MS, BATCH_READY_AGE_MS, BATCH_SCAN_INTERVAL_MS,
  CDN_DOWNLOAD_ENDPOINT, CONFIG_TEST_PATH, DASHBOARD_DEFAULT_LIMIT, DASHBOARD_MAX_LIMIT,
  DASHBOARD_PUBLIC_URL, DASHBOARD_UI_VERSION, DATA_DIR, DEFAULT_LOGIN_REGION, DEFAULT_NOTIFY_URL,
  FEISHU_APP_ACCESS_TOKEN_URL, FEISHU_APP_ID, FEISHU_APP_SECRET, FEISHU_AUTHORIZE_URL,
  FEISHU_MESSAGE_TYPE_TO_FLOWBOT, FEISHU_OAUTH_REDIRECT_URI, FEISHU_OAUTH_RESULT_PATH,
  FEISHU_OAUTH_SCOPE, FEISHU_OAUTH_STATE_PATH, FEISHU_SEND_MESSAGE_URL, FEISHU_TARGET_CHAT_IDS,
  FEISHU_USER_ACCESS_TOKEN_URL, FEISHU_USER_INFO_URL, FEISHU_VERIFICATION_TOKEN,
  FILTER_LOG_PATH, FLOWBOT_STORAGE_BACKEND, HISTORY_SUMMARY_MAX_BUCKETS, KNOWLEDGE_CANDIDATES_PATH, KNOWLEDGE_DIR,
  IMAGE_SUMMARY_ENABLED, IMAGE_SUMMARY_MAX_BYTES, IMAGE_SUMMARY_MODEL, IMAGE_SUMMARY_TIMEOUT_MS,
  KNOWLEDGE_HARVEST_ENABLED, KNOWLEDGE_HARVEST_MAX_PER_SCAN, KNOWLEDGE_HARVEST_READY_AGE_MS,
  KNOWLEDGE_HARVEST_ROOM_IDS, KNOWLEDGE_HARVEST_SCAN_INTERVAL_MS, KNOWLEDGE_HARVEST_STATE_PATH,
  KNOWLEDGE_PUBLISH_LOG_PATH, KNOWLEDGE_SOURCE_VALUES, LLM_API_KEY, LLM_API_URL,
  LLM_CLASSIFY_ENABLED, LLM_MAX_REPAIR_ATTEMPTS, LLM_MODEL, LLM_TIMEOUT_MS,
  LLM_TIMEOUT_RETRY_ATTEMPTS, LLM_TIMEOUT_RETRY_BASE_DELAY_MS, LLM_TIMEOUT_RETRY_MAX_DELAY_MS,
  LOCAL_LAUNCH_AGENT_LABEL, LOCAL_LAUNCH_AGENT_PLIST_PATH, LOCAL_MANAGED_CONFIG_PATH, LOG_PATH,
  LOGIN_REGION_OPTIONS, MAXKB_BASE_URL, MAXKB_CACHE_TTL_MS, MAXKB_ENABLED, MAXKB_KNOWLEDGE_FILTER,
  MAXKB_KNOWLEDGE_PREFIX_FILTER, MAXKB_PASSWORD, MAXKB_SEARCH_MODE, MAXKB_SEARCH_SIMILARITY,
  MAXKB_TIMEOUT_MS, MAXKB_USERNAME, MAXKB_WORKSPACE_ID, MEDIA_DIR, MEDIA_DOWNLOAD_TIMEOUT_MS,
  MEDIA_DOWNLOAD_TYPES, MEDIA_INDEX_PATH, MESSAGE_CONTEXT_MAX_NEIGHBORS, MESSAGE_POOL_STATE_PATH,
  MESSAGE_ROLE_LABELS, MESSAGE_SEARCH_DEFAULT_LIMIT, MESSAGE_SEARCH_INDEX_PATH, MESSAGE_SEARCH_MAX_LIMIT,
  MSG_TYPE_KEY_ALIASES, MSG_TYPE_NAMES, MSG_TYPE_NAME_ALIASES, NORMALIZED_LOG_PATH, PORT,
  PROXY_PROVIDER_ACCOUNT, PROXY_PROVIDER_BASE_URL, PROXY_PROVIDER_PASSWORD, PROXY_PROVIDER_SECRET,
  PROXY_PROVIDER_SIGN, RAGFLOW_BASE_URL, RAGFLOW_CHAT_ID, RAGFLOW_DATASET_IDS, RAGFLOW_DATASET_NAMES, RAGFLOW_ENABLED,
  RAGFLOW_LOGIN_EMAIL, RAGFLOW_LOGIN_PASSWORD, RAGFLOW_LOGIN_PUBLIC_KEY, RAGFLOW_SEARCH_SIMILARITY,
  RAGFLOW_TIMEOUT_MS, RAGFLOW_TOP_K, RAGFLOW_VECTOR_SIMILARITY_WEIGHT, ROUTING_LOG_PATH,
  SERVICE_FILE_PATH, SERVICE_NAME, TARGET_ROOM_IDS, TRANSCRIBE_ENABLED, TRANSCRIBE_LANGUAGE,
  TRANSCRIBE_MODEL, TRANSCRIBE_PYTHON, TRANSCRIBE_SCRIPT_PATH, TRANSCRIBE_TIMEOUT_MS, UPSTREAM_WECOM_API_BASE,
} = runtimeConfig;

const {
  applyTranscriptRecord,
  buildMediaPublicUrl,
  chooseStoredMimeType,
  dedupeMessageEventsByTraceId,
  inferExtension,
  inferMimeFromExtension,
  normalizeMsgTypeKey,
  normalizeMsgTypeLabel,
  sanitizeFileSegment,
} = createMediaMessageUtils({
  MSG_TYPE_KEY_ALIASES,
  MSG_TYPE_NAMES,
  MSG_TYPE_NAME_ALIASES,
});
const {
  downloadBinary,
  downloadBinaryWithHeaders,
  requestJson,
  requestJsonWithHeaders,
  requestStreamingChatText,
} = createFlowbotNetworkClients({ MEDIA_DOWNLOAD_TIMEOUT_MS });

const {
  dashboardDataCache,
  countJsonlFile,
  getLocalFileVersion,
  readJsonFile,
  readJsonlFile,
  rewriteJsonlFile,
  unlinkIfExists,
  writeJsonFile,
} = createFlowbotStorageBootstrap({
  DASHBOARD_DEFAULT_LIMIT,
  DATA_DIR,
  MEDIA_DIR,
  fs,
  mysqlRuntimeStore,
});

let knowledgeHarvestService = null;

function enqueueKnowledgeHarvestMessage(message) {
  return knowledgeHarvestService?.enqueueKnowledgeHarvestMessage(message) || null;
}

const {
  buildPublicMediaUrl,
  extractLlmResponseText,
  loadNormalizedEvents,
  loadNormalizedMessageMap,
  messageTimestampMs,
  normalizeKnowledgeCandidatePatch,
  parseArchiveStdout,
  requestLlmClassify,
  tryParseClassifyJson,
} = createFlowbotServerHelpers({
  DASHBOARD_PUBLIC_URL,
  LLM_API_KEY,
  LLM_API_URL,
  LLM_MODEL,
  LLM_TIMEOUT_MS,
  LLM_TIMEOUT_RETRY_ATTEMPTS,
  LLM_TIMEOUT_RETRY_BASE_DELAY_MS,
  LLM_TIMEOUT_RETRY_MAX_DELAY_MS,
  NORMALIZED_LOG_PATH,
  dedupeMessageEventsByTraceId,
  invokeWithLlmTimeoutRetry,
  readJsonlFile,
  requestJsonWithHeaders,
  requestStreamingChatText,
});

const hashText = createHashText(crypto);

const {
  assertSafeLocalKnowledgePath,
  computeTokenOverlapScore,
  findLocalKnowledgeDocument,
  normalizeKnowledgeSourceInput,
  normalizeMemorySourceInput,
  readKnowledgeDocuments,
  searchLocalKnowledgeDocuments,
  summarizeSnippet,
  tokenizeSearchText,
} = createLocalKnowledgeService({
  KNOWLEDGE_DIR,
  KNOWLEDGE_SOURCE_VALUES,
  MEMORY_SOURCE_VALUES,
  fs,
  hashText,
  path,
});

const {
  detectConfigManagerMode,
  mergeConfigInput,
  readServiceConfig,
  scheduleLocalServiceRestart,
  scheduleServiceRestart,
  writeLocalServiceConfig,
  writeRuntimeConfig,
  writeServiceConfig,
} = createFlowbotConfigManager({
  AGENT_WAKE_NAMES,
  ARCHIVE_ENABLED,
  ARCHIVE_MODE,
  CASE_ARCHIVE_NOTIFY_ENABLED,
  CONFIG_TEST_PATH,
  DATA_DIR,
  FEISHU_APP_ID,
  FEISHU_APP_SECRET,
  FEISHU_OAUTH_REDIRECT_URI,
  FEISHU_OAUTH_SCOPE,
  FEISHU_TARGET_CHAT_IDS,
  FEISHU_VERIFICATION_TOKEN,
  FLOWBOT_STORAGE_BACKEND,
  KNOWLEDGE_HARVEST_ENABLED,
  KNOWLEDGE_HARVEST_MAX_PER_SCAN,
  KNOWLEDGE_HARVEST_READY_AGE_MS,
  KNOWLEDGE_HARVEST_ROOM_IDS,
  KNOWLEDGE_HARVEST_SCAN_INTERVAL_MS,
  KNOWLEDGE_DIR,
  LLM_API_URL,
  LLM_CLASSIFY_ENABLED,
  LLM_MAX_REPAIR_ATTEMPTS,
  LLM_MODEL,
  LLM_TIMEOUT_MS,
  LLM_TIMEOUT_RETRY_ATTEMPTS,
  LLM_TIMEOUT_RETRY_BASE_DELAY_MS,
  LLM_TIMEOUT_RETRY_MAX_DELAY_MS,
  IMAGE_SUMMARY_ENABLED,
  IMAGE_SUMMARY_MAX_BYTES,
  IMAGE_SUMMARY_MODEL,
  IMAGE_SUMMARY_TIMEOUT_MS,
  RAGFLOW_CHAT_ID,
  LOCAL_LAUNCH_AGENT_LABEL,
  LOCAL_LAUNCH_AGENT_PLIST_PATH,
  LOCAL_MANAGED_CONFIG_PATH,
  SERVICE_FILE_PATH,
  SERVICE_NAME,
  TARGET_ROOM_IDS,
  TRANSCRIBE_ENABLED,
  TRANSCRIBE_LANGUAGE,
  TRANSCRIBE_MODEL,
  TRANSCRIBE_PYTHON,
  TRANSCRIBE_TIMEOUT_MS,
  legacyLocalManagedEnvPath:
    process.env.FLOWBOT_LOCAL_MANAGED_ENV_PATH
    || path.resolve(__dirname, "..", "..", "config", "flowbot.local.env"),
  readRuntimeSettings: mysqlRuntimeStore.readRuntimeSettings,
  readJsonFile,
  writeRuntimeSettings: mysqlRuntimeStore.writeRuntimeSettings,
});

const {
  appendArchiveDecision,
  appendBatchDecision,
  appendEvent,
  appendFilterDecision,
  appendKnowledgePublishResult,
  appendMessageSearchRecord,
  appendNormalizedEvent,
  appendRoutingDecision,
  buildMessageSearchRecord,
} = createFlowbotLogWriters({
  ARCHIVE_LOG_PATH,
  BATCH_LOG_PATH,
  DATA_DIR,
  FILTER_LOG_PATH,
  KNOWLEDGE_PUBLISH_LOG_PATH,
  LOG_PATH,
  MESSAGE_SEARCH_INDEX_PATH,
  NORMALIZED_LOG_PATH,
  ROUTING_LOG_PATH,
  buildPublicMediaUrl,
  enqueueKnowledgeHarvestMessage,
  mysqlRuntimeStore,
  tokenizeSearchText,
});

const {
  runLlmConnectivityTest,
} = createConfigConnectivityService({
  CONFIG_TEST_PATH,
  SERVICE_FILE_PATH,
  SERVICE_NAME,
  TRANSCRIBE_SCRIPT_PATH,
  extractLlmResponseText,
  fs,
  requestJsonWithHeaders,
  spawnSync,
  writeJsonFile,
});

const {
  buildProxyProviderUrl,
  fetchUpstreamRoomDetails,
  fetchUpstreamProxy,
  getUpstreamLoginQrcode,
  parseProxyProviderInput,
  setUpstreamClientProxy,
  setUpstreamNotifyUrl,
  toQrcodeDataUri,
  verifyUpstreamLoginQrcode,
} = createUpstreamLoginClient({
  DEFAULT_LOGIN_REGION,
  MEDIA_DOWNLOAD_TIMEOUT_MS,
  PROXY_PROVIDER_ACCOUNT,
  PROXY_PROVIDER_BASE_URL,
  PROXY_PROVIDER_PASSWORD,
  PROXY_PROVIDER_SECRET,
  PROXY_PROVIDER_SIGN,
  UPSTREAM_WECOM_API_BASE,
  requestJson,
  safeParseJson,
});

const {
  buildFeishuAuthorizeUrl,
  createFeishuOauthState,
  exchangeFeishuUserAccessToken,
  fetchFeishuUserInfo,
  getFeishuAppAccessToken,
  readFeishuOauthResult,
  readFeishuOauthState,
  renderFeishuOauthResultHtml,
  writeFeishuOauthResult,
} = createFeishuOauthService({
  FEISHU_APP_ACCESS_TOKEN_URL,
  FEISHU_APP_ID,
  FEISHU_APP_SECRET,
  FEISHU_AUTHORIZE_URL,
  FEISHU_OAUTH_REDIRECT_URI,
  FEISHU_OAUTH_RESULT_PATH,
  FEISHU_OAUTH_SCOPE,
  FEISHU_OAUTH_STATE_PATH,
  FEISHU_USER_ACCESS_TOKEN_URL,
  FEISHU_USER_INFO_URL,
  URL,
  crypto,
  maskSecret,
  readJsonFile,
  requestJson,
  requestJsonWithHeaders,
  writeJsonFile,
});

const {
  searchKnowledgeDocuments,
  searchMaxkbKnowledgeDocuments,
  searchRagflowKnowledgeDocuments,
  toFiniteScore,
} = createKnowledgeSearchClients({
  MAXKB_BASE_URL,
  MAXKB_CACHE_TTL_MS,
  MAXKB_ENABLED,
  MAXKB_KNOWLEDGE_FILTER,
  MAXKB_KNOWLEDGE_PREFIX_FILTER,
  MAXKB_PASSWORD,
  MAXKB_SEARCH_MODE,
  MAXKB_SEARCH_SIMILARITY,
  MAXKB_TIMEOUT_MS,
  MAXKB_USERNAME,
  MAXKB_WORKSPACE_ID,
  RAGFLOW_BASE_URL,
  RAGFLOW_DATASET_IDS,
  RAGFLOW_DATASET_NAMES,
  RAGFLOW_ENABLED,
  RAGFLOW_LOGIN_EMAIL,
  RAGFLOW_LOGIN_PASSWORD,
  RAGFLOW_LOGIN_PUBLIC_KEY,
  RAGFLOW_SEARCH_SIMILARITY,
  RAGFLOW_TIMEOUT_MS,
  RAGFLOW_TOP_K,
  RAGFLOW_VECTOR_SIMILARITY_WEIGHT,
  hashText,
  normalizeKnowledgeSourceInput,
  requestJson,
  requestJsonWithHeaders,
  searchLocalKnowledgeDocuments,
  summarizeSnippet,
});

const {
  buildKnowledgeAnswer,
  buildKnowledgeAnswerFallbackText,
} = createKnowledgeAnswerService({
  LLM_CLASSIFY_ENABLED,
  LLM_MAX_REPAIR_ATTEMPTS,
  normalizeKnowledgeSourceInput,
  requestLlmClassify,
  searchKnowledgeDocuments,
  toFiniteScore,
  tryParseClassifyJson,
});

const {
  askKnowledgeBot,
  isRagflowBotReady,
  listKnowledgeBots,
} = createKnowledgeBotService({
  RAGFLOW_BASE_URL,
  RAGFLOW_CHAT_ID,
  RAGFLOW_ENABLED,
  RAGFLOW_LOGIN_EMAIL,
  RAGFLOW_LOGIN_PASSWORD,
  RAGFLOW_LOGIN_PUBLIC_KEY,
  RAGFLOW_TIMEOUT_MS,
  mysqlRuntimeStore,
  requestJsonWithHeaders,
});

const {
  buildArchiveMessageContent,
  buildBatchPlannerOpenCase,
  buildBatchPlannerPendingMessage,
  buildLlmReadyMessage,
  containsAny,
  detectPriority,
  extractKeywords,
  isAuxiliaryArchiveContent,
  isWeakSummaryText,
  normalizeArchiveText,
  normalizeMentionIdList,
  normalizePriority,
  normalizeWakeText,
  shouldDelayMediaOnlyCase,
} = createMessageTextUtils({
  CASE_KEYWORDS,
  FEATURE_KEYWORDS,
  INCIDENT_KEYWORDS,
  PRIORITY_ALIASES,
  PRIORITY_KEYWORDS,
  buildPublicMediaUrl,
  normalizeMsgTypeKey,
});

const {
  isFeishuChatIdAllowed,
  isRoomIdAllowed,
  listRoomMessages,
  loadAllCaseItems,
  normalizePriorityItem,
} = createServerLocalHelpers({
  DATA_DIR,
  FEISHU_TARGET_CHAT_IDS,
  NORMALIZED_LOG_PATH,
  TARGET_ROOM_IDS,
  buildLlmReadyMessage,
  dedupeMessageEventsByTraceId,
  messageTimestampMs,
  normalizePriority,
  path,
  readJsonFile,
  readJsonlFile,
});

const {
  buildAttentionItem,
  buildAvailableRooms,
  buildCountBreakdown,
  buildSimpleCountBreakdown,
  compareTimeDesc,
  computeDashboardAgeMs,
  computeLatencyPartMs,
  computeTaskDurationMs,
  filterItemsByRoom,
  getItemRoomId,
  getItemRoomName,
  parseDashboardTimeMs,
  readCaseArtifacts,
  summarizeAgentTaskForDashboard,
  summarizeAgentTaskStatus,
  summarizePoolStatus,
  summarizeReason,
  summarizeThreadReason,
} = createDashboardSummaryUtils({
  AGENT_PRIMARY_WAKE_NAME,
  normalizePriority,
  readJsonFile,
});

const {
  buildLlmImageParts,
  collectAgentVisionInputs,
  collectAgentVisionInputsFromContext,
  resolveAgentMediaRenderOptions,
} = createAgentVisionUtils({
  buildLlmReadyMessage,
  normalizeBooleanInput,
  normalizeMsgTypeKey,
  pruneEmpty,
});

const {
  buildMessageSearchSnippet,
  getStoredMessageByTraceId,
  loadMessageSearchRecords,
  normalizeOptionalSearchText,
  parseSearchTimeMs,
  resolveStoredMessageSearch,
  searchCaseMessages,
  searchStoredMessages,
  searchStoredMessagesWithContext,
  searchUnifiedMemory,
} = createMessageSearchService({
  DATA_DIR,
  MESSAGE_CONTEXT_MAX_NEIGHBORS,
  MESSAGE_SEARCH_DEFAULT_LIMIT,
  MESSAGE_SEARCH_INDEX_PATH,
  MESSAGE_SEARCH_MAX_LIMIT,
  NORMALIZED_LOG_PATH,
  buildMessageSearchRecord,
  collectAgentVisionInputs,
  collectAgentVisionInputsFromContext,
  computeTokenOverlapScore,
  dedupeMessageEventsByTraceId,
  fs,
  hashText,
  loadAllCaseItems,
  messageTimestampMs,
  mysqlRuntimeStore,
  normalizeMemorySourceInput,
  normalizePriority,
  normalizeBooleanInput,
  readCaseArtifacts,
  readJsonlFile,
  resolveAgentMediaRenderOptions,
  summarizeSnippet,
  toFiniteScore,
  tokenizeSearchText,
});

const {
  getDateSummary,
  getHistorySummary,
  getRoomSummary,
} = createMessageSummaryService({
  HISTORY_SUMMARY_MAX_BUCKETS,
  MESSAGE_SEARCH_MAX_LIMIT,
  SUMMARY_STOPWORDS,
  buildMessageSearchSnippet,
  messageTimestampMs,
  parseSearchTimeMs,
  resolveStoredMessageSearch,
});

const {
  buildCaseProgressPayload,
  findCaseById,
  findRelatedCases,
  getCaseTimeline,
  searchCases,
} = createCaseQueryService({
  compareTimeDesc,
  computeTokenOverlapScore,
  loadAllCaseItems,
  normalizePriority,
  normalizePriorityItem,
  parseSearchTimeMs,
  readCaseArtifacts,
  searchStoredMessages,
});

const {
  buildAgentTaskId,
  claimAgentTask,
  patchAgentTasks,
  patchKnowledgeHarvestMessages,
  patchMessagePoolEntries,
  readAgentTaskState,
  readKnowledgeHarvestState,
  readMessagePoolState,
  upsertAgentTask,
  upsertKnowledgeCandidateIndex,
  upsertMessagePoolEntry,
  writeAgentTaskState,
  writeKnowledgeHarvestState,
  writeMessagePoolState,
} = createRuntimeStateService({
  AGENT_RUNTIME_ID,
  AGENT_SESSION_KEY_STRATEGY,
  AGENT_TASK_CLAIM_TIMEOUT_MS,
  AGENT_TASK_STATE_PATH,
  KNOWLEDGE_HARVEST_STATE_PATH,
  MESSAGE_POOL_STATE_PATH,
  buildAgentSessionBinding,
  buildLlmReadyMessage,
  compareTimeDesc,
  hashText,
  readJsonFile,
  requeueStaleClaimedTasks,
  writeJsonFile,
});

const {
  buildAgentTaskContext,
  buildTaskAgentState,
  findAgentTaskById,
} = createAgentTaskContextService({
  AGENT_RUNTIME_ID,
  AGENT_SESSION_KEY_STRATEGY,
  buildCaseProgressPayload,
  findCaseById,
  listRoomMessages,
  readAgentTaskState,
  searchCases,
  searchLocalKnowledgeDocuments,
  summarizeAgentTaskStatus,
});

const {
  enrichMediaForMessage,
  getMediaContentType,
} = createMediaEnrichmentService({
  CDN_DOWNLOAD_ENDPOINT,
  MEDIA_DIR,
  MEDIA_DOWNLOAD_TIMEOUT_MS,
  MEDIA_DOWNLOAD_TYPES,
  MEDIA_INDEX_PATH,
  TRANSCRIBE_ENABLED,
  TRANSCRIBE_LANGUAGE,
  TRANSCRIBE_MODEL,
  TRANSCRIBE_PYTHON,
  TRANSCRIBE_SCRIPT_PATH,
  TRANSCRIBE_TIMEOUT_MS,
  IMAGE_SUMMARY_ENABLED,
  IMAGE_SUMMARY_MAX_BYTES,
  IMAGE_SUMMARY_MODEL,
  IMAGE_SUMMARY_TIMEOUT_MS,
  LLM_API_KEY,
  LLM_API_URL,
  applyTranscriptRecord,
  buildPublicMediaUrl,
  buildMediaPublicUrl,
  chooseStoredMimeType,
  downloadBinary,
  downloadBinaryWithHeaders,
  extractLlmResponseText,
  fs,
  getFeishuAppAccessToken,
  hashText,
  inferExtension,
  inferMimeFromExtension,
  path,
  readJsonFile,
  requestJson,
  requestJsonWithHeaders,
  sanitizeFileSegment,
  spawnSync,
  writeJsonFile,
});

const {
  buildTraceId,
  normalizePayload,
  toIsoTime,
} = createWecomMessageNormalizer({
  MSG_TYPE_NAMES,
});

const {
  buildFeishuTraceId,
  evaluateFeishuPayload,
  normalizeFeishuPayload,
  pickFeishuSenderId,
} = createFeishuMessageNormalizer({
  FEISHU_APP_ID,
  FEISHU_MESSAGE_TYPE_TO_FLOWBOT,
  FEISHU_VERIFICATION_TOKEN,
  MSG_TYPE_NAMES,
  isFeishuChatIdAllowed,
  toIsoTime,
});

const {
  routeNormalizedMessage,
} = createAgentRouteService({
  AGENT_LANE_ENABLED,
  AGENT_WAKE_NAMES,
  buildLlmReadyMessage,
  normalizeMentionIdList,
  normalizeWakeText,
});

const {
  buildCaseArchiveNotificationText,
  buildCaseArchiveSolutionText,
  buildCaseSolutionFallbackText,
  buildCaseSolutionSearchQuery,
  buildDashboardUrl,
  buildUpstreamConversationId,
  formatCaseSolutionFromKnowledge,
  isFeishuAgentTask,
  pickArchiveSummary,
  sendAgentReplyMessage,
  sendFeishuTextMessage,
  sendRoomArchiveNotification,
} = createArchiveNotificationService({
  CASE_KEYWORDS,
  CATEGORY_LABELS,
  DASHBOARD_PUBLIC_URL,
  FEISHU_SEND_MESSAGE_URL,
  FEATURE_KEYWORDS,
  INCIDENT_KEYWORDS,
  MEDIA_DOWNLOAD_TIMEOUT_MS,
  PORT,
  UPSTREAM_WECOM_API_BASE,
  buildArchiveMessageContent,
  containsAny,
  getFeishuAppAccessToken,
  isWeakSummaryText,
  normalizeArchiveText,
  normalizeMsgTypeKey,
  normalizePriority,
  requestJson,
  requestJsonWithHeaders,
  searchKnowledgeDocuments,
});


knowledgeHarvestService = createKnowledgeHarvestService({
  DATA_DIR,
  KNOWLEDGE_CANDIDATES_PATH,
  KNOWLEDGE_DIR,
  KNOWLEDGE_HARVEST_ENABLED,
  KNOWLEDGE_HARVEST_MAX_PER_SCAN,
  KNOWLEDGE_HARVEST_READY_AGE_MS,
  KNOWLEDGE_HARVEST_ROOM_IDS,
  LLM_CLASSIFY_ENABLED,
  NORMALIZED_LOG_PATH,
  appendKnowledgePublishResult,
  assertSafeLocalKnowledgePath,
  compareTimeDesc,
  dedupeMessageEventsByTraceId,
  findLocalKnowledgeDocument,
  fs,
  hashText,
  loadNormalizedMessageMap,
  messageTimestampMs,
  mysqlRuntimeStore,
  patchKnowledgeHarvestMessages,
  path,
  readJsonlFile,
  readKnowledgeHarvestState,
  requestLlmClassify,
  searchKnowledgeDocuments,
  tryParseClassifyJson,
  upsertKnowledgeCandidateIndex,
  writeKnowledgeHarvestState,
});

const {
  appendKnowledgeCandidate,
  buildKnowledgeCandidateId,
  buildKnowledgeHarvestContext,
  buildKnowledgeHarvestMessages,
  buildKnowledgeHarvestSearchQuery,
  findKnowledgeCandidate,
  formatKnowledgeCandidateMarkdown,
  formatKnowledgeCandidateUpdateMarkdown,
  isKnowledgeHarvestRoomAllowed,
  judgeKnowledgeCandidateByLlm,
  listEligibleKnowledgeHarvestMessages,
  listKnowledgeCandidates,
  normalizeKnowledgeHarvestText,
  normalizeRelatedKnowledgeForHarvest,
  publishKnowledgeCandidateToLocal,
  rewriteKnowledgeCandidate,
  runKnowledgeHarvestProcessor,
  sanitizeKnowledgeFileName,
  shouldQueueKnowledgeHarvestMessage,
  updateExistingKnowledgeFromCandidate,
  validateKnowledgeHarvestPayload,
} = knowledgeHarvestService;

const {
  archivePendingGroup,
  buildArchivePayloadForGroup,
  buildBatchPlannerMessages,
  buildOpenCaseContext,
  listEligiblePendingMessages,
  normalizeBatchPlannerCategory,
  planPendingGroupsByLlm,
  recordBatchGroupDecision,
  requeueStaleProcessingMessages,
  runArchiveScript,
  runPendingBatchProcessor,
  validateBatchPlannerPayload,
} = createBatchProcessorService({
  ACTIVE_CASE_STATUSES,
  ARCHIVE_PYTHON,
  ARCHIVE_SCRIPT_PATH,
  BATCH_MAX_OPEN_CASES,
  BATCH_MAX_PENDING_PER_ROOM,
  BATCH_MEDIA_ONLY_HOLD_MS,
  BATCH_MODE_ENABLED,
  BATCH_OPEN_CASE_LOOKBACK_MS,
  BATCH_PROCESSING_STALE_MS,
  BATCH_READY_AGE_MS,
  CASE_ARCHIVE_NOTIFY_ENABLED,
  DATA_DIR,
  LLM_MAX_REPAIR_ATTEMPTS,
  appendArchiveDecision,
  appendBatchDecision,
  buildArchiveMessageContent,
  buildBatchPlannerOpenCase,
  buildBatchPlannerPendingMessage,
  buildCaseArchiveNotificationText,
  buildDashboardUrl,
  buildLlmImageParts,
  buildLlmReadyMessage,
  compareTimeDesc,
  detectPriority,
  extractKeywords,
  fs,
  loadNormalizedMessageMap,
  messageTimestampMs,
  mysqlRuntimeStore,
  normalizePriority,
  os,
  parseArchiveStdout,
  path,
  patchMessagePoolEntries,
  pickArchiveSummary,
  readCaseArtifacts,
  readJsonFile,
  readMessagePoolState,
  requestLlmClassify,
  sendAgentReplyMessage,
  shouldDelayMediaOnlyCase,
  spawnSync,
  tryParseClassifyJson,
});

const {
  cleanupDashboardNoise,
  clearRoomArchive,
  clearRoomMemory,
  clearRoomSession,
  compactRoomAgentState,
} = createDashboardRoomActionsService({
  ARCHIVE_LOG_PATH,
  BATCH_LOG_PATH,
  BATCH_READY_AGE_MS,
  DATA_DIR,
  MESSAGE_POOL_STATE_PATH,
  MESSAGE_SEARCH_INDEX_PATH,
  NORMALIZED_LOG_PATH,
  computeDashboardAgeMs,
  path,
  readAgentTaskState,
  readJsonFile,
  readKnowledgeHarvestState,
  readMessagePoolState,
  rewriteJsonlFile,
  unlinkIfExists,
  writeAgentTaskState,
  writeJsonFile,
  writeKnowledgeHarvestState,
  writeMessagePoolState,
});

const {
  buildDailySummary,
  buildDashboardData,
  countItemsOnDashboardDate,
  getDashboardLocalDateKey,
  getDashboardRelativeDateKey,
  itemMatchesDashboardDate,
  normalizeDashboardMessageItem,
} = createDashboardDataService({
  ACCEPT_NOTIFY_TYPES,
  AGENT_LANE_ENABLED,
  AGENT_SESSION_KEY_STRATEGY,
  AGENT_TASK_STATE_PATH,
  AGENT_WAKE_NAMES,
  ARCHIVE_ENABLED,
  ARCHIVE_LOG_PATH,
  ARCHIVE_MODE,
  BATCH_LOG_PATH,
  BATCH_MAX_PENDING_PER_ROOM,
  BATCH_MODE_ENABLED,
  BATCH_READY_AGE_MS,
  BATCH_SCAN_INTERVAL_MS,
  CASE_ARCHIVE_NOTIFY_ENABLED,
  DATA_DIR,
  DASHBOARD_DEFAULT_LIMIT,
  DASHBOARD_MAX_LIMIT,
  FEISHU_TARGET_CHAT_IDS,
  FILTER_LOG_PATH,
  KNOWLEDGE_CANDIDATES_PATH,
  KNOWLEDGE_HARVEST_ENABLED,
  KNOWLEDGE_HARVEST_MAX_PER_SCAN,
  KNOWLEDGE_HARVEST_READY_AGE_MS,
  KNOWLEDGE_HARVEST_ROOM_IDS,
  KNOWLEDGE_HARVEST_SCAN_INTERVAL_MS,
  KNOWLEDGE_HARVEST_STATE_PATH,
  KNOWLEDGE_PUBLISH_LOG_PATH,
  LLM_CLASSIFY_ENABLED,
  LLM_MODEL,
  LOG_PATH,
  MESSAGE_POOL_STATE_PATH,
  MSG_TYPE_NAMES,
  NORMALIZED_LOG_PATH,
  ROUTING_LOG_PATH,
  SUPPORTED_MSG_TYPES,
  TARGET_ROOM_IDS,
  TRANSCRIBE_ENABLED,
  TRANSCRIBE_MODEL,
  buildAttentionItem,
  buildAvailableRooms,
  buildCountBreakdown,
  buildSimpleCountBreakdown,
  buildTraceId,
  compareTimeDesc,
  computeDashboardAgeMs,
  computeLatencyPartMs,
  computeTaskDurationMs,
  dashboardDataCache,
  dedupeMessageEventsByTraceId,
  filterItemsByRoom,
  getItemRoomId,
  getItemRoomName,
  getLocalFileVersion,
  mysqlRuntimeStore,
  normalizeMsgTypeLabel,
  normalizePriority,
  parseArchiveStdout,
  path,
  readAgentTaskState,
  readCaseArtifacts,
  readJsonFile,
  readJsonlFile,
  readKnowledgeHarvestState,
  readMessagePoolState,
  summarizeAgentTaskForDashboard,
  summarizeAgentTaskStatus,
  summarizePoolStatus,
  summarizeReason,
  summarizeThreadReason,
  toIsoTime,
});

const server = createFlowbotHttpServer({
  ...runtimeConfig,
  appendEvent, appendFilterDecision, appendKnowledgeCandidate, appendKnowledgePublishResult, appendNormalizedEvent, appendRoutingDecision,
  askKnowledgeBot, buildAckTaskPatch, buildAgentTaskContext, buildCaseProgressPayload, buildDashboardData,
  buildFeishuAuthorizeUrl, buildFeishuTraceId, buildKnowledgeAnswer, buildKnowledgeAnswerFallbackText,
  buildKnowledgeCandidateId,
  buildProxyProviderUrl, buildTraceId, claimAgentTask, cleanupDashboardNoise, clearRoomArchive,
  clearRoomMemory, clearRoomSession, collectBody, compactRoomAgentState, compareTimeDesc,
  createFeishuOauthState, detectConfigManagerMode, enrichMediaForMessage, escapeHtml,
  evaluateFeishuPayload, exchangeFeishuUserAccessToken, fetchFeishuUserInfo, fetchUpstreamRoomDetails, fetchUpstreamProxy,
  findAgentTaskById, findCaseById, findKnowledgeCandidate, findRelatedCases, fs,
  getCaseTimeline, getDateSummary, getHistorySummary, getFeishuAppAccessToken,
  getLocalManagedEnvPath: () => LOCAL_MANAGED_ENV_PATH,
  getMediaContentType, getRoomSummary, getStoredMessageByTraceId, getUpstreamLoginQrcode,
  isRagflowBotReady, isRoomIdAllowed, listKnowledgeBots, listKnowledgeCandidates, listRoomMessages, maskSecret, mergeConfigInput,
  normalizeBooleanInput, normalizeFeishuPayload, normalizeKnowledgeCandidatePatch,
  normalizeKnowledgeSourceInput, normalizeMemorySourceInput, normalizePayload, parseProxyProviderInput,
  patchAgentTasks, patchKnowledgeHarvestMessages, path, pickFeishuSenderId, publishKnowledgeCandidateToLocal, readAgentTaskState,
  readCaseArtifacts, readFeishuOauthResult, readFeishuOauthState, readKnowledgeHarvestState, readMessagePoolState, readServiceConfig,
  requestJsonWithHeaders,
  renderFeishuOauthResultHtml, rewriteKnowledgeCandidate, routeNormalizedMessage,
  runKnowledgeHarvestProcessor, runLlmConnectivityTest, runPendingBatchProcessor, safeParseJson,
  scheduleLocalServiceRestart, scheduleServiceRestart, searchCaseMessages, searchCases,
  searchKnowledgeDocuments, searchStoredMessages, searchStoredMessagesWithContext, searchUnifiedMemory,
  sendAgentReplyMessage, sendFile, sendHtml, sendJson, sendRedirect, setUpstreamClientProxy,
  setUpstreamNotifyUrl, summarizeAgentTaskStatus, toQrcodeDataUri, updateExistingKnowledgeFromCandidate,
  upsertAgentTask, upsertMessagePoolEntry, verifyUpstreamLoginQrcode, writeFeishuOauthResult,
  writeLocalServiceConfig, writeRuntimeConfig, writeServiceConfig,
});

startFlowbotServer({
  ...runtimeConfig,
  requeueStaleProcessingMessages, runKnowledgeHarvestProcessor, runPendingBatchProcessor, server,
});
