const http = require("http");
const { URL } = require("url");
const { createAgentApiRoutes } = require("./agent_api_routes");
const { createBridgeManagementRoutes } = require("./bridge_management_routes");
const { createCallbackRoutes } = require("./callback_routes");
const { createConfigRoutes } = require("./config_routes");
const { createDashboardHtmlRenderer } = require("./dashboard_html_renderer");
const { createRouteChain } = require("./flowbot_route_chain");
const { createProxyHelperHtmlRenderer } = require("./proxy_helper_html_renderer");

function createFlowbotHttpServer(deps) {
  const {
    AGENT_PRIMARY_WAKE_NAME,
    AGENT_TASK_FETCH_LIMIT,
    ARCHIVE_MODE,
    BATCH_ACTION_LABELS,
    BATCH_LOG_PATH,
    BATCH_MODE_ENABLED,
    CASE_STATUS_LABELS,
    CATEGORY_LABELS,
    DASHBOARD_DEFAULT_LIMIT,
    DASHBOARD_UI_VERSION,
    DEFAULT_LOGIN_REGION,
    DEFAULT_NOTIFY_URL,
    FEISHU_APP_ID,
    FEISHU_OAUTH_REDIRECT_URI,
    FEISHU_OAUTH_SCOPE,
    FEISHU_TARGET_CHAT_IDS,
    FEISHU_VERIFICATION_TOKEN,
    FILTER_LOG_PATH,
    LOCAL_LAUNCH_AGENT_LABEL,
    LOCAL_MANAGED_CONFIG_PATH,
    LOG_PATH,
    LOGIN_REGION_OPTIONS,
    MEDIA_DIR,
    MEDIA_DOWNLOAD_TIMEOUT_MS,
    MESSAGE_CONTEXT_MAX_NEIGHBORS,
    MESSAGE_POOL_STATE_PATH,
    MESSAGE_ROLE_LABELS,
    MESSAGE_SEARCH_INDEX_PATH,
    NORMALIZED_LOG_PATH,
    PORT,
    SERVICE_FILE_PATH,
    SERVICE_NAME,
    SUPPORTED_MSG_TYPES,
    TARGET_ROOM_IDS,
    THREAD_TYPE_LABELS,
    ACCEPT_NOTIFY_TYPES,
    appendKnowledgeCandidate,
    appendEvent,
    appendFilterDecision,
    appendKnowledgePublishResult,
    appendNormalizedEvent,
    appendRoutingDecision,
    askKnowledgeBot,
    buildAckTaskPatch,
    buildAgentTaskContext,
    buildCaseProgressPayload,
    buildKnowledgeCandidateId,
    buildFeishuAuthorizeUrl,
    buildFeishuTraceId,
    buildKnowledgeAnswer,
    buildKnowledgeAnswerFallbackText,
    buildProxyProviderUrl,
    buildTraceId,
    claimAgentTask,
    cleanupDashboardNoise,
    clearRoomArchive,
    clearRoomMemory,
    clearRoomSession,
    collectBody,
    compactRoomAgentState,
    compareTimeDesc,
    createFeishuOauthState,
    detectConfigManagerMode,
    enrichMediaForMessage,
    escapeHtml,
    evaluateFeishuPayload,
    exchangeFeishuUserAccessToken,
    fetchFeishuUserInfo,
    fetchUpstreamRoomDetails,
    fetchUpstreamProxy,
    findAgentTaskById,
    findCaseById,
    findKnowledgeCandidate,
    findRelatedCases,
    fs,
    getCaseTimeline,
    getDateSummary,
    getHistorySummary,
    getLocalManagedEnvPath,
    getMediaContentType,
    getFeishuAppAccessToken,
    getRoomSummary,
    getStoredMessageByTraceId,
    getUpstreamLoginQrcode,
    isRoomIdAllowed,
    isRagflowBotReady,
    listKnowledgeBots,
    listKnowledgeCandidates,
    listRoomMessages,
    maskSecret,
    mergeConfigInput,
    normalizeBooleanInput,
    normalizeFeishuPayload,
    normalizeKnowledgeCandidatePatch,
    normalizeKnowledgeSourceInput,
    normalizeMemorySourceInput,
    normalizePayload,
    parseProxyProviderInput,
    patchAgentTasks,
    patchKnowledgeHarvestMessages,
    path,
    pickFeishuSenderId,
    publishKnowledgeCandidateToLocal,
    readAgentTaskState,
    readCaseArtifacts,
    readFeishuOauthResult,
    readFeishuOauthState,
    readKnowledgeHarvestState,
    readMessagePoolState,
    requestJsonWithHeaders,
    readServiceConfig,
    renderFeishuOauthResultHtml,
    rewriteKnowledgeCandidate,
    routeNormalizedMessage,
    runKnowledgeHarvestProcessor,
    runLlmConnectivityTest,
    runPendingBatchProcessor,
    safeParseJson,
    scheduleLocalServiceRestart,
    scheduleServiceRestart,
    searchCaseMessages,
    searchCases,
    searchKnowledgeDocuments,
    searchStoredMessages,
    searchStoredMessagesWithContext,
    searchUnifiedMemory,
    sendAgentReplyMessage,
    sendFile,
    sendHtml,
    sendJson,
    sendRedirect,
    setUpstreamClientProxy,
    setUpstreamNotifyUrl,
    summarizeAgentTaskStatus,
    toQrcodeDataUri,
    updateExistingKnowledgeFromCandidate,
    upsertAgentTask,
    upsertMessagePoolEntry,
    verifyUpstreamLoginQrcode,
    writeFeishuOauthResult,
    writeLocalServiceConfig,
    writeRuntimeConfig,
    writeServiceConfig,
  } = deps;

  const { renderDashboardHtml } = createDashboardHtmlRenderer({
    AGENT_PRIMARY_WAKE_NAME,
    BATCH_ACTION_LABELS,
    CASE_STATUS_LABELS,
    CATEGORY_LABELS,
    DASHBOARD_DEFAULT_LIMIT,
    DASHBOARD_UI_VERSION,
    DEFAULT_LOGIN_REGION,
    DEFAULT_NOTIFY_URL,
    LOGIN_REGION_OPTIONS,
    MESSAGE_ROLE_LABELS,
    THREAD_TYPE_LABELS,
    escapeHtml,
  });

  const { renderProxyHelperHtml } = createProxyHelperHtmlRenderer({
    DASHBOARD_UI_VERSION,
    DEFAULT_LOGIN_REGION,
    DEFAULT_NOTIFY_URL,
    LOGIN_REGION_OPTIONS,
    buildProxyProviderUrl,
    escapeHtml,
  });

  const { handleBridgeManagementRoute } = createBridgeManagementRoutes({
    ARCHIVE_MODE,
    BATCH_LOG_PATH,
    BATCH_MODE_ENABLED,
    DASHBOARD_DEFAULT_LIMIT,
    DEFAULT_LOGIN_REGION,
    FEISHU_APP_ID,
    FEISHU_OAUTH_REDIRECT_URI,
    FEISHU_OAUTH_SCOPE,
    FEISHU_TARGET_CHAT_IDS,
    FILTER_LOG_PATH,
    LOCAL_MANAGED_CONFIG_PATH,
    LOG_PATH,
    LOGIN_REGION_OPTIONS,
    MEDIA_DIR,
    MEDIA_DOWNLOAD_TIMEOUT_MS,
    MESSAGE_POOL_STATE_PATH,
    NORMALIZED_LOG_PATH,
    PORT,
    TARGET_ROOM_IDS,
    buildDashboardData: deps.buildDashboardData,
    buildFeishuAuthorizeUrl,
    buildProxyProviderUrl,
    cleanupDashboardNoise,
    clearRoomArchive,
    clearRoomMemory,
    clearRoomSession,
    collectBody,
    compactRoomAgentState,
    createFeishuOauthState,
    exchangeFeishuUserAccessToken,
    fetchFeishuUserInfo,
    fetchUpstreamRoomDetails,
    fetchUpstreamProxy,
    fs,
    getFeishuAppAccessToken,
    getMediaContentType,
    getUpstreamLoginQrcode,
    maskSecret,
    parseProxyProviderInput,
    path,
    readFeishuOauthResult,
    readFeishuOauthState,
    readMessagePoolState,
    requestJsonWithHeaders,
    renderDashboardHtml,
    renderFeishuOauthResultHtml,
    renderProxyHelperHtml,
    runPendingBatchProcessor,
    safeParseJson,
    sendFile,
    sendHtml,
    sendJson,
    sendRedirect,
    setUpstreamClientProxy,
    setUpstreamNotifyUrl,
    toQrcodeDataUri,
    verifyUpstreamLoginQrcode,
    writeFeishuOauthResult,
  });

  const { handleCallbackRoute } = createCallbackRoutes({
    ACCEPT_NOTIFY_TYPES,
    FEISHU_VERIFICATION_TOKEN,
    SUPPORTED_MSG_TYPES,
    appendEvent,
    appendFilterDecision,
    appendNormalizedEvent,
    appendRoutingDecision,
    buildFeishuTraceId,
    buildTraceId,
    collectBody,
    enrichMediaForMessage,
    evaluateFeishuPayload,
    isRoomIdAllowed,
    normalizeFeishuPayload,
    normalizePayload,
    pickFeishuSenderId,
    routeNormalizedMessage,
    safeParseJson,
    sendJson,
    upsertAgentTask,
    upsertMessagePoolEntry,
  });

  const { handleConfigRoute } = createConfigRoutes({
    LOCAL_LAUNCH_AGENT_LABEL,
    SERVICE_FILE_PATH,
    SERVICE_NAME,
    collectBody,
    detectConfigManagerMode,
    getLocalManagedEnvPath,
    maskSecret,
    mergeConfigInput,
    readServiceConfig,
    runLlmConnectivityTest,
    safeParseJson,
    listKnowledgeBots,
    scheduleLocalServiceRestart,
    scheduleServiceRestart,
    sendJson,
    writeLocalServiceConfig,
    writeRuntimeConfig,
    writeServiceConfig,
  });

  const { handleAgentApiRoute } = createAgentApiRoutes({
    AGENT_TASK_FETCH_LIMIT,
    MESSAGE_CONTEXT_MAX_NEIGHBORS,
    MESSAGE_SEARCH_INDEX_PATH,
    appendKnowledgeCandidate,
    appendKnowledgePublishResult,
    buildAckTaskPatch,
    buildAgentTaskContext,
    buildCaseProgressPayload,
    buildKnowledgeCandidateId,
    buildKnowledgeAnswer,
    buildKnowledgeAnswerFallbackText,
    askKnowledgeBot,
    claimAgentTask,
    collectBody,
    compareTimeDesc,
    findAgentTaskById,
    findCaseById,
    findKnowledgeCandidate,
    findRelatedCases,
    getCaseTimeline,
    getDateSummary,
    getHistorySummary,
    getRoomSummary,
    getStoredMessageByTraceId,
    listKnowledgeCandidates,
    listRoomMessages,
    normalizeBooleanInput,
    normalizeKnowledgeCandidatePatch,
    normalizeKnowledgeSourceInput,
    normalizeMemorySourceInput,
    isRagflowBotReady,
    patchAgentTasks,
    patchKnowledgeHarvestMessages,
    publishKnowledgeCandidateToLocal,
    readAgentTaskState,
    readCaseArtifacts,
    readKnowledgeHarvestState,
    rewriteKnowledgeCandidate,
    runKnowledgeHarvestProcessor,
    safeParseJson,
    searchCaseMessages,
    searchCases,
    searchKnowledgeDocuments,
    searchStoredMessages,
    searchStoredMessagesWithContext,
    searchUnifiedMemory,
    sendAgentReplyMessage,
    sendJson,
    summarizeAgentTaskStatus,
    updateExistingKnowledgeFromCandidate,
  });

  const routeChain = createRouteChain({
    handlers: [
      handleBridgeManagementRoute,
      handleConfigRoute,
      handleAgentApiRoute,
      handleCallbackRoute,
    ],
    onNotFound: (_req, res, url) => sendJson(res, 404, {
      ok: false,
      error: "not_found",
      path: url.pathname,
    }),
  });

  return http.createServer(async (req, res) => {
    const url = new URL(req.url || "/", `http://${req.headers.host || "127.0.0.1"}`);
    await routeChain.handle(req, res, url);
  });
}

module.exports = {
  createFlowbotHttpServer,
};
