"use strict";

module.exports = [
  "<!doctype html>\n",
  "<html lang=\"zh-CN\">\n",
  "<head>\n",
  "  <meta charset=\"UTF-8\">\n",
  "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n",
  "  <title>Flowbot Dashboard</title>\n",
  "  <style>\n",
  "    :root {\n",
  "      --bg: #f5f7fa;\n",
  "      --panel: #ffffff;\n",
  "      --line: #e4e7ec;\n",
  "      --text: #101828;\n",
  "      --muted: #667085;\n",
  "      --accent: #2f1f3a;\n",
  "      --accent-soft: #fbf8fe;\n",
  "      --warn: #7c2d12;\n",
  "      --warn-soft: #fff0e3;\n",
  "      --danger: #b42318;\n",
  "      --danger-soft: #fff0ee;\n",
  "      --ok: #2f1f3a;\n",
  "      --ok-soft: #e7f5ec;\n",
  "      --shadow: none;\n",
  "    }\n",
  "    * { box-sizing: border-box; }\n",
  "    body {\n",
  "      margin: 0;\n",
  "      font-family: \"PingFang SC\", \"Microsoft YaHei\", sans-serif;\n",
  "      color: var(--text);\n",
  "      background: var(--bg);\n",
  "    }\n",
  "    .wrap {\n",
  "      width: min(1500px, calc(100% - 24px));\n",
  "      margin: 12px auto 24px;\n",
  "    }\n",
  "    .hero, .panel {\n",
  "      background: var(--panel);\n",
  "      border: 1px solid var(--line);\n",
  "      border-radius: 8px;\n",
  "      box-shadow: var(--shadow);\n",
  "    }\n",
  "    .hero {\n",
  "      display: none;\n",
  "    }\n",
  "    h1 {\n",
  "      margin: 0 0 6px;\n",
  "      font-size: 22px;\n",
  "      line-height: 1.25;\n",
  "    }\n",
  "    .hero p {\n",
  "      margin: 0;\n",
  "      color: var(--muted);\n",
  "      line-height: 1.6;\n",
  "      max-width: 900px;\n",
  "    }\n",
  "    .meta {\n",
  "      display: flex;\n",
  "      gap: 14px;\n",
  "      flex-wrap: wrap;\n",
  "      margin-top: 16px;\n",
  "      color: var(--muted);\n",
  "      font-size: 14px;\n",
  "    }\n",
  "    .meta button {\n",
  "      border: 1px solid var(--line);\n",
  "      background: rgba(255,255,255,0.78);\n",
  "      color: var(--text);\n",
  "      border-radius: 999px;\n",
  "      padding: 6px 12px;\n",
  "      cursor: pointer;\n",
  "      font-size: 13px;\n",
  "    }\n",
  "    .meta select {\n",
  "      border: 1px solid var(--line);\n",
  "      background: rgba(255,255,255,0.9);\n",
  "      color: var(--text);\n",
  "      border-radius: 999px;\n",
  "      padding: 6px 12px;\n",
  "      font-size: 13px;\n",
  "      min-width: 220px;\n",
  "    }\n",
  "    .stats {\n",
  "      display: grid;\n",
  "      gap: 12px;\n",
  "      margin-bottom: 12px;\n",
  "    }\n",
  "    #stats {\n",
  "      display: none;\n",
  "    }\n",
  "    .hero .meta {\n",
  "      display: none;\n",
  "    }\n",
  "    .room-workspace {\n",
  "      display: grid;\n",
  "      grid-template-columns: minmax(0, 1fr);\n",
  "      gap: 12px;\n",
  "      align-items: start;\n",
  "    }\n",
  "    #dashboard-detail-page {\n",
  "      display: none;\n",
  "    }\n",
  "    .dashboard-list-page {\n",
  "      display: grid;\n",
  "      gap: 12px;\n",
  "      padding: 16px;\n",
  "    }\n",
  "    .dashboard-list-head,\n",
  "    .dashboard-list-toolbar,\n",
  "    .dashboard-list-pager {\n",
  "      display: flex;\n",
  "      align-items: center;\n",
  "      justify-content: space-between;\n",
  "      gap: 12px;\n",
  "      flex-wrap: wrap;\n",
  "    }\n",
  "    .dashboard-list-head h2 {\n",
  "      margin: 0 0 6px;\n",
  "      font-size: 20px;\n",
  "    }\n",
  "    .dashboard-list-head .hint {\n",
  "      margin: 0;\n",
  "    }\n",
  "    .dashboard-list-head-actions {\n",
  "      display: flex;\n",
  "      align-items: center;\n",
  "      gap: 10px;\n",
  "      flex-wrap: wrap;\n",
  "    }\n",
  "    .dashboard-list-toolbar input,\n",
  "    .dashboard-list-toolbar select {\n",
  "      border: 1px solid var(--line);\n",
  "      background: rgba(255,255,255,0.9);\n",
  "      color: var(--text);\n",
  "      border-radius: 16px;\n",
  "      box-shadow: 0 1px 2px rgba(15,23,42,0.04);\n",
  "      font-size: 15px;\n",
  "      font-weight: 600;\n",
  "      height: 44px;\n",
  "      outline: none;\n",
  "      transition: border-color 0.16s ease, box-shadow 0.16s ease, background 0.16s ease;\n",
  "    }\n",
  "    .dashboard-list-toolbar input:focus,\n",
  "    .dashboard-list-toolbar select:focus {\n",
  "      border-color: rgba(37,99,235,0.45);\n",
  "      box-shadow: 0 0 0 3px rgba(37,99,235,0.10);\n",
  "    }\n",
  "    .dashboard-list-toolbar input {\n",
  "      width: min(560px, 100%);\n",
  "      padding: 0 18px;\n",
  "      font-weight: 500;\n",
  "    }\n",
  "    .dashboard-list-toolbar select {\n",
  "      appearance: none;\n",
  "      min-width: 188px;\n",
  "      padding: 0 44px 0 18px;\n",
  "      cursor: pointer;\n",
  "      background-color: rgba(255,255,255,0.94);\n",
  "      background-image: url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='18' height='18' viewBox='0 0 24 24' fill='none' stroke='%230f172a' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m6 9 6 6 6-6'/%3E%3C/svg%3E\");\n",
  "      background-repeat: no-repeat;\n",
  "      background-position: right 16px center;\n",
  "      background-size: 18px 18px;\n",
  "    }\n",
  "    .dashboard-table-wrap {\n",
  "      overflow: auto;\n",
  "      border: 1px solid var(--line);\n",
  "      border-radius: 8px;\n",
  "      background: #fff;\n",
  "    }\n",
  "    .dashboard-table {\n",
  "      width: 100%;\n",
  "      border-collapse: collapse;\n",
  "      min-width: 860px;\n",
  "    }\n",
  "    .dashboard-table th,\n",
  "    .dashboard-table td {\n",
  "      padding: 13px 14px;\n",
  "      border-bottom: 1px solid var(--line);\n",
  "      text-align: left;\n",
  "      vertical-align: middle;\n",
  "      font-size: 13px;\n",
  "    }\n",
  "    .dashboard-table th {\n",
  "      color: var(--muted);\n",
  "      font-weight: 700;\n",
  "      background: #fcfcfd;\n",
  "    }\n",
  "    .dashboard-table tr:last-child td {\n",
  "      border-bottom: 0;\n",
  "    }\n",
  "    .dashboard-table .room-name {\n",
  "      display: grid;\n",
  "      gap: 5px;\n",
  "    }\n",
  "    .room-title-row {\n",
  "      display: flex;\n",
  "      align-items: center;\n",
  "      gap: 8px;\n",
  "      flex-wrap: wrap;\n",
  "    }\n",
  "    .dashboard-table .room-name strong {\n",
  "      font-size: 14px;\n",
  "      line-height: 1.35;\n",
  "    }\n",
  "    .dashboard-table .room-name small {\n",
  "      color: var(--muted);\n",
  "      word-break: break-all;\n",
  "    }\n",
  "    .platform-badge {\n",
  "      display: inline-flex;\n",
  "      align-items: center;\n",
  "      justify-content: center;\n",
  "      min-width: 44px;\n",
  "      height: 22px;\n",
  "      padding: 0 8px;\n",
  "      border-radius: 999px;\n",
  "      border: 1px solid var(--line);\n",
  "      background: #f8fafc;\n",
  "      color: #475467;\n",
  "      font-size: 12px;\n",
  "      font-weight: 700;\n",
  "      white-space: nowrap;\n",
  "    }\n",
  "    .platform-badge.feishu {\n",
  "      background: #eef4ff;\n",
  "      color: #175cd3;\n",
  "      border-color: #c7d7fe;\n",
  "    }\n",
  "    .platform-badge.wecom {\n",
  "      background: #ecfdf3;\n",
  "      color: #027a48;\n",
  "      border-color: #abefc6;\n",
  "    }\n",
  "    .table-action {\n",
  "      border: 1px solid var(--accent);\n",
  "      background: var(--accent);\n",
  "      color: #fff;\n",
  "      border-radius: 8px;\n",
  "      padding: 7px 12px;\n",
  "      cursor: pointer;\n",
  "      font-size: 13px;\n",
  "      white-space: nowrap;\n",
  "    }\n",
  "    .dashboard-list-pager {\n",
  "      color: var(--muted);\n",
  "      font-size: 13px;\n",
  "    }\n",
  "    .dashboard-list-pager button {\n",
  "      border: 1px solid var(--line);\n",
  "      background: #fff;\n",
  "      color: var(--text);\n",
  "      border-radius: 8px;\n",
  "      padding: 7px 12px;\n",
  "      cursor: pointer;\n",
  "    }\n",
  "    .dashboard-list-pager button:disabled {\n",
  "      opacity: 0.45;\n",
  "      cursor: not-allowed;\n",
  "    }\n",
  "    .dashboard-settings-page {\n",
  "      display: none;\n",
  "      gap: 16px;\n",
  "    }\n",
  "    .dashboard-settings-grid {\n",
  "      display: grid;\n",
  "      gap: 16px;\n",
  "    }\n",
  "    .dashboard-settings-section {\n",
  "      display: none;\n",
  "    }\n",
  "    .dashboard-settings-section.active {\n",
  "      display: block;\n",
  "    }\n",
  "    .room-sidebar {\n",
  "      display: none;\n",
  "    }\n",
  "    .room-sidebar h2,\n",
  "    .room-detail-head h2 {\n",
  "      margin: 0 0 6px;\n",
  "      font-size: 18px;\n",
  "    }\n",
  "    .room-sidebar .hint,\n",
  "    .room-detail-head .hint {\n",
  "      margin: 0;\n",
  "    }\n",
  "    .room-search {\n",
  "      border: 1px solid var(--line);\n",
  "      background: #fff;\n",
  "      color: var(--text);\n",
  "      border-radius: 8px;\n",
  "      padding: 10px 12px;\n",
  "      width: 100%;\n",
  "      font-size: 14px;\n",
  "    }\n",
  "    .room-list-actions,\n",
  "    .room-danger-actions {\n",
  "      display: grid;\n",
  "      grid-template-columns: repeat(2, minmax(0, 1fr));\n",
  "      gap: 8px;\n",
  "    }\n",
  "    .room-list-actions button,\n",
  "    .room-danger-actions button {\n",
  "      border: 1px solid var(--line);\n",
  "      background: #fff;\n",
  "      color: var(--text);\n",
  "      border-radius: 8px;\n",
  "      padding: 9px 10px;\n",
  "      cursor: pointer;\n",
  "      font-size: 13px;\n",
  "    }\n",
  "    .room-list-actions button.primary {\n",
  "      background: var(--accent);\n",
  "      border-color: var(--accent);\n",
  "      color: #fff;\n",
  "    }\n",
  "    .room-danger-actions button {\n",
  "      color: var(--warn);\n",
  "      background: var(--warn-soft);\n",
  "    }\n",
  "    .room-list {\n",
  "      min-height: 260px;\n",
  "      overflow: auto;\n",
  "      display: grid;\n",
  "      gap: 8px;\n",
  "      padding-right: 2px;\n",
  "    }\n",
  "    .room-item {\n",
  "      width: 100%;\n",
  "      text-align: left;\n",
  "      border: 1px solid var(--line);\n",
  "      background: #fff;\n",
  "      color: var(--text);\n",
  "      border-radius: 7px;\n",
  "      padding: 11px 12px;\n",
  "      cursor: pointer;\n",
  "      display: grid;\n",
  "      gap: 8px;\n",
  "    }\n",
  "    .room-item:hover {\n",
  "      background: rgba(255,255,255,0.96);\n",
  "    }\n",
  "    .room-item.active {\n",
  "      border-color: var(--accent);\n",
  "      background: var(--accent-soft);\n",
  "      box-shadow: none;\n",
  "    }\n",
  "    .room-item strong {\n",
  "      line-height: 1.35;\n",
  "      word-break: break-word;\n",
  "    }\n",
  "    .room-item small {\n",
  "      color: var(--muted);\n",
  "      line-height: 1.35;\n",
  "      word-break: break-word;\n",
  "    }\n",
  "    .room-counts {\n",
  "      display: flex;\n",
  "      flex-wrap: wrap;\n",
  "      gap: 6px;\n",
  "    }\n",
  "    .room-counts span {\n",
  "      font-size: 12px;\n",
  "      color: var(--muted);\n",
  "      border: 1px solid var(--line);\n",
  "      border-radius: 999px;\n",
  "      padding: 3px 7px;\n",
  "      background: #fcfcfd;\n",
  "    }\n",
  "    .room-detail {\n",
  "      min-width: 0;\n",
  "      display: grid;\n",
  "      gap: 14px;\n",
  "    }\n",
  "    .room-detail-head {\n",
  "      padding: 16px 18px;\n",
  "    }\n",
  "    .room-detail-meta {\n",
  "      display: flex;\n",
  "      gap: 10px;\n",
  "      flex-wrap: wrap;\n",
  "      margin-top: 12px;\n",
  "      color: var(--muted);\n",
  "      font-size: 13px;\n",
  "    }\n",
  "    .room-detail-meta span {\n",
  "      border: 1px solid var(--line);\n",
  "      border-radius: 999px;\n",
  "      padding: 5px 9px;\n",
  "      background: #fcfcfd;\n",
  "    }\n",
  "    .dashboard-nav {\n",
  "      position: sticky;\n",
  "      top: 0;\n",
  "      z-index: 20;\n",
  "      padding: 8px;\n",
  "      margin-bottom: 12px;\n",
  "      display: flex;\n",
  "      align-items: center;\n",
  "      justify-content: space-between;\n",
  "      gap: 8px;\n",
  "      flex-wrap: wrap;\n",
  "      border-radius: 8px;\n",
  "    }\n",
  "    .dashboard-tab-buttons {\n",
  "      display: flex;\n",
  "      gap: 8px;\n",
  "      flex-wrap: wrap;\n",
  "    }\n",
  "    .dashboard-tab-buttons button {\n",
  "      border: 1px solid transparent;\n",
  "      background: transparent;\n",
  "      color: var(--muted);\n",
  "      border-radius: 7px;\n",
  "      padding: 9px 14px;\n",
  "      cursor: pointer;\n",
  "      font-size: 14px;\n",
  "      line-height: 1;\n",
  "    }\n",
  "    .dashboard-tab-buttons button:hover {\n",
  "      color: var(--text);\n",
  "      background: var(--accent-soft);\n",
  "    }\n",
  "    .dashboard-tab-buttons button.active {\n",
  "      color: #fff;\n",
  "      background: var(--accent);\n",
  "      box-shadow: none;\n",
  "    }\n",
  "    .dashboard-nav-refresh {\n",
  "      margin-left: auto;\n",
  "      border: 1px solid var(--line);\n",
  "      background: #fff;\n",
  "      color: var(--text);\n",
  "      border-radius: 7px;\n",
  "      padding: 9px 13px;\n",
  "      cursor: pointer;\n",
  "      font-size: 13px;\n",
  "      font-weight: 700;\n",
  "      line-height: 1;\n",
  "    }\n",
  "    .dashboard-nav-refresh:hover {\n",
  "      border-color: var(--accent);\n",
  "      background: var(--accent-soft);\n",
  "    }\n",
  "    .dashboard-nav-refresh:disabled {\n",
  "      cursor: wait;\n",
  "      color: var(--muted);\n",
  "      background: #f8fafc;\n",
  "    }\n",
  "    .dashboard-tab-shell {\n",
  "      display: grid;\n",
  "      gap: 12px;\n",
  "    }\n",
  "    .dashboard-tab {\n",
  "      display: none;\n",
  "      gap: 12px;\n",
  "    }\n",
  "    .dashboard-tab.active {\n",
  "      display: grid;\n",
  "    }\n",
  "    .dashboard-tab-grid {\n",
  "      display: grid;\n",
  "      grid-template-columns: repeat(2, minmax(0, 1fr));\n",
  "      gap: 12px;\n",
  "      align-items: start;\n",
  "    }\n",
  "    .dashboard-tab-grid.single {\n",
  "      grid-template-columns: 1fr;\n",
  "    }\n",
  "    .dashboard-tab-grid .panel {\n",
  "      margin: 0;\n",
  "    }\n",
  "    #legacy-dashboard-layout {\n",
  "      display: none;\n",
  "    }\n",
  "    .flow-summary {\n",
  "      padding: 16px 18px;\n",
  "      border-radius: 8px;\n",
  "      border: 1px solid var(--line);\n",
  "      background: #fcfcfd;\n",
  "    }\n",
  "    .flow-summary strong {\n",
  "      display: block;\n",
  "      font-size: 16px;\n",
  "      margin-bottom: 6px;\n",
  "    }\n",
  "    .flow-summary span {\n",
  "      color: var(--muted);\n",
  "      font-size: 13px;\n",
  "      line-height: 1.6;\n",
  "    }\n",
  "    .pipeline {\n",
  "      display: flex;\n",
  "      align-items: stretch;\n",
  "      gap: 12px;\n",
  "      overflow-x: auto;\n",
  "      padding-bottom: 4px;\n",
  "    }\n",
  "    .pipeline-node {\n",
  "      min-width: 180px;\n",
  "      flex: 0 0 180px;\n",
  "      position: relative;\n",
  "      padding: 16px 18px 18px;\n",
  "      border-radius: 8px;\n",
  "      border: 1px solid var(--line);\n",
  "      background: #fff;\n",
  "      overflow: hidden;\n",
  "      isolation: isolate;\n",
  "    }\n",
  "    .pipeline-node::before {\n",
  "      content: \"\";\n",
  "      position: absolute;\n",
  "      inset: 0;\n",
  "      background: var(--accent-soft);\n",
  "      z-index: -1;\n",
  "      opacity: 0.32;\n",
  "    }\n",
  "    .pipeline-node.done {\n",
  "      border-color: var(--line);\n",
  "      box-shadow: none;\n",
  "    }\n",
  "    .pipeline-node.current {\n",
  "      border-color: var(--accent);\n",
  "      box-shadow: none;\n",
  "    }\n",
  "    .pipeline-node.current::before {\n",
  "      opacity: 1;\n",
  "      background: var(--accent-soft);\n",
  "    }\n",
  "    .pipeline-node.pending {\n",
  "      opacity: 0.72;\n",
  "    }\n",
  "    .pipeline-connector {\n",
  "      position: relative;\n",
  "      flex: 0 0 58px;\n",
  "      min-width: 58px;\n",
  "      align-self: center;\n",
  "      height: 18px;\n",
  "    }\n",
  "    .pipeline-connector::before {\n",
  "      content: \"\";\n",
  "      position: absolute;\n",
  "      left: 0;\n",
  "      right: 16px;\n",
  "      top: 50%;\n",
  "      transform: translateY(-50%);\n",
  "      height: 3px;\n",
  "      border-radius: 999px;\n",
  "      background: #d8c7e8;\n",
  "    }\n",
  "    .pipeline-connector::after {\n",
  "      content: \">\";\n",
  "      position: absolute;\n",
  "      right: 0;\n",
  "      top: 50%;\n",
  "      transform: translateY(-56%);\n",
  "      font-size: 22px;\n",
  "      font-weight: 700;\n",
  "      color: #b99ad0;\n",
  "    }\n",
  "    .pipeline-connector.active::before {\n",
  "      background: var(--accent);\n",
  "    }\n",
  "    .pipeline-connector.active::after {\n",
  "      color: var(--accent);\n",
  "    }\n",
  "    .pipeline-index {\n",
  "      display: inline-flex;\n",
  "      width: 28px;\n",
  "      height: 28px;\n",
  "      align-items: center;\n",
  "      justify-content: center;\n",
  "      border-radius: 999px;\n",
  "      background: var(--accent-soft);\n",
  "      color: var(--accent);\n",
  "      font-size: 12px;\n",
  "      font-weight: 700;\n",
  "      margin-bottom: 10px;\n",
  "    }\n",
  "    .pipeline-node.done .pipeline-index,\n",
  "    .pipeline-node.current .pipeline-index {\n",
  "      background: var(--accent);\n",
  "      color: #fff;\n",
  "    }\n",
  "    .pipeline-label {\n",
  "      font-size: 13px;\n",
  "      color: var(--muted);\n",
  "      margin-bottom: 8px;\n",
  "    }\n",
  "    .pipeline-value {\n",
  "      font-size: 30px;\n",
  "      font-weight: 700;\n",
  "      line-height: 1;\n",
  "    }\n",
  "    .branch-stats {\n",
  "      display: grid;\n",
  "      grid-template-columns: repeat(3, minmax(0, 1fr));\n",
  "      gap: 12px;\n",
  "    }\n",
  "    .branch-card {\n",
  "      padding: 14px 16px;\n",
  "      border-radius: 8px;\n",
  "      border: 1px solid var(--line);\n",
  "      background: #fff;\n",
  "    }\n",
  "    .branch-card .label {\n",
  "      font-size: 12px;\n",
  "      color: var(--muted);\n",
  "      margin-bottom: 8px;\n",
  "    }\n",
  "    .branch-card .value {\n",
  "      font-size: 24px;\n",
  "      font-weight: 700;\n",
  "      line-height: 1;\n",
  "    }\n",
  "    .branch-card .desc {\n",
  "      margin-top: 8px;\n",
  "      font-size: 12px;\n",
  "      color: var(--muted);\n",
  "    }\n",
  "    .attention-grid {\n",
  "      display: grid;\n",
  "      grid-template-columns: repeat(3, minmax(0, 1fr));\n",
  "      gap: 12px;\n",
  "    }\n",
  "    .attention-card {\n",
  "      padding: 14px 16px;\n",
  "      border-radius: 8px;\n",
  "      border: 1px solid var(--line);\n",
  "      background: #fff;\n",
  "      min-width: 0;\n",
  "    }\n",
  "    .attention-card.warn {\n",
  "      border-color: rgba(178,91,42,0.28);\n",
  "      background: var(--warn-soft);\n",
  "    }\n",
  "    .attention-card.danger {\n",
  "      border-color: rgba(165,56,44,0.28);\n",
  "      background: var(--danger-soft);\n",
  "    }\n",
  "    .attention-card .topline {\n",
  "      display: flex;\n",
  "      align-items: center;\n",
  "      justify-content: space-between;\n",
  "      gap: 10px;\n",
  "      margin-bottom: 8px;\n",
  "    }\n",
  "    .attention-card .title {\n",
  "      font-size: 14px;\n",
  "      font-weight: 800;\n",
  "      line-height: 1.3;\n",
  "    }\n",
  "    .attention-card .count {\n",
  "      font-size: 24px;\n",
  "      font-weight: 800;\n",
  "      line-height: 1;\n",
  "    }\n",
  "    .attention-card .desc,\n",
  "    .attention-card .action {\n",
  "      color: var(--muted);\n",
  "      font-size: 12px;\n",
  "      line-height: 1.55;\n",
  "      word-break: break-word;\n",
  "    }\n",
  "    .attention-card .action {\n",
  "      margin-top: 8px;\n",
  "      color: var(--accent);\n",
  "      font-weight: 700;\n",
  "    }\n",
  "    .daily-grid {\n",
  "      display: grid;\n",
  "      grid-template-columns: repeat(4, minmax(0, 1fr));\n",
  "      gap: 12px;\n",
  "    }\n",
  "    .daily-card {\n",
  "      padding: 14px 16px;\n",
  "      border-radius: 8px;\n",
  "      border: 1px solid var(--line);\n",
  "      background: #fff;\n",
  "      min-width: 0;\n",
  "    }\n",
  "    .daily-card .label {\n",
  "      color: var(--muted);\n",
  "      font-size: 12px;\n",
  "      line-height: 1.35;\n",
  "    }\n",
  "    .daily-card .value {\n",
  "      margin-top: 6px;\n",
  "      font-size: 26px;\n",
  "      line-height: 1;\n",
  "      font-weight: 800;\n",
  "    }\n",
  "    .daily-card .desc {\n",
  "      margin-top: 8px;\n",
  "      color: var(--muted);\n",
  "      font-size: 12px;\n",
  "      line-height: 1.55;\n",
  "      word-break: break-word;\n",
  "    }\n",
  "    .daily-notes {\n",
  "      display: flex;\n",
  "      flex-wrap: wrap;\n",
  "      gap: 8px;\n",
  "      margin-top: 12px;\n",
  "    }\n",
  "    @keyframes stepGlow {\n",
  "      0%, 100% { opacity: 0.7; }\n",
  "      50% { opacity: 1; }\n",
  "    }\n",
  "    @keyframes lineFlow {\n",
  "      0% { filter: brightness(0.95); opacity: 0.7; }\n",
  "      50% { filter: brightness(1.12); opacity: 1; }\n",
  "      100% { filter: brightness(0.95); opacity: 0.7; }\n",
  "    }\n",
  "    .layout {\n",
  "      display: grid;\n",
  "      grid-template-columns: 1.15fr 0.85fr;\n",
  "      gap: 12px;\n",
  "    }\n",
  "    .col {\n",
  "      display: grid;\n",
  "      gap: 12px;\n",
  "      align-content: start;\n",
  "    }\n",
  "    .panel {\n",
  "      padding: 16px;\n",
  "    }\n",
  "    .panel h2 {\n",
  "      margin: 0 0 12px;\n",
  "      font-size: 16px;\n",
  "    }\n",
  "    .hint {\n",
  "      margin: 0 0 12px;\n",
  "      color: var(--muted);\n",
  "      font-size: 14px;\n",
  "      line-height: 1.6;\n",
  "    }\n",
  "    .grid-2 {\n",
  "      display: grid;\n",
  "      grid-template-columns: repeat(2, minmax(0, 1fr));\n",
  "      gap: 12px;\n",
  "    }\n",
  "    .mini-grid {\n",
  "      display: grid;\n",
  "      grid-template-columns: repeat(3, minmax(0, 1fr));\n",
  "      gap: 12px;\n",
  "    }\n",
  "    .mini-stat {\n",
  "      padding: 14px;\n",
  "      border-radius: 8px;\n",
  "      border: 1px solid var(--line);\n",
  "      background: #fff;\n",
  "    }\n",
  "    .mini-stat .label {\n",
  "      color: var(--muted);\n",
  "      font-size: 12px;\n",
  "      margin-bottom: 8px;\n",
  "    }\n",
  "    .mini-stat .value {\n",
  "      font-size: 22px;\n",
  "      font-weight: 700;\n",
  "    }\n",
  "    .rule {\n",
  "      padding: 14px;\n",
  "      border-radius: 8px;\n",
  "      background: #fff;\n",
  "      border: 1px solid var(--line);\n",
  "    }\n",
  "    .rule strong {\n",
  "      display: block;\n",
  "      margin-bottom: 8px;\n",
  "      font-size: 14px;\n",
  "    }\n",
  "    .config-form {\n",
  "      display: grid;\n",
  "      gap: 14px;\n",
  "    }\n",
  "    .config-grid {\n",
  "      display: grid;\n",
  "      grid-template-columns: repeat(2, minmax(0, 1fr));\n",
  "      gap: 12px;\n",
  "    }\n",
  "    .config-field {\n",
  "      display: grid;\n",
  "      gap: 6px;\n",
  "    }\n",
  "    .config-field.full {\n",
  "      grid-column: 1 / -1;\n",
  "    }\n",
  "    .config-field label {\n",
  "      color: var(--muted);\n",
  "      font-size: 12px;\n",
  "      font-weight: 700;\n",
  "    }\n",
  "    .config-section-title {\n",
  "      grid-column: 1 / -1;\n",
  "      display: flex;\n",
  "      align-items: center;\n",
  "      gap: 10px;\n",
  "      margin-top: 4px;\n",
  "      color: var(--text);\n",
  "      font-size: 14px;\n",
  "      font-weight: 800;\n",
  "    }\n",
  "    .config-section-title::after {\n",
  "      content: \"\";\n",
  "      height: 1px;\n",
  "      flex: 1;\n",
  "      background: var(--line);\n",
  "    }\n",
  "    .config-field input,\n",
  "    .config-field textarea,\n",
  "    .config-field select {\n",
  "      width: 100%;\n",
  "      border: 1px solid var(--line);\n",
  "      background: #fff;\n",
  "      color: var(--text);\n",
  "      border-radius: 8px;\n",
  "      padding: 10px 12px;\n",
  "      font-size: 14px;\n",
  "      font-family: inherit;\n",
  "    }\n",
  "    .config-field textarea {\n",
  "      min-height: 88px;\n",
  "      resize: vertical;\n",
  "    }\n",
  "    .proxy-choice {\n",
  "      grid-column: 1 / -1;\n",
  "      display: grid;\n",
  "      gap: 10px;\n",
  "      padding: 12px;\n",
  "      border: 1px solid var(--line);\n",
  "      border-radius: 10px;\n",
  "      background: #f8fafc;\n",
  "    }\n",
  "    .proxy-choice-head {\n",
  "      display: flex;\n",
  "      justify-content: space-between;\n",
  "      gap: 12px;\n",
  "      align-items: flex-start;\n",
  "      flex-wrap: wrap;\n",
  "    }\n",
  "    .proxy-choice-title {\n",
  "      font-size: 13px;\n",
  "      font-weight: 800;\n",
  "      color: var(--text);\n",
  "    }\n",
  "    .proxy-choice-note,\n",
  "    .config-help {\n",
  "      color: var(--muted);\n",
  "      font-size: 12px;\n",
  "      line-height: 1.5;\n",
  "    }\n",
  "    .proxy-choice-grid {\n",
  "      display: grid;\n",
  "      grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);\n",
  "      gap: 12px;\n",
  "      align-items: start;\n",
  "    }\n",
  "    .config-actions {\n",
  "      display: flex;\n",
  "      flex-wrap: wrap;\n",
  "      gap: 10px;\n",
  "      align-items: center;\n",
  "    }\n",
  "    .action-btn {\n",
  "      border: 1px solid var(--line);\n",
  "      border-radius: 8px;\n",
  "      padding: 10px 16px;\n",
  "      cursor: pointer;\n",
  "      font-size: 13px;\n",
  "      font-weight: 700;\n",
  "      color: var(--text);\n",
  "      background: #fff;\n",
  "    }\n",
  "    .action-btn.primary {\n",
  "      background: var(--accent);\n",
  "      color: #fff;\n",
  "      border-color: var(--accent);\n",
  "    }\n",
  "    .config-status {\n",
  "      padding: 14px 16px;\n",
  "      border-radius: 8px;\n",
  "      border: 1px solid var(--line);\n",
  "      background: #fff;\n",
  "    }\n",
  "    .config-status strong {\n",
  "      display: block;\n",
  "      margin-bottom: 6px;\n",
  "      font-size: 14px;\n",
  "    }\n",
  "    .config-status .muted + .muted {\n",
  "      margin-top: 4px;\n",
  "    }\n",
  "    .qr-login-preview {\n",
  "      display: grid;\n",
  "      gap: 12px;\n",
  "      align-items: start;\n",
  "    }\n",
  "    .qr-login-box {\n",
  "      min-height: 280px;\n",
  "      display: grid;\n",
  "      place-items: center;\n",
  "      border-radius: 8px;\n",
];
