"use strict";

module.exports = [
  "      border: 1px dashed var(--line);\n",
  "      background: #fcfcfd;\n",
  "      padding: 16px;\n",
  "      text-align: center;\n",
  "    }\n",
  "    .qr-login-box img {\n",
  "      max-width: min(100%, 320px);\n",
  "      max-height: 320px;\n",
  "      border-radius: 16px;\n",
  "      border: 1px solid var(--line);\n",
  "      background: #fff;\n",
  "      padding: 10px;\n",
  "    }\n",
  "    .login-meta-grid {\n",
  "      display: grid;\n",
  "      gap: 12px;\n",
  "      grid-template-columns: repeat(2, minmax(0, 1fr));\n",
  "    }\n",
  "    .login-meta-card {\n",
  "      padding: 12px 14px;\n",
  "      border-radius: 8px;\n",
  "      border: 1px solid var(--line);\n",
  "      background: #fff;\n",
  "    }\n",
  "    .login-meta-card .label {\n",
  "      color: var(--muted);\n",
  "      font-size: 12px;\n",
  "      margin-bottom: 8px;\n",
  "    }\n",
  "    .login-meta-card .value {\n",
  "      font-size: 14px;\n",
  "      font-weight: 700;\n",
  "      word-break: break-word;\n",
  "      line-height: 1.5;\n",
  "    }\n",
  "    .chips {\n",
  "      display: flex;\n",
  "      flex-wrap: wrap;\n",
  "      gap: 8px;\n",
  "    }\n",
  "    .chip {\n",
  "      padding: 6px 10px;\n",
  "      border-radius: 999px;\n",
  "      background: var(--accent-soft);\n",
  "      color: var(--accent);\n",
  "      font-size: 12px;\n",
  "      border: 1px solid #e1d5ea;\n",
  "    }\n",
  "    .list {\n",
  "      display: grid;\n",
  "      gap: 12px;\n",
  "    }\n",
  "    .list-items {\n",
  "      display: grid;\n",
  "      gap: 12px;\n",
  "    }\n",
  "    .pager {\n",
  "      display: flex;\n",
  "      align-items: center;\n",
  "      justify-content: space-between;\n",
  "      gap: 12px;\n",
  "      padding: 10px 12px;\n",
  "      border: 1px solid var(--line);\n",
  "      border-radius: 8px;\n",
  "      background: #fff;\n",
  "    }\n",
  "    .pager-info {\n",
  "      color: var(--muted);\n",
  "      font-size: 12px;\n",
  "    }\n",
  "    .pager-actions {\n",
  "      display: flex;\n",
  "      gap: 8px;\n",
  "    }\n",
  "    .pager button {\n",
  "      border: 1px solid var(--line);\n",
  "      background: #fff;\n",
  "      color: var(--text);\n",
  "      border-radius: 8px;\n",
  "      padding: 6px 12px;\n",
  "      cursor: pointer;\n",
  "      font-size: 12px;\n",
  "    }\n",
  "    .pager button:disabled {\n",
  "      opacity: 0.45;\n",
  "      cursor: default;\n",
  "    }\n",
  "    .item {\n",
  "      border: 1px solid var(--line);\n",
  "      border-radius: 8px;\n",
  "      padding: 14px;\n",
  "      background: #fff;\n",
  "    }\n",
  "    .item-head {\n",
  "      display: flex;\n",
  "      justify-content: space-between;\n",
  "      gap: 12px;\n",
  "      align-items: flex-start;\n",
  "      margin-bottom: 10px;\n",
  "    }\n",
  "    .item-title {\n",
  "      font-weight: 700;\n",
  "      line-height: 1.4;\n",
  "    }\n",
  "    .muted {\n",
  "      color: var(--muted);\n",
  "      font-size: 13px;\n",
  "      line-height: 1.5;\n",
  "    }\n",
  "    .badge {\n",
  "      display: inline-flex;\n",
  "      align-items: center;\n",
  "      gap: 6px;\n",
  "      border-radius: 999px;\n",
  "      padding: 6px 10px;\n",
  "      font-size: 12px;\n",
  "      white-space: nowrap;\n",
  "      border: 1px solid transparent;\n",
  "    }\n",
  "    .badge.ok { background: var(--ok-soft); color: var(--ok); border-color: rgba(47,125,83,0.14); }\n",
  "    .badge.warn { background: var(--warn-soft); color: var(--warn); border-color: rgba(178,91,42,0.14); }\n",
  "    .badge.danger { background: var(--danger-soft); color: var(--danger); border-color: rgba(165,56,44,0.14); }\n",
  "    .knowledge-kpis {\n",
  "      display: grid;\n",
  "      grid-template-columns: repeat(3, minmax(0, 1fr));\n",
  "      gap: 10px;\n",
  "      margin: 12px 0;\n",
  "    }\n",
  "    .knowledge-kpi {\n",
  "      border: 1px solid var(--line);\n",
  "      border-radius: 8px;\n",
  "      background: #fff;\n",
  "      padding: 10px 12px;\n",
  "      min-width: 0;\n",
  "    }\n",
  "    .knowledge-kpi .label {\n",
  "      color: var(--muted);\n",
  "      font-size: 12px;\n",
  "      line-height: 1.3;\n",
  "    }\n",
  "    .knowledge-kpi .value {\n",
  "      margin-top: 4px;\n",
  "      font-size: 18px;\n",
  "      line-height: 1.2;\n",
  "      font-weight: 800;\n",
  "    }\n",
  "    .knowledge-edit-form {\n",
  "      display: grid;\n",
  "      gap: 10px;\n",
  "      margin-top: 12px;\n",
  "      padding: 12px;\n",
  "      border-radius: 8px;\n",
  "      border: 1px solid var(--line);\n",
  "      background: #fcfcfd;\n",
  "    }\n",
  "    .knowledge-edit-grid {\n",
  "      display: grid;\n",
  "      grid-template-columns: repeat(2, minmax(0, 1fr));\n",
  "      gap: 10px;\n",
  "    }\n",
  "    .knowledge-edit-field {\n",
  "      display: grid;\n",
  "      gap: 5px;\n",
  "      min-width: 0;\n",
  "    }\n",
  "    .knowledge-edit-field.full {\n",
  "      grid-column: 1 / -1;\n",
  "    }\n",
  "    .knowledge-edit-field label {\n",
  "      color: var(--muted);\n",
  "      font-size: 12px;\n",
  "      font-weight: 700;\n",
  "    }\n",
  "    .knowledge-edit-field input,\n",
  "    .knowledge-edit-field textarea,\n",
  "    .knowledge-edit-field select {\n",
  "      width: 100%;\n",
  "      border: 1px solid var(--line);\n",
  "      border-radius: 8px;\n",
  "      background: #fff;\n",
  "      color: var(--text);\n",
  "      padding: 9px 10px;\n",
  "      font-size: 13px;\n",
  "      line-height: 1.45;\n",
  "      font-family: inherit;\n",
  "    }\n",
  "    .knowledge-edit-field textarea {\n",
  "      min-height: 76px;\n",
  "      resize: vertical;\n",
  "    }\n",
  "    .media-preview {\n",
  "      margin-top: 12px;\n",
  "      padding: 12px;\n",
  "      border-radius: 8px;\n",
  "      border: 1px solid var(--line);\n",
  "      background: #fcfcfd;\n",
  "    }\n",
  "    .media-preview img,\n",
  "    .media-preview video {\n",
  "      display: block;\n",
  "      max-width: min(100%, 420px);\n",
  "      max-height: 320px;\n",
  "      border-radius: 8px;\n",
  "      border: 1px solid var(--line);\n",
  "      background: #fff;\n",
  "    }\n",
  "    .media-preview audio {\n",
  "      width: min(100%, 420px);\n",
  "      margin-top: 4px;\n",
  "    }\n",
  "    .media-meta {\n",
  "      margin-top: 8px;\n",
  "      color: var(--muted);\n",
  "      font-size: 12px;\n",
  "      line-height: 1.5;\n",
  "    }\n",
  "    .media-transcript {\n",
  "      margin-top: 10px;\n",
  "      padding: 10px 12px;\n",
  "      border-radius: 8px;\n",
  "      background: #fff;\n",
  "      border: 1px solid var(--line);\n",
  "      font-size: 13px;\n",
  "      line-height: 1.65;\n",
  "      white-space: pre-wrap;\n",
  "      word-break: break-word;\n",
  "    }\n",
  "    .media-link {\n",
  "      color: var(--accent);\n",
  "      text-decoration: none;\n",
  "      font-weight: 600;\n",
  "    }\n",
  "    .message-timeline {\n",
  "      margin-top: 12px;\n",
  "      display: grid;\n",
  "      gap: 10px;\n",
  "    }\n",
  "    .timeline-title {\n",
  "      font-size: 13px;\n",
  "      color: var(--muted);\n",
  "      font-weight: 700;\n",
  "    }\n",
  "    .timeline-item {\n",
  "      border: 1px solid rgba(36,29,22,0.08);\n",
  "      border-radius: 14px;\n",
  "      padding: 12px;\n",
  "      background: rgba(255,255,255,0.82);\n",
  "    }\n",
  "    .timeline-meta {\n",
  "      color: var(--muted);\n",
  "      font-size: 12px;\n",
  "      line-height: 1.5;\n",
  "      margin-bottom: 6px;\n",
  "    }\n",
  "    .timeline-text {\n",
  "      color: var(--text);\n",
  "      font-size: 14px;\n",
  "      line-height: 1.65;\n",
  "      white-space: pre-wrap;\n",
  "      word-break: break-word;\n",
  "    }\n",
  "    details {\n",
  "      margin-top: 10px;\n",
  "    }\n",
  "    summary {\n",
  "      cursor: pointer;\n",
  "      color: var(--accent);\n",
  "      font-size: 13px;\n",
  "    }\n",
  "    pre {\n",
  "      margin: 10px 0 0;\n",
  "      padding: 12px;\n",
  "      border-radius: 14px;\n",
  "      background: #17130f;\n",
  "      color: #f6eee6;\n",
  "      overflow: auto;\n",
  "      font-size: 12px;\n",
  "      line-height: 1.55;\n",
  "    }\n",
  "    .empty {\n",
  "      padding: 18px;\n",
  "      border: 1px dashed var(--line);\n",
  "      border-radius: 18px;\n",
  "      color: var(--muted);\n",
  "      text-align: center;\n",
  "      background: rgba(255,255,255,0.52);\n",
  "    }\n",
  "    .breakdown {\n",
  "      display: grid;\n",
  "      gap: 10px;\n",
  "    }\n",
  "    .breakdown-row {\n",
  "      display: flex;\n",
  "      justify-content: space-between;\n",
  "      gap: 12px;\n",
  "      padding: 12px 14px;\n",
  "      border-radius: 14px;\n",
  "      border: 1px solid var(--line);\n",
  "      background: rgba(255,255,255,0.66);\n",
  "      font-size: 13px;\n",
  "    }\n",
  "    .agent-grid {\n",
  "      display: grid;\n",
  "      grid-template-columns: repeat(3, minmax(0, 1fr));\n",
  "      gap: 14px;\n",
  "    }\n",
  "    .agent-card {\n",
  "      padding: 16px 18px;\n",
  "      border-radius: 20px;\n",
  "      border: 1px solid var(--line);\n",
  "      background: rgba(255,255,255,0.78);\n",
  "    }\n",
  "    .agent-card strong {\n",
  "      display: block;\n",
  "      margin-bottom: 10px;\n",
  "      font-size: 15px;\n",
  "    }\n",
  "    .agent-kpis {\n",
  "      display: grid;\n",
  "      grid-template-columns: repeat(2, minmax(0, 1fr));\n",
  "      gap: 10px;\n",
  "    }\n",
  "    .agent-kpi {\n",
  "      padding: 10px 12px;\n",
  "      border-radius: 14px;\n",
  "      background: rgba(239, 232, 220, 0.55);\n",
  "      border: 1px solid rgba(213, 196, 170, 0.8);\n",
  "    }\n",
  "    .agent-kpi .label {\n",
  "      color: var(--muted);\n",
  "      font-size: 12px;\n",
  "      margin-bottom: 4px;\n",
  "    }\n",
  "    .agent-kpi .value {\n",
  "      font-size: 20px;\n",
  "      font-weight: 700;\n",
  "    }\n",
  "    .agent-card .meta-note {\n",
  "      margin-top: 10px;\n",
  "      color: var(--muted);\n",
  "      font-size: 12px;\n",
  "      line-height: 1.6;\n",
  "    }\n",
  "    .agent-list {\n",
  "      display: grid;\n",
  "      gap: 10px;\n",
  "    }\n",
  "    .agent-list-item {\n",
  "      padding: 12px 14px;\n",
  "      border-radius: 14px;\n",
  "      border: 1px solid var(--line);\n",
  "      background: rgba(255,255,255,0.7);\n",
  "    }\n",
  "    .agent-list-item .title {\n",
  "      font-size: 13px;\n",
  "      font-weight: 700;\n",
  "      margin-bottom: 4px;\n",
  "    }\n",
  "    .agent-list-item .desc {\n",
  "      color: var(--muted);\n",
  "      font-size: 12px;\n",
  "      line-height: 1.6;\n",
  "      word-break: break-word;\n",
  "    }\n",
  "    @media (max-width: 1100px) {\n",
  "      .layout { grid-template-columns: 1fr; }\n",
  "      .room-workspace { grid-template-columns: 1fr; }\n",
  "      .room-sidebar { position: static; max-height: none; }\n",
  "      .dashboard-tab-grid { grid-template-columns: 1fr; }\n",
  "      .agent-grid { grid-template-columns: 1fr; }\n",
  "    }\n",
  "    @media (max-width: 720px) {\n",
  "      .wrap { width: min(100% - 20px, 1500px); }\n",
  "      .hero, .panel { border-radius: 8px; }\n",
  "      .grid-2 { grid-template-columns: 1fr; }\n",
  "      .config-grid,\n",
  "      .proxy-choice-grid { grid-template-columns: 1fr; }\n",
  "      .login-meta-grid { grid-template-columns: 1fr; }\n",
  "      .mini-grid { grid-template-columns: 1fr; }\n",
  "      .branch-stats { grid-template-columns: 1fr; }\n",
  "      .attention-grid { grid-template-columns: 1fr; }\n",
  "      .daily-grid { grid-template-columns: 1fr; }\n",
  "      .knowledge-edit-grid { grid-template-columns: 1fr; }\n",
  "    }\n",
  "    .panel,\n",
  "    .room-item,\n",
  "    .item,\n",
  "    .rule,\n",
  "    .mini-stat,\n",
  "    .branch-card,\n",
  "    .attention-card,\n",
  "    .daily-card,\n",
  "    .agent-card,\n",
  "    .agent-list-item,\n",
  "    .breakdown-row,\n",
  "    .config-status,\n",
  "    .login-meta-card,\n",
  "    .knowledge-kpi,\n",
  "    .timeline-item {\n",
  "      border-color: var(--line) !important;\n",
  "      border-radius: 8px !important;\n",
  "      background: #fff !important;\n",
  "      box-shadow: none !important;\n",
  "    }\n",
  "    .dashboard-nav,\n",
  "    .flow-summary,\n",
  "    .pipeline-node,\n",
  "    .pager,\n",
  "    .empty,\n",
  "    .media-preview,\n",
  "    .media-transcript,\n",
  "    .knowledge-edit-form {\n",
  "      border-color: var(--line) !important;\n",
  "      border-radius: 8px !important;\n",
  "      box-shadow: none !important;\n",
  "    }\n",
  "    .room-item.active,\n",
  "    .dashboard-tab-buttons button.active,\n",
  "    .action-btn.primary,\n",
  "    .table-action,\n",
  "    .room-list-actions button.primary {\n",
  "      border-color: var(--accent) !important;\n",
  "    }\n",
  "  </style>\n",
  "</head>\n",
  "<body>\n",
  "  <div class=\"wrap\">\n",
  "    <section class=\"hero\">\n",
  "      <div class=\"meta\">\n",
  "        <span id=\"meta-now\">载入中...</span>\n",
  "        <span>页面范围：最近 <span id=\"meta-limit\">__FLOWBOT_DASHBOARD_DEFAULT_LIMIT__</span> 条</span>\n",
  "        <label>群范围：\n",
  "          <select id=\"room-selector\">\n",
  "            <option value=\"\">全部群</option>\n",
  "          </select>\n",
  "        </label>\n",
  "        <span id=\"meta-room\">当前范围：全部群</span>\n",
  "        <span id=\"meta-batch\">批处理：载入中...</span>\n",
  "        <span>UI 版本：<strong>__FLOWBOT_DASHBOARD_UI_VERSION__</strong></span>\n",
  "        <button id=\"refresh-now\" type=\"button\">立即刷新</button>\n",
  "        <button id=\"process-pending-now\" type=\"button\">立即处理待处理</button>\n",
  "        <button id=\"room-compact-session\" type=\"button\" disabled>清理状态</button>\n",
  "        <button id=\"room-clean-noise\" type=\"button\">清理看板噪音</button>\n",
  "        <button id=\"room-clear-session\" type=\"button\" disabled>清空状态</button>\n",
  "        <button id=\"room-clear-memory\" type=\"button\" disabled>清除记忆</button>\n",
  "        <button id=\"room-clear-archive\" type=\"button\" disabled>清除归档</button>\n",
  "        <span id=\"meta-room-action\">房间操作：请选择一个群</span>\n",
  "      </div>\n",
  "    </section>\n",
  "\n",
  "    <section class=\"dashboard-list-page panel\" id=\"dashboard-list-page\">\n",
  "      <div class=\"dashboard-list-head\">\n",
  "        <div>\n",
  "          <h2>后台列表</h2>\n",
  "        </div>\n",
  "        <div class=\"dashboard-list-head-actions\">\n",
  "          <button class=\"table-action\" id=\"open-dashboard-settings-system\" type=\"button\">系统配置</button>\n",
  "          <button class=\"table-action\" id=\"open-dashboard-settings-login\" type=\"button\">实例登录</button>\n",
  "          <button class=\"table-action\" id=\"dashboard-list-refresh\" type=\"button\">刷新列表</button>\n",
  "        </div>\n",
  "      </div>\n",
  "      <div class=\"dashboard-list-toolbar\">\n",
  "        <input id=\"dashboard-list-search\" type=\"search\" placeholder=\"搜索群名 / roomId\">\n",
  "        <select id=\"dashboard-list-status\">\n",
  "          <option value=\"all\">全部状态</option>\n",
  "          <option value=\"attention\">需要关注</option>\n",
  "          <option value=\"knowledge\">有知识候选</option>\n",
  "          <option value=\"case\">有 Case</option>\n",
  "        </select>\n",
  "      </div>\n",
  "      <div class=\"dashboard-table-wrap\">\n",
  "        <table class=\"dashboard-table\">\n",
  "          <thead>\n",
  "            <tr>\n",
  "              <th>群</th>\n",
  "              <th>消息</th>\n",
  "              <th>Case</th>\n",
  "              <th>Thread</th>\n",
  "              <th>知识候选</th>\n",
  "              <th>状态</th>\n",
  "              <th>操作</th>\n",
  "            </tr>\n",
  "          </thead>\n",
  "          <tbody id=\"dashboard-list-body\">\n",
  "            <tr><td colspan=\"7\">列表载入中...</td></tr>\n",
  "          </tbody>\n",
  "        </table>\n",
  "      </div>\n",
  "      <div class=\"dashboard-list-pager\">\n",
  "        <span id=\"dashboard-list-page-info\">第 1 / 1 页</span>\n",
  "        <div>\n",
  "          <button id=\"dashboard-list-prev\" type=\"button\">上一页</button>\n",
  "          <button id=\"dashboard-list-next\" type=\"button\">下一页</button>\n",
  "        </div>\n",
  "      </div>\n",
  "    </section>\n",
  "\n",
  "    <section class=\"dashboard-settings-page\" id=\"dashboard-settings-page\">\n",
  "      <section class=\"dashboard-settings-section active\" data-settings-section=\"system\">\n",
  "        <div class=\"dashboard-settings-grid\" data-dashboard-group=\"settings-system\"></div>\n",
  "      </section>\n",
  "      <section class=\"dashboard-settings-section\" data-settings-section=\"login\">\n",
  "        <div class=\"dashboard-settings-grid\" data-dashboard-group=\"settings-login\"></div>\n",
  "      </section>\n",
  "    </section>\n",
  "\n",
  "    <div class=\"room-workspace\" id=\"dashboard-detail-page\">\n",
  "      <aside class=\"room-sidebar panel\">\n",
  "        <div>\n",
  "          <h2>群列表</h2>\n",
  "          <p class=\"hint\">先选群，再看右侧详情。支持按群名或 roomId 筛选。</p>\n",
  "        </div>\n",
  "        <input class=\"room-search\" id=\"room-search\" type=\"search\" placeholder=\"搜索群名 / roomId\">\n",
  "        <div class=\"room-list-actions\">\n",
  "          <button id=\"room-list-refresh\" class=\"primary\" type=\"button\">刷新</button>\n",
  "          <button id=\"room-list-process\" type=\"button\">处理待处理</button>\n",
  "          <button id=\"room-list-knowledge\" type=\"button\">扫描知识</button>\n",
  "          <button id=\"room-list-clean-noise\" type=\"button\">清理噪音</button>\n",
  "        </div>\n",
  "        <div class=\"room-list\" id=\"room-list\"></div>\n",
  "        <div class=\"room-danger-actions\">\n",
  "          <button id=\"room-list-compact\" type=\"button\">清理状态</button>\n",
  "          <button id=\"room-list-clear-session\" type=\"button\">清空状态</button>\n",
  "          <button id=\"room-list-clear-memory\" type=\"button\">清除记忆</button>\n",
  "          <button id=\"room-list-clear-archive\" type=\"button\">清除归档</button>\n",
  "        </div>\n",
  "      </aside>\n",
  "\n",
  "      <main class=\"room-detail\">\n",
  "        <section class=\"room-detail-head panel\">\n",
  "          <div class=\"dashboard-list-head\">\n",
  "            <div>\n",
  "              <h2 id=\"room-detail-title\">全部群</h2>\n",
  "            </div>\n",
  "            <button class=\"table-action\" id=\"back-to-dashboard-list\" type=\"button\">返回列表</button>\n",
  "          </div>\n",
  "        </section>\n",
  "\n",
  "        <section class=\"dashboard-nav panel\" aria-label=\"看板分区\">\n",
  "          <div class=\"dashboard-tab-buttons\">\n",
  "          <button type=\"button\" class=\"active\" data-dashboard-tab=\"overview\">总览与流程</button>\n",
  "          <button type=\"button\" data-dashboard-tab=\"messages\">消息处理</button>\n",
  "          <button type=\"button\" data-dashboard-tab=\"cases\">Case 归档</button>\n",
  "          </div>\n",
  "          <button type=\"button\" class=\"dashboard-nav-refresh\" id=\"dashboard-detail-refresh\">刷新当前群</button>\n",
  "        </section>\n",
  "\n",
  "        <div class=\"dashboard-tab-shell\">\n",
  "          <section class=\"dashboard-tab active\" data-dashboard-pane=\"overview\">\n",
  "            <div class=\"dashboard-tab-grid single\" data-dashboard-group=\"overview\"></div>\n",
  "          </section>\n",
  "          <section class=\"dashboard-tab\" data-dashboard-pane=\"messages\">\n",
  "            <div class=\"dashboard-tab-grid\" data-dashboard-group=\"messages\"></div>\n",
  "          </section>\n",
  "          <section class=\"dashboard-tab\" data-dashboard-pane=\"cases\">\n",
  "            <div class=\"dashboard-tab-grid\" data-dashboard-group=\"cases\"></div>\n",
  "          </section>\n",
  "        </div>\n",
  "      </main>\n",
  "    </div>\n",
  "\n",
  "    <section class=\"stats\" id=\"stats\"></section>\n",
  "\n",
  "    <div class=\"layout\" id=\"legacy-dashboard-layout\">\n",
  "      <div class=\"col\">\n",
  "        <section class=\"panel\">\n",
  "          <h2>过滤规则</h2>\n",
  "          <p class=\"hint\">这里展示当前服务真正执行中的入口规则。只要是群消息且命中支持的消息类型，就会进入后续处理与归档。</p>\n",
  "          <div class=\"grid-2\">\n",
  "            <div class=\"rule\">\n",
  "              <strong>已发现群 ID</strong>\n",
  "              <div class=\"chips\" id=\"rule-rooms\"></div>\n",
  "            </div>\n",
  "            <div class=\"rule\">\n",
  "              <strong>通知类型</strong>\n",
  "              <div class=\"chips\" id=\"rule-notify\"></div>\n",
  "            </div>\n",
  "            <div class=\"rule\">\n",
  "              <strong>可处理消息类型</strong>\n",
  "              <div class=\"chips\" id=\"rule-msg-types\"></div>\n",
  "            </div>\n",
  "            <div class=\"rule\">\n",
  "              <strong>归档聚合</strong>\n",
  "              <div class=\"chips\" id=\"rule-archive\"></div>\n",
  "            </div>\n",
  "          </div>\n",
  "        </section>\n",
  "\n",
  "        <section class=\"panel\" data-dashboard-target=\"settingsSystem\">\n",
  "          <div class=\"dashboard-list-head\">\n",
  "            <h2>系统配置</h2>\n",
  "            <div class=\"dashboard-list-head-actions\">\n",
  "              <button class=\"table-action\" data-back-to-dashboard-list type=\"button\">返回列表</button>\n",
  "            </div>\n",
  "          </div>\n",
  "          <form class=\"config-form\" id=\"config-form\">\n",
  "            <div class=\"config-grid\">\n",
  "              <div class=\"config-section-title\">基础配置</div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-target-rooms\">企微群白名单</label>\n",
  "                <textarea id=\"cfg-target-rooms\" placeholder=\"每行一个企微 room_id，留空表示企微全部群放行\"></textarea>\n",
  "              </div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-feishu-target-chats\">飞书群白名单</label>\n",
  "                <textarea id=\"cfg-feishu-target-chats\" placeholder=\"每行一个飞书 chat_id，留空表示飞书全部群放行\"></textarea>\n",
  "              </div>\n",
  "              <div class=\"config-section-title\">飞书接入</div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-feishu-app-id\">飞书 App ID</label>\n",
  "                <input id=\"cfg-feishu-app-id\" type=\"text\" placeholder=\"例如：cli_xxx\">\n",
  "              </div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-feishu-app-secret\">飞书 App Secret</label>\n",
  "                <input id=\"cfg-feishu-app-secret\" type=\"password\" autocomplete=\"new-password\" placeholder=\"留空则保持当前 Secret 不变\">\n",
  "              </div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-feishu-verification-token\">飞书校验 Token</label>\n",
  "                <input id=\"cfg-feishu-verification-token\" type=\"password\" autocomplete=\"new-password\" placeholder=\"留空则保持当前 Token 不变\">\n",
  "              </div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-feishu-oauth-redirect-uri\">飞书授权回调地址</label>\n",
  "                <input id=\"cfg-feishu-oauth-redirect-uri\" type=\"text\" placeholder=\"https://你的域名/feishu/oauth/callback\">\n",
  "              </div>\n",
  "              <div class=\"config-field full\">\n",
  "                <label for=\"cfg-feishu-oauth-scope\">飞书授权范围</label>\n",
  "                <input id=\"cfg-feishu-oauth-scope\" type=\"text\" placeholder=\"wiki:space:retrieve wiki:node:read docx:document:readonly\">\n",
  "              </div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-archive-enabled\">归档总开关</label>\n",
  "                <select id=\"cfg-archive-enabled\">\n",
  "                  <option value=\"1\">开启</option>\n",
  "                  <option value=\"0\">关闭</option>\n",
  "                </select>\n",
  "              </div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-case-archive-notify-enabled\">Case 归档推送</label>\n",
  "                <select id=\"cfg-case-archive-notify-enabled\">\n",
  "                  <option value=\"1\">开启</option>\n",
  "                  <option value=\"0\">关闭</option>\n",
  "                </select>\n",
  "              </div>\n",
  "              <div class=\"config-field full\">\n",
  "                <label for=\"cfg-agent-wake-names\">机器人唤醒名</label>\n",
  "                <input id=\"cfg-agent-wake-names\" type=\"text\" placeholder=\"例如：__FLOWBOT_AGENT_PRIMARY_WAKE_NAME__\">\n",
  "              </div>\n",
  "              <div class=\"config-section-title\">模型配置</div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-llm-enabled\">大模型兜底分类</label>\n",
  "                <select id=\"cfg-llm-enabled\">\n",
  "                  <option value=\"1\">开启</option>\n",
  "                  <option value=\"0\">关闭</option>\n",
  "                </select>\n",
  "              </div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-llm-url\">大模型 API URL</label>\n",
  "                <input id=\"cfg-llm-url\" type=\"text\" placeholder=\"https://dashscope.aliyuncs.com/compatible-mode/v1\">\n",
  "              </div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-llm-model\">大模型 Model</label>\n",
  "                <input id=\"cfg-llm-model\" type=\"text\" placeholder=\"qwen3.7-max\">\n",
  "              </div>\n",
  "              <div class=\"config-field full\">\n",
  "                <label for=\"cfg-llm-key\">大模型 API Key</label>\n",
  "                <input id=\"cfg-llm-key\" type=\"password\" placeholder=\"留空则保持当前已配置的 Key 不变\">\n",
  "              </div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-llm-timeout\">大模型超时（毫秒）</label>\n",
  "                <input id=\"cfg-llm-timeout\" type=\"number\" min=\"1000\" step=\"1000\">\n",
  "              </div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-llm-repair\">JSON 修复重试次数</label>\n",
  "                <input id=\"cfg-llm-repair\" type=\"number\" min=\"0\" max=\"5\" step=\"1\">\n",
  "              </div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-image-summary-enabled\">图片理解</label>\n",
  "                <select id=\"cfg-image-summary-enabled\">\n",
  "                  <option value=\"1\">开启</option>\n",
  "                  <option value=\"0\">关闭</option>\n",
  "                </select>\n",
  "              </div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-image-summary-model\">图片理解模型</label>\n",
  "                <input id=\"cfg-image-summary-model\" type=\"text\" placeholder=\"qwen-vl-plus\">\n",
  "              </div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-image-summary-timeout\">图片理解超时（毫秒）</label>\n",
  "                <input id=\"cfg-image-summary-timeout\" type=\"number\" min=\"1000\" step=\"1000\">\n",
  "              </div>\n",
  "              <div class=\"config-section-title\">语音转写</div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-transcribe-enabled\">语音转中文</label>\n",
  "                <select id=\"cfg-transcribe-enabled\">\n",
  "                  <option value=\"1\">开启</option>\n",
  "                  <option value=\"0\">关闭</option>\n",
  "                </select>\n",
  "              </div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-transcribe-timeout\">转写超时（毫秒）</label>\n",
  "                <input id=\"cfg-transcribe-timeout\" type=\"number\" min=\"1000\" step=\"1000\">\n",
  "              </div>\n",
  "              <div class=\"config-section-title\">数据存储</div>\n",
  "              <div class=\"config-field full\">\n",
  "                <label for=\"cfg-data-dir\">媒体和运行文件目录</label>\n",
  "                <input id=\"cfg-data-dir\" type=\"text\" placeholder=\"例如：/opt/yuebai-ai-platform/data/customer-bot-data\">\n",
  "                <div class=\"config-help\">消息、Case、任务和知识候选固定写 MySQL；这里主要放媒体附件、临时文件和本地运行文件。</div>\n",
  "              </div>\n",
  "              <div class=\"config-field full\">\n",
  "                <label for=\"cfg-mysql-url\">MySQL 连接地址</label>\n",
  "                <input id=\"cfg-mysql-url\" type=\"text\" placeholder=\"例如：mysql://flowbot_app@172.31.42.172:3306/flowbot_runtime\">\n",
  "                <div class=\"config-help\">格式：mysql://用户@主机:端口/库名。密码建议填下面，避免直接暴露在地址里。</div>\n",
  "              </div>\n",
  "              <div class=\"config-field full\">\n",
  "                <label for=\"cfg-mysql-password\">MySQL 密码（可选）</label>\n",
  "                <input id=\"cfg-mysql-password\" type=\"password\" autocomplete=\"new-password\" placeholder=\"留空则保持当前密码不变\">\n",
  "              </div>\n",
  "              <div class=\"config-section-title\">知识沉淀</div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-knowledge-harvest-enabled\">知识沉淀扫描</label>\n",
  "                <select id=\"cfg-knowledge-harvest-enabled\">\n",
  "                  <option value=\"1\">开启</option>\n",
  "                  <option value=\"0\">关闭</option>\n",
  "                </select>\n",
  "              </div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-knowledge-harvest-ready-age\">知识扫描等待（毫秒）</label>\n",
  "                <input id=\"cfg-knowledge-harvest-ready-age\" type=\"number\" min=\"0\" step=\"1000\">\n",
  "              </div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-knowledge-harvest-interval\">知识扫描间隔（毫秒）</label>\n",
  "                <input id=\"cfg-knowledge-harvest-interval\" type=\"number\" min=\"10000\" step=\"1000\">\n",
  "              </div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"cfg-knowledge-harvest-max\">单轮知识扫描上限</label>\n",
  "                <input id=\"cfg-knowledge-harvest-max\" type=\"number\" min=\"1\" max=\"20\" step=\"1\">\n",
  "              </div>\n",
  "              <div class=\"config-field full\">\n",
  "                <label for=\"cfg-knowledge-harvest-rooms\">知识沉淀群白名单</label>\n",
  "                <textarea id=\"cfg-knowledge-harvest-rooms\" placeholder=\"每行一个 room_id 或 chat_id；留空表示所有已接入群都参与知识沉淀\"></textarea>\n",
  "              </div>\n",
  "              <div class=\"config-section-title\">知识库问答</div>\n",
  "              <div class=\"config-field full\">\n",
  "                <label for=\"cfg-ragflow-chat-id\">RAGFlow 问答机器人</label>\n",
  "                <select id=\"cfg-ragflow-chat-id\">\n",
  "                  <option value=\"\">未选择，使用旧检索链路</option>\n",
  "                </select>\n",
  "                <div class=\"config-actions\" style=\"margin-top: 8px;\">\n",
  "                  <button class=\"action-btn\" id=\"config-ragflow-refresh\" type=\"button\">刷新机器人列表</button>\n",
  "                  <span class=\"muted\" id=\"config-ragflow-status\">未加载</span>\n",
  "                </div>\n",
  "              </div>\n",
  "            </div>\n",
  "            <div class=\"config-actions\">\n",
  "              <button class=\"action-btn\" id=\"config-test\" type=\"button\">测试模型连接</button>\n",
  "              <button class=\"action-btn primary\" id=\"config-save\" type=\"submit\">保存并应用</button>\n",
  "              <span class=\"muted\" id=\"config-flash\">配置载入中...</span>\n",
  "            </div>\n",
  "          </form>\n",
  "        </section>\n",
  "\n",
  "        <section class=\"panel\" data-dashboard-target=\"settingsLogin\">\n",
  "          <div class=\"dashboard-list-head\">\n",
  "            <h2>实例登录</h2>\n",
  "            <div class=\"dashboard-list-head-actions\">\n",
  "              <button class=\"table-action\" data-back-to-dashboard-list type=\"button\">返回列表</button>\n",
  "            </div>\n",
  "          </div>\n",
  "          <form class=\"config-form\" id=\"wecom-login-form\">\n",
  "            <div class=\"config-grid\">\n",
  "              <div class=\"config-field full\">\n",
  "                <label for=\"login-guid\">实例 GUID</label>\n",
  "                <input id=\"login-guid\" type=\"text\" placeholder=\"例如：49d07411-00f9-3baf-b5d4-4b34dc0ef0df\">\n",
  "              </div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"login-region-select\">地区预设</label>\n",
  "                <select id=\"login-region-select\"></select>\n",
  "              </div>\n",
  "              <div class=\"config-field\">\n",
  "                <label for=\"login-region\">地区代码</label>\n",
  "                <input id=\"login-region\" type=\"text\" placeholder=\"例如：370200\">\n",
  "              </div>\n",
  "              <div class=\"proxy-choice\">\n",
  "                <div class=\"proxy-choice-head\">\n",
  "                  <div class=\"proxy-choice-title\">代理设置</div>\n",
  "                </div>\n",
  "                <div class=\"proxy-choice-grid\">\n",
  "                  <div class=\"config-field full\">\n",
  "                    <label for=\"login-proxy\">代理地址</label>\n",
  "                    <input id=\"login-proxy\" type=\"text\" placeholder=\"例如：socks5://user:pass@ip:port\">\n",
  "                  </div>\n",
  "                </div>\n",
  "              </div>\n",
  "              <div class=\"config-field full\">\n",
  "                <label for=\"login-notify-url\">回调地址</label>\n",
  "                <input id=\"login-notify-url\" type=\"text\" placeholder=\"https://your-flowbot.example.com/flowbot/callback\" value=\"__FLOWBOT_DEFAULT_NOTIFY_URL_HTML__\">\n",
  "              </div>\n",
  "              <div class=\"config-field full\">\n",
  "                <label for=\"login-code\">登录验证码（可选）</label>\n",
  "                <input id=\"login-code\" type=\"text\" placeholder=\"只有扫码后提示要验证码时再填写\">\n",
  "              </div>\n",
  "            </div>\n",
  "            <div class=\"config-actions\">\n",
  "              <button class=\"action-btn primary\" id=\"login-start\" type=\"submit\">开始登录</button>\n",
  "              <button class=\"action-btn\" id=\"login-open-provider\" type=\"button\">获取代理</button>\n",
  "              <button class=\"action-btn\" id=\"login-set-notify\" type=\"button\">设置回调地址</button>\n",
  "              <button class=\"action-btn\" id=\"login-verify\" type=\"button\">提交验证码</button>\n",
  "              <span class=\"muted\" id=\"login-flash\">等待开始登录</span>\n",
  "            </div>\n",
  "          </form>\n",
  "          <div class=\"qr-login-preview\" style=\"margin-top: 12px;\">\n",
  "            <div class=\"qr-login-box\" id=\"login-qrcode-box\">\n",
  "              <div class=\"muted\">二维码会显示在这里</div>\n",
  "            </div>\n",
  "            <div class=\"login-meta-grid\" id=\"login-meta-grid\"></div>\n",
  "            <div class=\"config-status\" id=\"login-status\">\n",
  "              <strong>登录状态</strong>\n",
  "              <div class=\"muted\">还没有发起登录流程</div>\n",
  "            </div>\n",
  "          </div>\n",
  "        </section>\n",
  "\n",
  "        <section class=\"panel\">\n",
  "          <h2>当前进度与原因统计</h2>\n",
  "          <p class=\"hint\">这里把“收到回调 -> 标准化 -> 处理 -> 线程 -> Case”的流水线拆开看，同时汇总最近一批数据里最常见的卡点。</p>\n",
  "          <div class=\"mini-grid\" id=\"stage-list\"></div>\n",
  "          <div class=\"grid-2\" style=\"margin-top: 12px;\">\n",
  "            <div>\n",
  "              <p class=\"hint\">未成 Case 的主因</p>\n",
  "              <div class=\"breakdown\" id=\"processed-reasons\"></div>\n",
  "            </div>\n",
  "            <div>\n",
  "              <p class=\"hint\">消息类型分布</p>\n",
  "              <div class=\"breakdown\" id=\"message-types\"></div>\n",
  "            </div>\n",
  "          </div>\n",
  "        </section>\n",
  "\n",
  "        <section class=\"panel\">\n",
  "          <h2>过滤后的原始回调</h2>\n",
  "          <p class=\"hint\">这里只展示已经通过过滤的原始回调数据，不展示被拦掉的全量噪音。</p>\n",
  "          <div class=\"list\" id=\"accepted-callbacks\"></div>\n",
];
