"use strict";

module.exports = [
  "\n",
  "    function renderStageStats(items) {\n",
  "      const root = document.getElementById(\"stage-list\");\n",
  "      root.innerHTML = items.map((item) => `\n",
  "        <div class=\"mini-stat\">\n",
  "          <div class=\"label\">${escapeHtml(item.label)}</div>\n",
  "          <div class=\"value\">${escapeHtml(item.count)}</div>\n",
  "        </div>\n",
  "      `).join(\"\");\n",
  "    }\n",
  "\n",
  "    function bindPager(root, id, totalPages, rerender) {\n",
  "      const prev = root.querySelector(\"[data-page-action='prev']\");\n",
  "      const next = root.querySelector(\"[data-page-action='next']\");\n",
  "      if (prev) {\n",
  "        prev.addEventListener(\"click\", () => {\n",
  "          const current = listPageState.get(id) || 1;\n",
  "          listPageState.set(id, Math.max(1, current - 1));\n",
  "          rerender();\n",
  "        });\n",
  "      }\n",
  "      if (next) {\n",
  "        next.addEventListener(\"click\", () => {\n",
  "          const current = listPageState.get(id) || 1;\n",
  "          listPageState.set(id, Math.min(totalPages, current + 1));\n",
  "          rerender();\n",
  "        });\n",
  "      }\n",
  "    }\n",
  "\n",
  "    function hydrateNestedPagers(root) {\n",
  "      const containers = root.querySelectorAll(\"[data-nested-pager-id]\");\n",
  "      containers.forEach((container) => {\n",
  "        const pagerId = container.getAttribute(\"data-nested-pager-id\") || \"\";\n",
  "        const rerender = nestedPagerRegistry.get(pagerId);\n",
  "        if (!pagerId || !rerender) {\n",
  "          return;\n",
  "        }\n",
  "        const prev = container.querySelector(\"[data-page-action='prev']\");\n",
  "        const next = container.querySelector(\"[data-page-action='next']\");\n",
  "        const refresh = () => {\n",
  "          container.outerHTML = rerender();\n",
  "          const scope = root.closest(\".item\") || root;\n",
  "          hydrateLazyDetails(scope);\n",
  "          hydrateNestedPagers(scope);\n",
  "        };\n",
  "        if (prev) {\n",
  "          prev.addEventListener(\"click\", () => {\n",
  "            const current = listPageState.get(pagerId) || 1;\n",
  "            listPageState.set(pagerId, Math.max(1, current - 1));\n",
  "            refresh();\n",
  "          });\n",
  "        }\n",
  "        if (next) {\n",
  "          next.addEventListener(\"click\", () => {\n",
  "            const current = listPageState.get(pagerId) || 1;\n",
  "            listPageState.set(pagerId, current + 1);\n",
  "            refresh();\n",
  "          });\n",
  "        }\n",
  "      });\n",
  "    }\n",
  "\n",
  "    function renderList(id, items, renderer, emptyText, pageSize = 8) {\n",
  "      const root = document.getElementById(id);\n",
  "      if (!items.length) {\n",
  "        listPageState.set(id, 1);\n",
  "        root.innerHTML = '<div class=\"empty\">' + escapeHtml(emptyText) + '</div>';\n",
  "        return;\n",
  "      }\n",
  "      const totalPages = Math.max(1, Math.ceil(items.length / pageSize));\n",
  "      const currentPage = Math.min(Math.max(listPageState.get(id) || 1, 1), totalPages);\n",
  "      listPageState.set(id, currentPage);\n",
  "      const start = (currentPage - 1) * pageSize;\n",
  "      const pageItems = items.slice(start, start + pageSize);\n",
  "      root.innerHTML = `\n",
  "        <div class=\"list-items\">${pageItems.map(renderer).join(\"\")}</div>\n",
  "        <div class=\"pager\">\n",
  "          <div class=\"pager-info\">第 ${currentPage} / ${totalPages} 页，当前显示 ${pageItems.length} 条，共 ${items.length} 条</div>\n",
  "          <div class=\"pager-actions\">\n",
  "            <button type=\"button\" data-page-action=\"prev\" ${currentPage <= 1 ? \"disabled\" : \"\"}>上一页</button>\n",
  "            <button type=\"button\" data-page-action=\"next\" ${currentPage >= totalPages ? \"disabled\" : \"\"}>下一页</button>\n",
  "          </div>\n",
  "        </div>\n",
  "      `;\n",
  "      hydrateLazyDetails(root);\n",
  "      hydrateNestedPagers(root);\n",
  "      bindPager(root, id, totalPages, () => renderList(id, items, renderer, emptyText, pageSize));\n",
  "    }\n",
  "\n",
  "    function displayMessageText(item) {\n",
  "      const media = item?.normalized || item || {};\n",
  "      const content = String(media.content || item?.contentPreview || \"\").trim();\n",
  "      if (content) return content;\n",
  "      const transcriptText = String(media.transcriptText || media.transcript_text || \"\").trim();\n",
  "      if (transcriptText) return transcriptText;\n",
  "      const mediaKind = String(media.mediaKind || media.media_kind || \"\").trim();\n",
  "      if (mediaKind === \"audio\" || Number(media.msgType || item?.msgType || 0) === 6) return \"[语音]\";\n",
  "      if (mediaKind === \"image\" || Number(media.msgType || item?.msgType || 0) === 5) return \"[图片]\";\n",
  "      if (mediaKind === \"video\" || Number(media.msgType || item?.msgType || 0) === 7) return \"[视频]\";\n",
  "      if (mediaKind === \"file\" || Number(media.msgType || item?.msgType || 0) === 8) return \"[文件]\";\n",
  "      return \"(空内容)\";\n",
  "    }\n",
  "\n",
  "    function renderAcceptedItem(item) {\n",
  "      const titleText = displayMessageText(item);\n",
  "      return `\n",
  "        <article class=\"item\">\n",
  "          <div class=\"item-head\">\n",
  "            <div>\n",
  "              <div class=\"item-title\">${escapeHtml(item.senderName || item.senderId || \"unknown\")} · ${escapeHtml(titleText)}</div>\n",
  "              <div class=\"muted\">traceId: ${escapeHtml(item.traceId)} · room: ${escapeHtml(item.roomId)} · seq: ${escapeHtml(item.seq)} · 类型: ${escapeHtml(item.msgTypeName)} · 时间: ${escapeHtml(item.sendTimeIso || item.receivedAt)}</div>\n",
  "            </div>\n",
  "            <span class=\"badge ok\">已通过过滤</span>\n",
  "          </div>\n",
  "          ${renderMediaPreview(item)}\n",
  "          ${renderJsonDetails(\"查看原始数据\", item.jsonBody || item)}\n",
  "        </article>\n",
  "      `;\n",
  "    }\n",
  "\n",
  "    function renderNormalizedItem(item) {\n",
  "      const mediaStatus = item.mediaDownloadStatus ? (\" · 媒体: \" + item.mediaDownloadStatus) : \"\";\n",
  "      const titleText = displayMessageText(item);\n",
  "      return `\n",
  "        <article class=\"item\">\n",
  "          <div class=\"item-head\">\n",
  "            <div>\n",
  "              <div class=\"item-title\">${escapeHtml(item.senderName || item.senderId || \"unknown\")} · ${escapeHtml(titleText)}</div>\n",
  "              <div class=\"muted\">traceId: ${escapeHtml(item.traceId)} · type: ${escapeHtml(item.msgTypeName)} · contentType: ${escapeHtml(item.contentType)}${escapeHtml(mediaStatus)} · 时间: ${escapeHtml(item.sendTimeIso || item.receivedAt)}</div>\n",
  "            </div>\n",
  "            <span class=\"badge warn\">已标准化</span>\n",
  "          </div>\n",
  "          ${renderMediaPreview(item)}\n",
  "          ${renderJsonDetails(\"查看标准化结构\", item)}\n",
  "        </article>\n",
  "      `;\n",
  "    }\n",
  "\n",
  "    function renderPendingItem(item) {\n",
  "      const normalized = item.normalized || item;\n",
  "      const badgeClass = item.status === \"processing\" ? \"warn\" : \"danger\";\n",
  "      const detailParts = [];\n",
  "      if (item.attempts) detailParts.push(\"尝试次数: \" + item.attempts);\n",
  "      if (item.caseId) detailParts.push(\"case: \" + item.caseId);\n",
  "      if (item.threadType) detailParts.push(\"线程: \" + (THREAD_TYPE_LABELS[item.threadType] || item.threadType));\n",
  "      if (item.messageRole) detailParts.push(\"角色: \" + (MESSAGE_ROLE_LABELS[item.messageRole] || item.messageRole));\n",
  "      if (item.batchAction) detailParts.push(\"动作: \" + (BATCH_ACTION_LABELS[item.batchAction] || item.batchAction));\n",
  "      if (item.batchReason) detailParts.push(\"结果: \" + item.batchReason);\n",
  "      if (item.lastError) detailParts.push(\"错误: \" + item.lastError);\n",
  "      return `\n",
  "        <article class=\"item\">\n",
  "          <div class=\"item-head\">\n",
  "            <div>\n",
  "              <div class=\"item-title\">${escapeHtml(normalized.senderName || normalized.senderId || item.senderName || \"unknown\")} · ${escapeHtml(normalized.content || item.contentPreview || \"(空内容)\")}</div>\n",
  "              <div class=\"muted\">traceId: ${escapeHtml(item.traceId)} · 状态: ${escapeHtml(item.statusLabel || item.status || \"待处理\")} · 时间: ${escapeHtml(normalized.sendTimeIso || item.sendTimeIso || item.receivedAt || \"\")} · ${escapeHtml(detailParts.join(\" · \"))}</div>\n",
  "            </div>\n",
  "            <span class=\"badge ${badgeClass}\">${escapeHtml(item.statusLabel || item.status || \"待处理\")}</span>\n",
  "          </div>\n",
  "          ${renderMediaPreview(normalized)}\n",
  "          ${renderJsonDetails(\"查看消息池记录\", item)}\n",
  "        </article>\n",
  "      `;\n",
  "    }\n",
  "\n",
  "    function renderProcessedItem(item) {\n",
  "      const isReview = item.batchAction === \"need_review\";\n",
  "      const isIgnored = item.batchAction === \"ignore\";\n",
  "      const isCaseActivity = item.batchAction === \"append_case_activity\" && item.caseInfo?.case_id;\n",
  "      const badgeClass = isReview ? \"warn\" : (item.caseInfo?.case_id ? \"ok\" : item.archived ? \"warn\" : \"danger\");\n",
  "      const badgeText = isReview\n",
  "        ? \"待复核\"\n",
  "        : isCaseActivity\n",
  "          ? \"已追加活动\"\n",
  "          : item.caseInfo?.case_id\n",
  "            ? \"已进入 Case\"\n",
  "            : isIgnored\n",
  "              ? \"已忽略\"\n",
  "              : item.archived\n",
  "                ? \"已处理未成 Case\"\n",
  "                : \"已跳过\";\n",
  "      const detailParts = [];\n",
  "      if (item.category) detailParts.push(\"分类: \" + (CATEGORY_LABELS[item.category] || item.category));\n",
  "      if (item.priority) detailParts.push(\"优先级: \" + item.priority);\n",
  "      if (item.threadType) detailParts.push(\"线程: \" + (THREAD_TYPE_LABELS[item.threadType] || item.threadType));\n",
  "      if (item.messageRole) detailParts.push(\"角色: \" + (MESSAGE_ROLE_LABELS[item.messageRole] || item.messageRole));\n",
  "      if (item.batchAction) detailParts.push(\"动作: \" + (BATCH_ACTION_LABELS[item.batchAction] || item.batchAction));\n",
  "      if (item.summary) detailParts.push(\"摘要: \" + item.summary);\n",
  "      if (item.classifierSource) detailParts.push(\"判定来源: \" + item.classifierSource);\n",
  "      if (item.llmRepaired) detailParts.push(\"JSON修复: 已重试\");\n",
  "      if (item.thread?.thread_id) detailParts.push(\"thread: \" + item.thread.thread_id);\n",
  "      if (item.caseInfo?.case_id) detailParts.push(\"case: \" + item.caseInfo.case_id);\n",
  "      return `\n",
  "        <article class=\"item\">\n",
  "          <div class=\"item-head\">\n",
  "            <div>\n",
  "              <div class=\"item-title\">${escapeHtml(item.senderName || \"unknown\")} · ${escapeHtml(item.contentPreview || \"\")}</div>\n",
  "              <div class=\"muted\">${escapeHtml(item.reasonLabel)} · ${escapeHtml(detailParts.join(\" · \"))}</div>\n",
  "            </div>\n",
  "            <span class=\"badge ${badgeClass}\">${escapeHtml(badgeText)}</span>\n",
  "          </div>\n",
  "          ${renderMediaPreview(item)}\n",
  "          ${renderJsonDetails(\"查看处理明细\", item)}\n",
  "        </article>\n",
  "      `;\n",
  "    }\n",
  "\n",
  "    function renderCaseItem(item) {\n",
  "      return `\n",
  "        <article class=\"item\">\n",
  "          <div class=\"item-head\">\n",
  "            <div>\n",
  "              <div class=\"item-title\">${escapeHtml(item.summary || item.case_id)}</div>\n",
  "              <div class=\"muted\">caseId: ${escapeHtml(item.case_id)} · 状态: ${escapeHtml(CASE_STATUS_LABELS[item.status] || item.status || \"-\")} · 优先级: ${escapeHtml(item.priority)} · 消息数: ${escapeHtml(item.message_count)} · 活动数: ${escapeHtml(item.activity_count || item.caseDetail?.activities?.length || 0)} · 更新: ${escapeHtml(item.updated_at)}</div>\n",
  "            </div>\n",
  "            <span class=\"badge ok\">${escapeHtml(CATEGORY_LABELS[item.category] || item.category || \"Case\")}</span>\n",
  "          </div>\n",
  "          <div class=\"muted\">参与人：${escapeHtml((item.participants || []).join(\"、\") || \"暂无\")}</div>\n",
  "          ${renderCaseActivities(item)}\n",
  "          ${renderArchivedMessages(item)}\n",
  "          ${renderJsonDetails(\"查看 Case JSON\", item)}\n",
  "        </article>\n",
  "      `;\n",
  "    }\n",
  "\n",
  "    function renderNonCaseItem(item) {\n",
  "      const reason = item.reasonLabel || item.reason || item.status || \"未进入 case\";\n",
  "      const detailParts = [];\n",
  "      if (item.threadType) detailParts.push(\"线程: \" + (THREAD_TYPE_LABELS[item.threadType] || item.threadType));\n",
  "      if (item.messageRole) detailParts.push(\"角色: \" + (MESSAGE_ROLE_LABELS[item.messageRole] || item.messageRole));\n",
  "      if (item.batchAction) detailParts.push(\"动作: \" + (BATCH_ACTION_LABELS[item.batchAction] || item.batchAction));\n",
  "      return `\n",
  "        <article class=\"item\">\n",
  "          <div class=\"item-head\">\n",
  "            <div>\n",
  "              <div class=\"item-title\">${escapeHtml(item.summary || item.contentPreview || item.thread_id || \"未成 Case 项\")}</div>\n",
  "              <div class=\"muted\">${escapeHtml(reason)}${detailParts.length ? \" · \" + escapeHtml(detailParts.join(\" · \")) : \"\"}</div>\n",
  "          </div>\n",
  "          <span class=\"badge danger\">未成 Case</span>\n",
  "          </div>\n",
  "          ${renderJsonDetails(\"查看详情\", item)}\n",
  "        </article>\n",
  "      `;\n",
  "    }\n",
  "\n",
  "    function renderThreadItem(item) {\n",
  "      return `\n",
  "        <article class=\"item\">\n",
  "          <div class=\"item-head\">\n",
  "            <div>\n",
  "              <div class=\"item-title\">${escapeHtml(item.summary || item.thread_id)}</div>\n",
  "              <div class=\"muted\">threadId: ${escapeHtml(item.thread_id)} · 状态: ${escapeHtml(item.status)} · 消息数: ${escapeHtml(item.message_count)} · 更新: ${escapeHtml(item.updated_at)}</div>\n",
  "            </div>\n",
  "            <span class=\"badge warn\">${escapeHtml(item.status || \"candidate\")}</span>\n",
  "          </div>\n",
  "          ${renderJsonDetails(\"查看 Thread 摘要\", item)}\n",
  "        </article>\n",
  "      `;\n",
  "    }\n",
  "\n",
  "    function renderKnowledgeCandidateItem(item) {\n",
  "      const badgeClass = item.status === \"published\" ? \"ok\" : (item.status === \"rejected\" ? \"danger\" : \"warn\");\n",
  "      const badgeText = item.status === \"published\" ? \"已入库\" : (item.status === \"rejected\" ? \"已拒绝\" : \"待审核\");\n",
  "      const tags = Array.isArray(item.tags) ? item.tags.join(\"、\") : \"\";\n",
  "      const tagsText = Array.isArray(item.tags) ? item.tags.join(\", \") : \"\";\n",
  "      const relatedKnowledge = Array.isArray(item.relatedKnowledge) ? item.relatedKnowledge : [];\n",
  "      const relatedHtml = relatedKnowledge.length\n",
  "        ? `\n",
  "          <details class=\"json-details\" style=\"margin-top:12px;\">\n",
  "            <summary>查看模型参考的已有知识（${relatedKnowledge.length}）</summary>\n",
  "            <div class=\"message-timeline\" style=\"margin-top:12px;\">\n",
  "              ${relatedKnowledge.map((doc) => `\n",
  "                <div class=\"timeline-item\">\n",
  "                  <div class=\"timeline-meta\">${escapeHtml(doc.source || \"-\")} · score: ${escapeHtml(doc.score ?? \"-\")} · ${escapeHtml(doc.fileName || doc.id || \"\")}</div>\n",
  "                  <div class=\"timeline-text\">${escapeHtml(doc.title || \"未命名知识\")}</div>\n",
  "                  <div class=\"timeline-text\">${escapeHtml(doc.snippet || \"\")}</div>\n",
  "                </div>\n",
  "              `).join(\"\")}\n",
  "            </div>\n",
  "          </details>\n",
  "        `\n",
  "        : \"\";\n",
  "      const actions = item.status === \"pending_review\"\n",
  "        ? `\n",
  "          <div class=\"knowledge-edit-form\" data-knowledge-form=\"${escapeHtml(item.candidateId)}\">\n",
  "            <div class=\"knowledge-edit-grid\">\n",
  "              <div class=\"knowledge-edit-field full\">\n",
  "                <label>标题</label>\n",
  "                <input data-knowledge-field=\"title\" type=\"text\" value=\"${escapeHtml(item.title || \"\")}\">\n",
  "              </div>\n",
  "              <div class=\"knowledge-edit-field\">\n",
  "                <label>适用范围</label>\n",
  "                <input data-knowledge-field=\"scope\" type=\"text\" value=\"${escapeHtml(item.scope || \"\")}\">\n",
  "              </div>\n",
  "              <div class=\"knowledge-edit-field\">\n",
  "                <label>标签</label>\n",
  "                <input data-knowledge-field=\"tags\" type=\"text\" value=\"${escapeHtml(tagsText)}\">\n",
  "              </div>\n",
  "              <div class=\"knowledge-edit-field full\">\n",
  "                <label>问题或场景</label>\n",
  "                <textarea data-knowledge-field=\"problem\">${escapeHtml(item.problem || \"\")}</textarea>\n",
  "              </div>\n",
  "              <div class=\"knowledge-edit-field full\">\n",
  "                <label>处理办法</label>\n",
  "                <textarea data-knowledge-field=\"solution\">${escapeHtml(item.solution || \"\")}</textarea>\n",
  "              </div>\n",
  "              <div class=\"knowledge-edit-field full\">\n",
  "                <label>判断依据</label>\n",
  "                <textarea data-knowledge-field=\"reason\">${escapeHtml(item.reason || \"\")}</textarea>\n",
  "              </div>\n",
  "              <div class=\"knowledge-edit-field\">\n",
  "                <label>审核人</label>\n",
  "                <input data-knowledge-field=\"reviewer\" type=\"text\" value=\"${escapeHtml(item.reviewer || \"\")}\">\n",
  "              </div>\n",
  "              <div class=\"knowledge-edit-field\">\n",
  "                <label>审核备注</label>\n",
  "                <input data-knowledge-field=\"reviewNote\" type=\"text\" value=\"${escapeHtml(item.reviewNote || \"\")}\">\n",
  "              </div>\n",
  "              <div class=\"knowledge-edit-field full\">\n",
  "                <label>更新到已有知识</label>\n",
  "                <select data-knowledge-field=\"targetKnowledgeFileName\">\n",
  "                  <option value=\"\">选择一个本地知识文档</option>\n",
  "                  ${relatedKnowledge.filter((doc) => doc.source === \"local\" && doc.fileName).map((doc) => `\n",
  "                    <option value=\"${escapeHtml(doc.fileName)}\">${escapeHtml((doc.title || doc.fileName) + \" · \" + doc.fileName)}</option>\n",
  "                  `).join(\"\")}\n",
  "                </select>\n",
  "              </div>\n",
  "            </div>\n",
  "          </div>\n",
  "          <div class=\"config-actions\" style=\"margin-top: 12px;\">\n",
  "            <button class=\"action-btn\" data-knowledge-action=\"save\" data-candidate-id=\"${escapeHtml(item.candidateId)}\" type=\"button\">保存修改</button>\n",
  "            <button class=\"action-btn\" data-knowledge-action=\"update_existing\" data-candidate-id=\"${escapeHtml(item.candidateId)}\" type=\"button\">更新已有知识</button>\n",
  "            <button class=\"action-btn primary\" data-knowledge-action=\"approve\" data-candidate-id=\"${escapeHtml(item.candidateId)}\" type=\"button\">入知识库</button>\n",
  "            <button class=\"action-btn\" data-knowledge-action=\"reject\" data-candidate-id=\"${escapeHtml(item.candidateId)}\" type=\"button\">拒绝</button>\n",
  "          </div>\n",
  "        `\n",
  "        : \"\";\n",
  "      return `\n",
  "        <article class=\"item\">\n",
  "          <div class=\"item-head\">\n",
  "            <div>\n",
  "              <div class=\"item-title\">${escapeHtml(item.title || item.candidateId || \"知识候选\")}</div>\n",
  "              <div class=\"muted\">candidateId: ${escapeHtml(item.candidateId)} · room: ${escapeHtml(item.roomName || item.roomId || \"-\")} · 置信度: ${escapeHtml(item.confidence ?? \"-\")} · 标签: ${escapeHtml(tags || \"暂无\")}</div>\n",
  "            </div>\n",
  "            <span class=\"badge ${badgeClass}\">${escapeHtml(badgeText)}</span>\n",
  "          </div>\n",
  "          <div class=\"muted\" style=\"margin-top: 10px;\">场景：${escapeHtml(item.scope || \"待补充\")}</div>\n",
  "          <div class=\"muted\" style=\"margin-top: 6px;\">模型建议：${escapeHtml(item.knowledgeStatus || \"uncertain\")} · ${escapeHtml(item.recommendation || \"needs_human_review\")}</div>\n",
  "          ${item.existingKnowledgeSummary ? `<div class=\"muted\" style=\"margin-top: 6px;\">已有知识：${escapeHtml(item.existingKnowledgeSummary)}</div>` : \"\"}\n",
  "          ${item.delta ? `<div class=\"muted\" style=\"margin-top: 6px;\">新增/变化：${escapeHtml(item.delta)}</div>` : \"\"}\n",
  "          <div style=\"margin-top: 10px;\">${escapeHtml(item.problem || \"\")}</div>\n",
  "          <div style=\"margin-top: 8px;\">${escapeHtml(item.solution || \"\")}</div>\n",
  "          ${relatedHtml}\n",
  "          ${actions}\n",
  "          ${renderJsonDetails(\"查看知识候选详情\", item)}\n",
  "        </article>\n",
  "      `;\n",
  "    }\n",
  "\n",
  "    function renderKnowledgeKpis(progress) {\n",
  "      const root = document.getElementById(\"knowledge-kpis\");\n",
  "      if (!root) {\n",
  "        return;\n",
  "      }\n",
  "      const items = [\n",
  "        { label: \"待审核\", value: progress.knowledgePendingReviewTotal || 0 },\n",
  "        { label: \"可能已有\", value: progress.knowledgeAlreadyExistsTotal || 0 },\n",
  "        { label: \"建议更新\", value: progress.knowledgeUpdateExistingTotal || 0 },\n",
  "        { label: \"已发布\", value: progress.knowledgePublishedTotal || 0 },\n",
  "        { label: \"已拒绝\", value: progress.knowledgeRejectedTotal || 0 },\n",
  "        { label: \"判定失败\", value: progress.knowledgeFailedTotal || 0 },\n",
  "      ];\n",
  "      root.innerHTML = items.map((item) => `\n",
  "        <div class=\"knowledge-kpi\">\n",
  "          <div class=\"label\">${escapeHtml(item.label)}</div>\n",
  "          <div class=\"value\">${escapeHtml(item.value)}</div>\n",
  "        </div>\n",
  "      `).join(\"\");\n",
  "    }\n",
  "\n",
  "    function openKnowledgeGovernance() {\n",
  "      try {\n",
  "        const topWindow = window.top || window;\n",
  "        const room = lastRooms.find((item) => String(item.id || \"\") === String(selectedRoomId || \"\"));\n",
  "        topWindow.sessionStorage.setItem(\"yuebai-flowbot-knowledge-room-filter\", JSON.stringify({\n",
  "          roomId: selectedRoomId || \"\",\n",
  "          roomName: roomDisplayName(room),\n",
  "          status: \"needs_review\",\n",
  "        }));\n",
  "        topWindow.localStorage.setItem(\"yuebai-knowledge-workbench-tab\", \"governance\");\n",
  "        topWindow.location.hash = \"#/knowledge\";\n",
  "      } catch {\n",
  "        window.location.href = \"/ragflow-workbench-bridge.html?tab=governance&roomId=\" + encodeURIComponent(selectedRoomId || \"\");\n",
  "      }\n",
  "    }\n",
  "\n",
  "    function collectKnowledgeCandidatePatch(candidateId) {\n",
  "      const form = document.querySelector('[data-knowledge-form=\"' + cssEscape(candidateId) + '\"]');\n",
  "      if (!form) {\n",
  "        return {};\n",
  "      }\n",
  "      const patch = {};\n",
  "      form.querySelectorAll(\"[data-knowledge-field]\").forEach((field) => {\n",
  "        patch[field.getAttribute(\"data-knowledge-field\")] = field.value;\n",
  "      });\n",
  "      return patch;\n",
  "    }\n",
  "\n",
  "    async function performKnowledgeCandidateAction(candidateId, action) {\n",
  "      const patch = collectKnowledgeCandidatePatch(candidateId);\n",
  "      if (action === \"update_existing\" && !String(patch.targetKnowledgeFileName || patch.targetKnowledgeId || \"\").trim()) {\n",
  "        throw new Error(\"请先选择要更新的本地知识文档\");\n",
  "      }\n",
  "      const response = await fetch(\"/flowbot/agent/knowledge-candidates/action\", {\n",
  "        method: \"POST\",\n",
  "        headers: { \"Content-Type\": \"application/json\" },\n",
  "        body: JSON.stringify({ candidateId, action, ...patch }),\n",
  "      });\n",
  "      const data = await response.json();\n",
  "      if (!data.ok) {\n",
  "        throw new Error(data.error || \"knowledge_candidate_action_failed\");\n",
  "      }\n",
  "      await load(true);\n",
  "    }\n",
  "\n",
  "    function bindKnowledgeCandidateActions(root) {\n",
  "      root.querySelectorAll(\"[data-knowledge-action]\").forEach((button) => {\n",
  "        if (button.dataset.bound === \"1\") {\n",
  "          return;\n",
  "        }\n",
  "        button.dataset.bound = \"1\";\n",
  "        button.addEventListener(\"click\", async () => {\n",
  "          const action = button.getAttribute(\"data-knowledge-action\") || \"\";\n",
  "          const candidateId = button.getAttribute(\"data-candidate-id\") || \"\";\n",
  "          if (!candidateId || !action) {\n",
  "            return;\n",
  "          }\n",
  "          if (action === \"reject\" && !confirm(\"确认拒绝这个知识候选吗？\")) {\n",
  "            return;\n",
  "          }\n",
  "          if ((action === \"approve\" || action === \"publish\") && !confirm(\"确认按当前编辑内容入知识库吗？\")) {\n",
  "            return;\n",
  "          }\n",
  "          if (action === \"update_existing\" && !confirm(\"确认把当前编辑内容追加到选中的已有知识吗？\")) {\n",
  "            return;\n",
  "          }\n",
  "          button.disabled = true;\n",
  "          try {\n",
  "            await performKnowledgeCandidateAction(candidateId, action);\n",
  "          } catch (error) {\n",
  "            alert(\"知识候选操作失败：\" + String(error?.message || error));\n",
  "          } finally {\n",
  "            button.disabled = false;\n",
  "          }\n",
  "        });\n",
  "      });\n",
  "    }\n",
  "\n",
  "    function setupDashboardTabs() {\n",
  "      const groups = {\n",
  "        overview: document.querySelector('[data-dashboard-group=\"overview\"]'),\n",
  "        settingsSystem: document.querySelector('[data-dashboard-group=\"settings-system\"]'),\n",
  "        settingsLogin: document.querySelector('[data-dashboard-group=\"settings-login\"]'),\n",
  "        messages: document.querySelector('[data-dashboard-group=\"messages\"]'),\n",
  "        cases: document.querySelector('[data-dashboard-group=\"cases\"]'),\n",
  "      };\n",
  "      const stats = document.getElementById(\"stats\");\n",
  "      if (groups.overview && stats) {\n",
  "        groups.overview.appendChild(stats);\n",
  "      }\n",
  "      const sectionByTitle = {\n",
  "        \"过滤规则\": \"settingsSystem\",\n",
  "        \"当前进度与原因统计\": \"overview\",\n",
  "        \"系统配置\": \"settingsSystem\",\n",
  "        \"上游实例登录\": \"settingsLogin\",\n",
  "        \"过滤后的原始回调\": \"messages\",\n",
  "        \"标准化后的消息\": \"messages\",\n",
  "        \"待批处理消息\": \"messages\",\n",
  "        \"已扫描并处理\": \"messages\",\n",
  "        \"已归纳为 Case\": \"cases\",\n",
  "        \"未归纳成 Case 的数据\": \"cases\",\n",
  "        \"候选 Thread 与当前进度\": \"cases\",\n",
  "        \"过滤拦截摘要\": \"cases\",\n",
  "        \"知识矫正审核\": \"overview\",\n",
  "      };\n",
  "      document.querySelectorAll(\"#legacy-dashboard-layout .panel\").forEach((panel) => {\n",
  "        const explicitGroupId = panel.getAttribute(\"data-dashboard-target\") || \"\";\n",
  "        const title = panel.querySelector(\"h2\")?.textContent?.trim() || \"\";\n",
  "        const groupId = explicitGroupId || sectionByTitle[title] || \"overview\";\n",
  "        groups[groupId]?.appendChild(panel);\n",
  "      });\n",
  "      document.getElementById(\"legacy-dashboard-layout\")?.remove();\n",
  "      document.querySelectorAll(\"[data-dashboard-tab]\").forEach((button) => {\n",
  "        button.addEventListener(\"click\", () => {\n",
  "          const key = button.getAttribute(\"data-dashboard-tab\") || \"overview\";\n",
  "          document.querySelectorAll(\"[data-dashboard-tab]\").forEach((item) => {\n",
  "            item.classList.toggle(\"active\", item === button);\n",
  "          });\n",
  "          document.querySelectorAll(\"[data-dashboard-pane]\").forEach((pane) => {\n",
  "            pane.classList.toggle(\"active\", pane.getAttribute(\"data-dashboard-pane\") === key);\n",
  "          });\n",
  "        });\n",
  "      });\n",
  "    }\n",
  "\n",
  "    async function load(force = false) {\n",
  "      if (isLoading) {\n",
  "        return;\n",
  "      }\n",
  "      if (!force && (hasOpenDetails() || document.hidden)) {\n",
  "        updateRefreshStatus();\n",
  "        return;\n",
  "      }\n",
  "      isLoading = true;\n",
  "      try {\n",
  "        const response = await fetch(buildEndpoint(), { cache: \"no-store\" });\n",
  "        const data = await response.json();\n",
  "        document.getElementById(\"meta-now\").textContent = \"最近刷新: \" + new Date(data.generatedAt).toLocaleString();\n",
  "        document.getElementById(\"meta-limit\").textContent = LIMIT;\n",
  "        const metaBatch = document.getElementById(\"meta-batch\");\n",
  "        if (metaBatch) {\n",
  "          metaBatch.textContent = \"批处理：待处理 \" + (data.progress.pendingTotal || 0) + \" / 处理中 \" + (data.progress.processingTotal || 0);\n",
  "        }\n",
  "        currentWecomGuid = String(data.filters.currentWecomGuid || currentWecomGuid || \"\");\n",
  "        if (dashboardView === \"list\") {\n",
  "          lastRooms = (Array.isArray(data.filters.availableRooms) ? data.filters.availableRooms : []).map((room) => {\n",
  "            const name = roomNameCache.get(String(room.id || \"\"));\n",
  "            return name ? { ...room, name } : room;\n",
  "          });\n",
  "          lastScope = data.scope || {};\n",
  "          renderDashboardList(lastRooms);\n",
  "          enrichDashboardRoomNames(lastRooms).catch(() => {});\n",
  "          updateRefreshStatus();\n",
  "          return;\n",
  "        }\n",
  "        renderRoomSelector(data.filters.availableRooms, data.scope);\n",
  "        renderRoomList(data.filters.availableRooms, data.scope);\n",
  "        enrichDashboardRoomNames(lastRooms).catch(() => {});\n",
  "        renderStats(data.progress, data.scope, data.agentOverview, data.needsAttention, data.dailySummary);\n",
  "        renderStageStats(data.breakdowns.stages);\n",
  "        renderBreakdown(\"processed-reasons\", data.breakdowns.processedReasons, \"当前没有处理结果。\");\n",
  "        renderBreakdown(\"message-types\", data.breakdowns.messageTypes, \"当前没有消息类型统计。\");\n",
  "        renderBreakdown(\"ignored-reasons\", data.breakdowns.ignoredReasons, \"当前没有过滤拦截记录。\");\n",
  "        setChips(\"rule-rooms\", data.filters.detectedRoomIds || []);\n",
  "        setChips(\"rule-notify\", data.filters.notifyTypes.map(String));\n",
  "        setChips(\"rule-msg-types\", data.filters.supportedMsgTypes.map((item) => item.name));\n",
  "        setChips(\"rule-archive\", [\n",
  "          data.filters.archiveEnabled ? \"归档已开启\" : \"归档已关闭\",\n",
  "          (data.filters.archiveMode || \"unknown\") + \" · \"\n",
  "            + (data.filters.batchModeEnabled ? (\"批处理已开启（每 \" + data.filters.batchScanIntervalSeconds + \" 秒扫描）\") : \"批处理未开启\"),\n",
  "          \"待处理至少停留 \" + data.filters.batchReadyAgeSeconds + \" 秒\",\n",
  "          \"单群单轮最多 \" + data.filters.batchMaxPendingPerRoom + \" 条\",\n",
  "          data.filters.transcriptionEnabled ? (\"语音转写已开启（\" + data.filters.transcriptionModel + \"）\") : \"语音转写未开启\",\n",
  "          data.filters.llmClassifyEnabled ? (\"大模型兜底已开启（\" + data.filters.llmModel + \"）\") : \"大模型兜底未开启\",\n",
  "          data.filters.knowledgeHarvestEnabled\n",
  "            ? (\"知识沉淀已开启（每 \" + data.filters.knowledgeHarvestScanIntervalSeconds + \" 秒扫描，等待 \" + data.filters.knowledgeHarvestReadyAgeSeconds + \" 秒）\")\n",
  "            : \"知识沉淀未开启\",\n",
  "          (data.filters.knowledgeHarvestRoomIds || []).length\n",
  "            ? (\"知识沉淀白名单：\" + data.filters.knowledgeHarvestRoomIds.join(\"，\"))\n",
  "            : \"知识沉淀群：全部已接入群\",\n",
  "        ]);\n",
  "        renderList(\"accepted-callbacks\", data.latest.callbacks, renderAcceptedItem, \"当前没有过滤通过的回调。\", 6);\n",
  "        renderList(\"normalized-list\", data.latest.normalized, renderNormalizedItem, \"当前还没有标准化消息。\", 6);\n",
  "        renderList(\"pending-list\", [...(data.latest.processing || []), ...(data.latest.pending || [])], renderPendingItem, \"当前没有待批处理消息。\", 6);\n",
  "        renderList(\"processed-list\", data.latest.processed, renderProcessedItem, \"当前没有进入处理阶段的数据。\", 6);\n",
  "        renderList(\"case-list\", data.latest.cases, renderCaseItem, \"当前还没有正式 Case。\", 5);\n",
  "        renderList(\"non-case-list\", data.latest.nonCase, renderNonCaseItem, \"当前没有未成 Case 的数据。\", 6);\n",
  "        renderList(\"thread-list\", data.latest.candidateThreads, renderThreadItem, \"当前没有候选 Thread。\", 5);\n",
  "        renderKnowledgeKpis(data.progress || {});\n",
  "        updateRefreshStatus();\n",
  "      } finally {\n",
  "        isLoading = false;\n",
  "      }\n",
  "    }\n",
  "\n",
  "    if (refreshNowButton) {\n",
  "      refreshNowButton.addEventListener(\"click\", () => {\n",
  "        load(true).catch((error) => {\n",
  "          document.body.innerHTML = '<div class=\"wrap\"><div class=\"panel\"><h2>加载失败</h2><pre>' + escapeHtml(String(error?.stack || error)) + '</pre></div></div>';\n",
  "        });\n",
  "      });\n",
  "    }\n",
  "    if (dashboardDetailRefreshButton) {\n",
  "      dashboardDetailRefreshButton.addEventListener(\"click\", async () => {\n",
  "        const originalText = dashboardDetailRefreshButton.textContent;\n",
  "        dashboardDetailRefreshButton.disabled = true;\n",
  "        dashboardDetailRefreshButton.textContent = \"刷新中...\";\n",
  "        try {\n",
  "          await load(true);\n",
  "        } catch (error) {\n",
  "          alert(\"刷新当前群失败：\" + String(error?.message || error));\n",
  "        } finally {\n",
  "          dashboardDetailRefreshButton.disabled = false;\n",
  "          dashboardDetailRefreshButton.textContent = originalText || \"刷新当前群\";\n",
  "        }\n",
  "      });\n",
  "    }\n",
  "    window.addEventListener(\"message\", async (event) => {\n",
  "      if (event.origin !== window.location.origin) return;\n",
  "      if (event.data?.type !== \"yuebai-module-refresh\") return;\n",
  "      const requestId = event.data.requestId || \"\";\n",
  "      try {\n",
  "        await load(true);\n",
  "        event.source?.postMessage({ type: \"yuebai-module-refresh-done\", requestId, ok: true }, event.origin);\n",
  "      } catch (error) {\n",
  "        event.source?.postMessage({ type: \"yuebai-module-refresh-done\", requestId, ok: false, error: String(error?.message || error) }, event.origin);\n",
  "      }\n",
  "    });\n",
  "    if (processPendingButton) {\n",
  "      processPendingButton.addEventListener(\"click\", async () => {\n",
  "        processPendingButton.disabled = true;\n",
  "        try {\n",
  "          const response = await fetch(\"/flowbot/process-pending\", {\n",
  "            method: \"POST\",\n",
  "            headers: {\n",
  "              \"Content-Type\": \"application/json\",\n",
  "            },\n",
  "            body: \"{}\",\n",
  "          });\n",
  "          const data = await response.json();\n",
  "          if (!data.ok) {\n",
  "            throw new Error(data.error || \"process_pending_failed\");\n",
  "          }\n",
  "          await load(true);\n",
  "        } catch (error) {\n",
  "          document.body.insertAdjacentHTML(\"beforeend\", \"\");\n",
  "          alert(\"批处理触发失败：\" + String(error?.message || error));\n",
  "        } finally {\n",
  "          processPendingButton.disabled = false;\n",
  "        }\n",
  "      });\n",
  "    }\n",
  "    async function runKnowledgeScan(triggerButton) {\n",
  "      if (knowledgeScanBusy) {\n",
  "        return;\n",
  "      }\n",
  "      knowledgeScanBusy = true;\n",
  "      const buttons = [processKnowledgeButton, roomListKnowledgeButton].filter(Boolean);\n",
  "      const originalText = triggerButton ? triggerButton.textContent : \"立即扫描知识\";\n",
  "      buttons.forEach((button) => { button.disabled = true; });\n",
  "      if (triggerButton) {\n",
  "        triggerButton.textContent = \"扫描中...\";\n",
  "      }\n",
  "      setKnowledgeFlash(\"正在扫描可沉淀知识...\", \"normal\");\n",
  "        try {\n",
  "          const response = await fetch(\"/flowbot/knowledge-harvest/process\", {\n",
  "            method: \"POST\",\n",
  "            headers: {\n",
  "              \"Content-Type\": \"application/json\",\n",
  "            },\n",
  "            body: JSON.stringify({\n",
  "              ignoreReadyAge: true,\n",
  "              roomId: selectedRoomId || \"\",\n",
  "            }),\n",
  "          });\n",
  "          const data = await response.json();\n",
  "          if (!data.ok) {\n",
  "            throw new Error(data.error || \"knowledge_harvest_failed\");\n",
  "          }\n",
  "          setKnowledgeFlash(\n",
  "            \"扫描完成：处理 \" + (data.processed || 0) + \" 条，生成候选 \" + (data.candidates || 0) + \" 条，忽略 \" + (data.ignored || 0) + \" 条，失败 \" + (data.failed || 0) + \" 条\",\n",
  "            data.failed ? \"error\" : \"ok\",\n",
  "          );\n",
  "          await load(true);\n",
  "        } catch (error) {\n",
  "          setKnowledgeFlash(\"扫描失败：\" + String(error?.message || error), \"error\");\n",
  "          alert(\"知识扫描失败：\" + String(error?.message || error));\n",
  "        } finally {\n",
  "          buttons.forEach((button) => { button.disabled = false; });\n",
  "          if (triggerButton) {\n",
  "            triggerButton.textContent = originalText;\n",
  "          }\n",
  "          knowledgeScanBusy = false;\n",
  "        }\n",
  "    }\n",
  "    if (processKnowledgeButton) {\n",
  "      processKnowledgeButton.addEventListener(\"click\", () => runKnowledgeScan(processKnowledgeButton));\n",
  "    }\n",
  "    if (roomListKnowledgeButton) {\n",
  "      roomListKnowledgeButton.addEventListener(\"click\", () => runKnowledgeScan(roomListKnowledgeButton));\n",
  "    }\n",
  "    if (openKnowledgeGovernanceButton) {\n",
  "      openKnowledgeGovernanceButton.addEventListener(\"click\", openKnowledgeGovernance);\n",
  "    }\n",
  "    if (roomCompactSessionButton) {\n",
  "      roomCompactSessionButton.addEventListener(\"click\", () => {\n",
  "        performRoomAction(\n",
  "          \"compact_messages\",\n",
  "          \"确认要清理当前群已结束的智能体任务和失效激活状态吗？\",\n",
  "          \"正在清理当前群智能体状态...\",\n",
  "          \"已清理状态\",\n",
  "        );\n",
  "      });\n",
  "    }\n",
  "    if (roomCleanNoiseButton) {\n",
  "      roomCleanNoiseButton.addEventListener(\"click\", () => {\n",
  "        performRoomAction(\n",
  "          \"cleanup_noise\",\n",
  "          selectedRoomId\n",
  "            ? \"确认清理当前群的看板历史噪音吗？这只会关闭超时待处理、失败/卡住 Agent 和知识扫描失败记录，不会删除 Case 或知识库。\"\n",
  "            : \"确认清理全部群的看板历史噪音吗？这只会关闭超时待处理、失败/卡住 Agent 和知识扫描失败记录，不会删除 Case 或知识库。\",\n",
  "          \"正在清理看板历史噪音...\",\n",
  "          \"已清理看板噪音\",\n",
  "        );\n",
  "      });\n",
  "    }\n",
  "    if (roomClearSessionButton) {\n",
  "      roomClearSessionButton.addEventListener(\"click\", () => {\n",
  "        performRoomAction(\n",
  "          \"clear_session\",\n",
  "          \"确认要清除当前群的智能体跟进状态吗？这会删除该群的任务映射和激活状态，让后续对话从全新状态开始。\",\n",
  "          \"正在清除当前群智能体状态...\",\n",
  "          \"已清空状态\",\n",
  "        );\n",
  "      });\n",
  "    }\n",
  "    if (roomClearMemoryButton) {\n",
  "      roomClearMemoryButton.addEventListener(\"click\", () => {\n",
  "        performRoomAction(\n",
  "          \"clear_memory\",\n",
  "          \"确认要清除当前群的消息记忆吗？这会删除该群已标准化的消息与搜索记忆。\",\n",
  "          \"正在清除当前群记忆...\",\n",
  "          \"已清除记忆\",\n",
  "        );\n",
  "      });\n",
  "    }\n",
  "    if (roomClearArchiveButton) {\n",
  "      roomClearArchiveButton.addEventListener(\"click\", () => {\n",
  "        performRoomAction(\n",
  "          \"clear_archive\",\n",
  "          \"确认要清除当前群的归档与 Case 数据吗？这会删除该群相关 case、thread 和归档记录。\",\n",
  "          \"正在清除当前群归档...\",\n",
  "          \"已清除归档\",\n",
  "        );\n",
  "      });\n",
  "    }\n",
  "    configTestButton.addEventListener(\"click\", () => {\n",
  "      submitConfigTest().catch((error) => {\n",
  "        setConfigFlash(\"测试失败：\" + String(error?.message || error), \"error\");\n",
  "      });\n",
  "    });\n",
  "    if (configRagflowRefreshButton) {\n",
  "      configRagflowRefreshButton.addEventListener(\"click\", () => {\n",
  "        loadRagflowChats(document.getElementById(\"cfg-ragflow-chat-id\")?.value || \"\").catch((error) => {\n",
  "          if (configRagflowStatus) configRagflowStatus.textContent = \"机器人列表加载失败：\" + String(error?.message || error);\n",
  "        });\n",
  "      });\n",
  "    }\n",
  "    configForm.addEventListener(\"submit\", (event) => {\n",
  "      submitConfigSave(event).catch((error) => {\n",
  "        setConfigFlash(\"保存失败：\" + String(error?.message || error), \"error\");\n",
  "      });\n",
  "    });\n",
  "    if (loginRegionSelect && loginRegionInput) {\n",
  "      renderLoginRegions();\n",
  "      loginRegionSelect.addEventListener(\"change\", () => {\n",
  "        loginRegionInput.value = loginRegionSelect.value || DEFAULT_LOGIN_REGION;\n",
  "      });\n",
  "    }\n",
  "    const loginNotifyUrlInput = document.getElementById(\"login-notify-url\");\n",
  "    if (loginNotifyUrlInput && !loginNotifyUrlInput.value.trim()) {\n",
  "      loginNotifyUrlInput.value = DEFAULT_NOTIFY_URL;\n",
  "    }\n",
  "    const loginUrlParams = new URLSearchParams(window.location.search);\n",
  "    const pendingLoginBridge = consumePendingLoginBridge();\n",
  "    if (pendingLoginBridge) {\n",
  "      applyPendingLoginBridge(pendingLoginBridge);\n",
  "    }\n",
  "    if (loginUrlParams.get(\"loginGuid\")) {\n",
  "      document.getElementById(\"login-guid\").value = loginUrlParams.get(\"loginGuid\");\n",
  "    }\n",
  "    if (loginUrlParams.get(\"loginRegion\")) {\n",
  "      loginRegionInput.value = loginUrlParams.get(\"loginRegion\");\n",
  "      if (loginRegionSelect) {\n",
  "        loginRegionSelect.value = loginUrlParams.get(\"loginRegion\");\n",
  "      }\n",
  "    }\n",
  "    if (loginForm) {\n",
  "      loginForm.addEventListener(\"submit\", (event) => {\n",
  "        submitLoginStart(event).catch((error) => {\n",
  "          setLoginFlash(\"登录失败：\" + String(error?.message || error), \"error\");\n",
  "          renderLoginStatus(\"登录流程失败\", [String(error?.message || error)], \"error\");\n",
  "        });\n",
  "      });\n",
  "    }\n",
  "    if (loginOpenProviderButton) {\n",
  "      loginOpenProviderButton.addEventListener(\"click\", async () => {\n",
  "        loginOpenProviderButton.disabled = true;\n",
  "        setLoginFlash(\"正在获取公司代理...\");\n",
  "        try {\n",
  "          await fetchLoginProviderResult();\n",
  "        } catch (error) {\n",
  "          setLoginFlash(\"获取代理失败，请稍后重试，或手动填写代理地址。\", \"error\");\n",
  "          renderLoginStatus(\"自动获取代理失败\", [String(error?.message || error)], \"error\");\n",
  "        } finally {\n",
  "          loginOpenProviderButton.disabled = false;\n",
  "        }\n",
  "      });\n",
  "    }\n",
  "    if (loginSetNotifyButton) {\n",
  "      loginSetNotifyButton.addEventListener(\"click\", () => {\n",
  "        submitLoginSetNotify().catch((error) => {\n",
  "          setLoginFlash(\"设置回调地址失败：\" + String(error?.message || error), \"error\");\n",
  "          renderLoginStatus(\"设置回调地址失败\", [String(error?.message || error)], \"error\");\n",
  "        });\n",
  "      });\n",
  "    }\n",
  "    if (loginVerifyButton) {\n",
  "      loginVerifyButton.addEventListener(\"click\", () => {\n",
  "        submitLoginVerify().catch((error) => {\n",
  "          setLoginFlash(\"验证码提交失败：\" + String(error?.message || error), \"error\");\n",
  "          renderLoginStatus(\"验证码提交失败\", [String(error?.message || error)], \"error\");\n",
  "        });\n",
  "      });\n",
  "    }\n",
  "    if (roomSearchInput) {\n",
  "      roomSearchInput.addEventListener(\"input\", () => renderRoomList(lastRooms, lastScope));\n",
  "    }\n",
  "    if (dashboardListSearch) {\n",
  "      dashboardListSearch.addEventListener(\"input\", () => {\n",
  "        dashboardListPageNo = 1;\n",
  "        renderDashboardList(lastRooms);\n",
  "      });\n",
  "    }\n",
  "    if (dashboardListStatus) {\n",
  "      dashboardListStatus.addEventListener(\"change\", () => {\n",
  "        dashboardListPageNo = 1;\n",
  "        renderDashboardList(lastRooms);\n",
  "      });\n",
  "    }\n",
  "    if (dashboardListRefresh) {\n",
  "      dashboardListRefresh.addEventListener(\"click\", () => {\n",
  "        load(true).catch((error) => alert(\"刷新列表失败：\" + String(error?.message || error)));\n",
  "      });\n",
  "    }\n",
  "    if (openDashboardSettingsSystemButton) {\n",
  "      openDashboardSettingsSystemButton.addEventListener(\"click\", () => openDashboardSettings(\"system\"));\n",
  "    }\n",
  "    if (openDashboardSettingsLoginButton) {\n",
  "      openDashboardSettingsLoginButton.addEventListener(\"click\", () => openDashboardSettings(\"login\"));\n",
  "    }\n",
  "    document.querySelectorAll(\"[data-back-to-dashboard-list]\").forEach((button) => {\n",
  "      button.addEventListener(\"click\", () => openDashboardList());\n",
  "    });\n",
  "    if (dashboardListPrev) {\n",
  "      dashboardListPrev.addEventListener(\"click\", () => {\n",
  "        dashboardListPageNo = Math.max(1, dashboardListPageNo - 1);\n",
  "        renderDashboardList(lastRooms);\n",
  "      });\n",
  "    }\n",
  "    if (dashboardListNext) {\n",
  "      dashboardListNext.addEventListener(\"click\", () => {\n",
  "        dashboardListPageNo += 1;\n",
];
