"use strict";

module.exports = [
  "        renderDashboardList(lastRooms);\n",
  "      });\n",
  "    }\n",
  "    if (backToDashboardList) {\n",
  "      backToDashboardList.addEventListener(\"click\", openDashboardList);\n",
  "    }\n",
  "    if (roomListRefreshButton) {\n",
  "      roomListRefreshButton.addEventListener(\"click\", () => {\n",
  "        load(true).catch((error) => alert(\"刷新失败：\" + String(error?.message || error)));\n",
  "      });\n",
  "    }\n",
  "    if (roomListProcessButton && processPendingButton) {\n",
  "      roomListProcessButton.addEventListener(\"click\", () => processPendingButton.click());\n",
  "    }\n",
  "    if (roomListCleanNoiseButton && roomCleanNoiseButton) {\n",
  "      roomListCleanNoiseButton.addEventListener(\"click\", () => roomCleanNoiseButton.click());\n",
  "    }\n",
  "    if (roomListCompactButton && roomCompactSessionButton) {\n",
  "      roomListCompactButton.addEventListener(\"click\", () => roomCompactSessionButton.click());\n",
  "    }\n",
  "    if (roomListClearSessionButton && roomClearSessionButton) {\n",
  "      roomListClearSessionButton.addEventListener(\"click\", () => roomClearSessionButton.click());\n",
  "    }\n",
  "    if (roomListClearMemoryButton && roomClearMemoryButton) {\n",
  "      roomListClearMemoryButton.addEventListener(\"click\", () => roomClearMemoryButton.click());\n",
  "    }\n",
  "    if (roomListClearArchiveButton && roomClearArchiveButton) {\n",
  "      roomListClearArchiveButton.addEventListener(\"click\", () => roomClearArchiveButton.click());\n",
  "    }\n",
  "    roomSelector.addEventListener(\"change\", () => {\n",
  "      roomActionFlashSticky = false;\n",
  "      openRoomDetail(roomSelector.value || \"\");\n",
  "    });\n",
  "    document.addEventListener(\"visibilitychange\", updateRefreshStatus);\n",
  "    setupDashboardTabs();\n",
  "    updateDashboardView();\n",
  "    updateRoomActionButtons();\n",
  "\n",
  "    loadConfig().catch((error) => {\n",
  "      setConfigFlash(\"配置加载失败：\" + String(error?.message || error), \"error\");\n",
  "    });\n",
  "    if (loginUrlParams.get(\"autostartLogin\") === \"1\" && pendingLoginBridge?.proxyFetchResult) {\n",
  "      setTimeout(() => {\n",
  "        submitLoginStart({\n",
  "          preventDefault() {},\n",
  "        }).catch((error) => {\n",
  "          setLoginFlash(\"登录失败：\" + String(error?.message || error), \"error\");\n",
  "          renderLoginStatus(\"登录流程失败\", [String(error?.message || error)], \"error\");\n",
  "        });\n",
  "      }, 150);\n",
  "    }\n",
  "    load(true).catch((error) => {\n",
  "      document.body.innerHTML = '<div class=\"wrap\"><div class=\"panel\"><h2>加载失败</h2><pre>' + escapeHtml(String(error?.stack || error)) + '</pre></div></div>';\n",
  "    });\n",
  "  </script>\n",
  "</body>\n",
  "</html>",
];
