"use strict";

module.exports = [
  "        .replaceAll(\"'\", \"&#39;\");\n",
  "    }\n",
  "\n",
  "    function cssEscape(value) {\n",
  "      if (window.CSS && typeof window.CSS.escape === \"function\") {\n",
  "        return window.CSS.escape(String(value ?? \"\"));\n",
  "      }\n",
  "      return String(value ?? \"\").replace(/[\"\\\\]/g, \"\\\\$&\");\n",
  "    }\n",
  "\n",
  "    function formatJson(value) {\n",
  "      return escapeHtml(JSON.stringify(value, null, 2));\n",
  "    }\n",
  "\n",
  "    let previewSeed = 0;\n",
  "    const previewStore = new Map();\n",
  "    const listPageState = new Map();\n",
  "    const nestedPagerRegistry = new Map();\n",
  "    let isLoading = false;\n",
  "    const PREVIEW_MAX_DEPTH = 4;\n",
  "    const PREVIEW_MAX_ARRAY = 12;\n",
  "    const PREVIEW_MAX_KEYS = 24;\n",
  "    const PREVIEW_MAX_STRING = 1200;\n",
  "\n",
  "    function buildPreviewData(value, depth = 0) {\n",
  "      if (value == null) {\n",
  "        return value;\n",
  "      }\n",
  "      if (typeof value === \"string\") {\n",
  "        if (value.length <= PREVIEW_MAX_STRING) {\n",
  "          return value;\n",
  "        }\n",
  "        return value.slice(0, PREVIEW_MAX_STRING) + \"... [truncated \" + (value.length - PREVIEW_MAX_STRING) + \" chars]\";\n",
  "      }\n",
  "      if (typeof value !== \"object\") {\n",
  "        return value;\n",
  "      }\n",
  "      if (depth >= PREVIEW_MAX_DEPTH) {\n",
  "        if (Array.isArray(value)) {\n",
  "          return \"[array(\" + value.length + \") truncated]\";\n",
  "        }\n",
  "        return \"[object truncated keys=\" + Object.keys(value).length + \"]\";\n",
  "      }\n",
  "      if (Array.isArray(value)) {\n",
  "        const result = value.slice(0, PREVIEW_MAX_ARRAY).map((item) => buildPreviewData(item, depth + 1));\n",
  "        if (value.length > PREVIEW_MAX_ARRAY) {\n",
  "          result.push(\"[+\" + (value.length - PREVIEW_MAX_ARRAY) + \" more items]\");\n",
  "        }\n",
  "        return result;\n",
  "      }\n",
  "      const result = {};\n",
  "      const keys = Object.keys(value);\n",
  "      for (const key of keys.slice(0, PREVIEW_MAX_KEYS)) {\n",
  "        result[key] = buildPreviewData(value[key], depth + 1);\n",
  "      }\n",
  "      if (keys.length > PREVIEW_MAX_KEYS) {\n",
  "        result.__truncated_keys__ = keys.length - PREVIEW_MAX_KEYS;\n",
  "      }\n",
  "      return result;\n",
  "    }\n",
  "\n",
  "    function registerPreview(value) {\n",
  "      const id = \"preview-\" + (++previewSeed);\n",
  "      previewStore.set(id, buildPreviewData(value));\n",
  "      return id;\n",
  "    }\n",
  "\n",
  "    function renderJsonDetails(label, value) {\n",
  "      const id = registerPreview(value);\n",
  "      return `\n",
  "        <details class=\"json-details\" data-preview-id=\"${id}\">\n",
  "          <summary>${escapeHtml(label)}</summary>\n",
  "          <pre hidden>点击后加载中...</pre>\n",
  "        </details>\n",
  "      `;\n",
  "    }\n",
  "\n",
  "    function renderMediaPreview(item) {\n",
  "      const media = item?.normalized || item;\n",
  "      const mediaUrl = media?.mediaLocalUrl || media?.media_local_url || \"\";\n",
  "      if (!mediaUrl) {\n",
  "        return \"\";\n",
  "      }\n",
  "      const mediaKind = media?.mediaKind || media?.media_kind || \"\";\n",
  "      const parts = [];\n",
  "      const mediaMimeType = media?.mediaMimeType || media?.media_mime_type || \"\";\n",
  "      const mediaSizeBytes = media?.mediaSizeBytes ?? media?.media_size_bytes ?? \"\";\n",
  "      const mediaWidth = media?.mediaWidth ?? media?.media_width ?? \"\";\n",
  "      const mediaHeight = media?.mediaHeight ?? media?.media_height ?? \"\";\n",
  "      const transcriptText = media?.transcriptText || media?.transcript_text || \"\";\n",
  "      const transcriptStatus = media?.transcriptStatus || media?.transcript_status || \"\";\n",
  "      const transcriptError = media?.transcriptError || media?.transcript_error || \"\";\n",
  "      if (mediaMimeType) parts.push(\"类型: \" + mediaMimeType);\n",
  "      if (mediaSizeBytes) parts.push(\"大小: \" + mediaSizeBytes + \" bytes\");\n",
  "      if (mediaWidth && mediaHeight) parts.push(\"尺寸: \" + mediaWidth + \" x \" + mediaHeight);\n",
  "      const meta = parts.join(\" · \");\n",
  "      if (mediaKind === \"image\") {\n",
  "        return `\n",
  "          <div class=\"media-preview\">\n",
  "            <a class=\"media-link\" href=\"${escapeHtml(mediaUrl)}\" target=\"_blank\" rel=\"noreferrer\">\n",
  "              <img src=\"${escapeHtml(mediaUrl)}\" alt=\"media preview\" loading=\"lazy\">\n",
  "            </a>\n",
  "            <div class=\"media-meta\">${escapeHtml(meta || \"已下载原图\")}</div>\n",
  "          </div>\n",
  "        `;\n",
  "      }\n",
  "      if (mediaKind === \"video\") {\n",
  "        return `\n",
  "          <div class=\"media-preview\">\n",
  "            <video controls preload=\"metadata\" src=\"${escapeHtml(mediaUrl)}\"></video>\n",
  "            <div class=\"media-meta\">${escapeHtml(meta || \"已下载视频\")} · <a class=\"media-link\" href=\"${escapeHtml(mediaUrl)}\" target=\"_blank\" rel=\"noreferrer\">打开原文件</a></div>\n",
  "          </div>\n",
  "        `;\n",
  "      }\n",
  "      if (mediaKind === \"audio\") {\n",
  "        const transcriptHtml = transcriptText\n",
  "          ? `<div class=\"media-transcript\"><strong>语音转写：</strong>${escapeHtml(transcriptText)}</div>`\n",
  "          : (transcriptStatus === \"failed\"\n",
  "            ? `<div class=\"media-transcript\"><strong>语音转写失败：</strong>${escapeHtml(transcriptError || \"未知错误\")}</div>`\n",
  "            : \"\");\n",
  "        return `\n",
  "          <div class=\"media-preview\">\n",
  "            <audio controls preload=\"none\" src=\"${escapeHtml(mediaUrl)}\"></audio>\n",
  "            <div class=\"media-meta\">${escapeHtml(meta || \"已下载音频\")} · <a class=\"media-link\" href=\"${escapeHtml(mediaUrl)}\" target=\"_blank\" rel=\"noreferrer\">下载音频</a></div>\n",
  "            ${transcriptHtml}\n",
  "          </div>\n",
  "        `;\n",
  "      }\n",
  "      return `\n",
  "        <div class=\"media-preview\">\n",
  "          <div class=\"media-meta\">${escapeHtml(meta || \"已下载文件\")}</div>\n",
  "          <a class=\"media-link\" href=\"${escapeHtml(mediaUrl)}\" target=\"_blank\" rel=\"noreferrer\">打开原文件</a>\n",
  "        </div>\n",
  "      `;\n",
  "    }\n",
  "\n",
  "    function renderArchivedMessages(item) {\n",
  "      const timeline = item?.conversationDetail?.timeline || item?.caseDetail?.messages || [];\n",
  "      if (!Array.isArray(timeline) || !timeline.length) {\n",
  "        return '<div class=\"muted\" style=\"margin-top:12px;\">当前 Case 还没有展开的原始消息时间线。</div>';\n",
  "      }\n",
  "      const pagerId = \"case-timeline:\" + String(item?.case_id || item?.source_thread_id || item?.summary || \"unknown\");\n",
  "      const pageSize = 8;\n",
  "      const totalPages = Math.max(1, Math.ceil(timeline.length / pageSize));\n",
  "      const currentPage = Math.min(Math.max(listPageState.get(pagerId) || 1, 1), totalPages);\n",
  "      listPageState.set(pagerId, currentPage);\n",
  "      const start = (currentPage - 1) * pageSize;\n",
  "      const pageItems = timeline.slice(start, start + pageSize);\n",
  "      const rows = pageItems.map((message) => {\n",
  "        const meta = [\n",
  "          message?.time || \"\",\n",
  "          message?.sender || \"unknown\",\n",
  "          message?.type || \"text\",\n",
  "          message?.message_role ? (\"角色: \" + (MESSAGE_ROLE_LABELS[message.message_role] || message.message_role)) : \"\",\n",
  "        ].filter(Boolean).join(\" · \");\n",
  "        const content = message?.content || \"(空内容)\";\n",
  "        return `\n",
  "          <div class=\"timeline-item\">\n",
  "            <div class=\"timeline-meta\">${escapeHtml(meta)}</div>\n",
  "            <div class=\"timeline-text\">${escapeHtml(content)}</div>\n",
  "            ${renderMediaPreview(message)}\n",
  "          </div>\n",
  "        `;\n",
  "      }).join(\"\");\n",
  "      const content = `\n",
  "        <div class=\"message-timeline\">\n",
  "          <div class=\"timeline-title\">原始消息时间线</div>\n",
  "          ${rows}\n",
  "          <div class=\"pager\">\n",
  "            <div class=\"pager-info\">第 ${currentPage} / ${totalPages} 页，当前显示 ${pageItems.length} 条，共 ${timeline.length} 条</div>\n",
  "            <div class=\"pager-actions\">\n",
  "              <button type=\"button\" data-page-action=\"prev\" ${currentPage <= 1 ? \"disabled\" : \"\"}>上一页</button>\n",
  "              <button type=\"button\" data-page-action=\"next\" ${currentPage >= totalPages ? \"disabled\" : \"\"}>下一页</button>\n",
  "            </div>\n",
  "          </div>\n",
  "        </div>\n",
  "      `;\n",
  "      nestedPagerRegistry.set(pagerId, () => renderArchivedMessages(item));\n",
  "      return `<div data-nested-pager-id=\"${escapeHtml(pagerId)}\">${content}</div>`;\n",
  "    }\n",
  "\n",
  "    function renderCaseActivities(item) {\n",
  "      const activities = item?.caseDetail?.activities || item?.conversationDetail?.activities || [];\n",
  "      if (!Array.isArray(activities) || !activities.length) {\n",
  "        return '<div class=\"muted\" style=\"margin-top:12px;\">当前 Case 还没有活动时间线。</div>';\n",
  "      }\n",
  "      const rows = activities.map((activity) => {\n",
  "        const meta = [\n",
  "          activity?.time || \"\",\n",
  "          activity?.sender || \"unknown\",\n",
  "          activity?.message_role ? (MESSAGE_ROLE_LABELS[activity.message_role] || activity.message_role) : \"\",\n",
  "          activity?.batch_action ? (BATCH_ACTION_LABELS[activity.batch_action] || activity.batch_action) : \"\",\n",
  "        ].filter(Boolean).join(\" · \");\n",
  "        return `\n",
  "          <div class=\"timeline-item\">\n",
  "            <div class=\"timeline-meta\">${escapeHtml(meta)}</div>\n",
  "            <div class=\"timeline-text\">${escapeHtml(activity?.summary || \"(空摘要)\")}</div>\n",
  "          </div>\n",
  "        `;\n",
  "      }).join(\"\");\n",
  "      return `\n",
  "        <details class=\"json-details\" style=\"margin-top:12px;\">\n",
  "          <summary>查看 Case 活动时间线（${activities.length}）</summary>\n",
  "          <div class=\"message-timeline\" style=\"margin-top:12px;\">\n",
  "            <div class=\"timeline-title\">Case 活动时间线</div>\n",
  "            ${rows}\n",
  "          </div>\n",
  "        </details>\n",
  "      `;\n",
  "    }\n",
  "\n",
  "    function hasOpenDetails() {\n",
  "      return document.querySelector(\".json-details[open]\") !== null;\n",
  "    }\n",
  "\n",
  "    function updateRefreshStatus() {\n",
  "      const el = document.getElementById(\"meta-refresh\");\n",
  "      if (el) el.textContent = \"手动刷新\";\n",
  "    }\n",
  "\n",
  "    function hydrateLazyDetails(root) {\n",
  "      const detailsList = root.querySelectorAll(\".json-details\");\n",
  "      for (const details of detailsList) {\n",
  "        if (details.dataset.bound === \"1\") {\n",
  "          continue;\n",
  "        }\n",
  "        details.dataset.bound = \"1\";\n",
  "        details.addEventListener(\"toggle\", () => {\n",
  "          const previewId = details.dataset.previewId;\n",
  "          const pre = details.querySelector(\"pre\");\n",
  "          if (!pre || !previewId) {\n",
  "            return;\n",
  "          }\n",
  "          if (details.open) {\n",
  "            const allOpen = document.querySelectorAll(\".json-details[open]\");\n",
  "            for (const other of allOpen) {\n",
  "              if (other !== details) {\n",
  "                other.open = false;\n",
  "              }\n",
  "            }\n",
  "            const value = previewStore.get(previewId);\n",
  "            pre.textContent = JSON.stringify(value, null, 2);\n",
  "            pre.hidden = false;\n",
  "          } else {\n",
  "            pre.textContent = \"\";\n",
  "            pre.hidden = true;\n",
  "          }\n",
  "          updateRefreshStatus();\n",
  "        });\n",
  "      }\n",
  "    }\n",
  "\n",
  "    function setChips(id, values) {\n",
  "      const root = document.getElementById(id);\n",
  "      root.innerHTML = \"\";\n",
  "      for (const value of values) {\n",
  "        const chip = document.createElement(\"span\");\n",
  "        chip.className = \"chip\";\n",
  "        chip.textContent = value;\n",
  "        root.appendChild(chip);\n",
  "      }\n",
  "      if (!values.length) {\n",
  "        root.innerHTML = '<span class=\"muted\">暂无</span>';\n",
  "      }\n",
  "    }\n",
  "\n",
  "    function renderRoomSelector(rooms, scope) {\n",
  "      if (!roomSelector) {\n",
  "        return;\n",
  "      }\n",
  "      const currentValue = scope?.selectedRoomId || \"\";\n",
  "      roomSelector.innerHTML = \"\";\n",
  "      const allOption = document.createElement(\"option\");\n",
  "      allOption.value = \"\";\n",
  "      allOption.textContent = \"全部群\";\n",
  "      roomSelector.appendChild(allOption);\n",
  "      for (const room of rooms || []) {\n",
  "        const option = document.createElement(\"option\");\n",
  "        option.value = room.id;\n",
  "        option.textContent = room.name === room.id\n",
  "          ? room.id\n",
  "          : room.name + \" (\" + room.id + \")\";\n",
  "        roomSelector.appendChild(option);\n",
  "      }\n",
  "      roomSelector.value = currentValue;\n",
  "      const actualValue = roomSelector.value || \"\";\n",
  "      if (selectedRoomId !== actualValue) {\n",
  "        roomActionFlashSticky = false;\n",
  "      }\n",
  "      const metaRoom = document.getElementById(\"meta-room\");\n",
  "      if (metaRoom) {\n",
  "        metaRoom.textContent = \"当前范围：\" + (actualValue ? (scope?.selectedRoomLabel || actualValue) : \"全部群\");\n",
  "      }\n",
  "      selectedRoomId = actualValue;\n",
  "      updateRoomActionButtons();\n",
  "    }\n",
  "\n",
  "    function roomDisplayName(room) {\n",
  "      if (!room) return \"全部群\";\n",
  "      const cachedName = roomNameCache.get(String(room.id || \"\"));\n",
  "      return cachedName || (room.name && room.name !== room.id ? room.name : (room.id || \"未命名群\"));\n",
  "    }\n",
  "\n",
  "    function renderRoomDetailHeader(room, scope) {\n",
  "      const title = document.getElementById(\"room-detail-title\");\n",
  "      const isAll = !scope?.selectedRoomId;\n",
  "      const name = isAll ? \"全部群\" : roomDisplayName(room);\n",
  "      if (title) title.textContent = name;\n",
  "    }\n",
  "\n",
  "    function updateDashboardView() {\n",
  "      try {\n",
  "        window.parent?.postMessage({ type: \"yuebai-flowbot-view\", view: dashboardView }, window.location.origin);\n",
  "      } catch {}\n",
  "      if (dashboardListPage) {\n",
  "        dashboardListPage.style.display = dashboardView === \"list\" ? \"grid\" : \"none\";\n",
  "      }\n",
  "      if (dashboardSettingsPage) {\n",
  "        dashboardSettingsPage.style.display = dashboardView === \"settings\" ? \"grid\" : \"none\";\n",
  "      }\n",
  "      if (dashboardDetailPage) {\n",
  "        dashboardDetailPage.style.display = dashboardView === \"detail\" ? \"grid\" : \"none\";\n",
  "      }\n",
  "      const statsRoot = document.getElementById(\"stats\");\n",
  "      if (statsRoot) {\n",
  "        statsRoot.style.display = dashboardView === \"detail\" ? \"grid\" : \"none\";\n",
  "      }\n",
  "      if (refreshNowButton) {\n",
  "        refreshNowButton.style.display = dashboardView === \"detail\" ? \"none\" : \"inline-flex\";\n",
  "      }\n",
  "      if (dashboardDetailRefreshButton) {\n",
  "        dashboardDetailRefreshButton.style.display = dashboardView === \"detail\" ? \"inline-flex\" : \"none\";\n",
  "      }\n",
  "    }\n",
  "\n",
  "    function updateSettingsTabView() {\n",
  "      document.querySelectorAll(\"[data-settings-section]\").forEach((section) => {\n",
  "        section.classList.toggle(\"active\", section.getAttribute(\"data-settings-section\") === currentSettingsTab);\n",
  "      });\n",
  "    }\n",
  "\n",
  "    function openDashboardList() {\n",
  "      dashboardView = \"list\";\n",
  "      selectedRoomId = \"\";\n",
  "      const nextUrl = new URL(window.location.href);\n",
  "      nextUrl.searchParams.delete(\"view\");\n",
  "      nextUrl.searchParams.delete(\"roomId\");\n",
  "      window.history.replaceState({}, \"\", nextUrl.toString());\n",
  "      updateDashboardView();\n",
  "      load(true).catch((error) => alert(\"加载列表失败：\" + String(error?.message || error)));\n",
  "    }\n",
  "\n",
  "    function openDashboardSettings(tab = \"system\") {\n",
  "      dashboardView = \"settings\";\n",
  "      currentSettingsTab = tab === \"login\" ? \"login\" : \"system\";\n",
  "      selectedRoomId = \"\";\n",
  "      if (roomSelector) roomSelector.value = \"\";\n",
  "      const nextUrl = new URL(window.location.href);\n",
  "      nextUrl.searchParams.set(\"view\", \"settings\");\n",
  "      nextUrl.searchParams.set(\"settingsTab\", currentSettingsTab);\n",
  "      nextUrl.searchParams.delete(\"roomId\");\n",
  "      window.history.replaceState({}, \"\", nextUrl.toString());\n",
  "      updateDashboardView();\n",
  "      updateSettingsTabView();\n",
  "      load(true).catch((error) => alert(\"加载配置页失败：\" + String(error?.message || error)));\n",
  "    }\n",
  "\n",
  "    function openRoomDetail(roomId) {\n",
  "      dashboardView = \"detail\";\n",
  "      selectedRoomId = roomId || \"\";\n",
  "      if (roomSelector) roomSelector.value = selectedRoomId;\n",
  "      const nextUrl = new URL(window.location.href);\n",
  "      nextUrl.searchParams.set(\"view\", \"detail\");\n",
  "      if (selectedRoomId) {\n",
  "        nextUrl.searchParams.set(\"roomId\", selectedRoomId);\n",
  "      } else {\n",
  "        nextUrl.searchParams.delete(\"roomId\");\n",
  "      }\n",
  "      window.history.replaceState({}, \"\", nextUrl.toString());\n",
  "      updateDashboardView();\n",
  "      load(true).catch((error) => {\n",
  "        document.body.innerHTML = '<div class=\"wrap\"><div class=\"panel\"><h2>加载失败</h2><pre>' + escapeHtml(String(error?.stack || error)) + '</pre></div></div>';\n",
  "      });\n",
  "    }\n",
  "\n",
  "    function selectRoomFromList(roomId) {\n",
  "      roomActionFlashSticky = false;\n",
  "      openRoomDetail(roomId);\n",
  "    }\n",
  "\n",
  "    function getDashboardRows(rooms) {\n",
  "      const allRows = Array.isArray(rooms) ? rooms : [];\n",
  "      return allRows.map((room) => ({\n",
  "        id: room.id || \"\",\n",
  "        name: roomNameCache.get(String(room.id || \"\")) || roomDisplayName(room),\n",
  "        hasName: Boolean(roomNameCache.get(String(room.id || \"\")) || (room.name && room.name !== room.id)),\n",
  "        platform: String(room.platform || (String(room.id || \"\").startsWith(\"oc_\") ? \"feishu\" : \"wecom\")),\n",
  "        guid: room.guid || \"\",\n",
  "        messageCount: Number(room.messageCount || 0),\n",
  "        caseCount: Number(room.caseCount || 0),\n",
  "        threadCount: Number(room.threadCount || 0),\n",
  "        knowledgeCount: Number(room.knowledgeCount || room.knowledgePendingReviewTotal || 0),\n",
  "        attentionCount: Number(room.attentionCount || room.failedCount || 0),\n",
  "      }));\n",
  "    }\n",
  "\n",
  "    function platformLabel(platform) {\n",
  "      return String(platform || \"\") === \"feishu\" ? \"飞书\" : \"企微\";\n",
  "    }\n",
  "\n",
  "    async function enrichDashboardRoomNames(rooms) {\n",
  "      if (roomNameLookupBusy || !Array.isArray(rooms) || !rooms.length) {\n",
  "        return;\n",
  "      }\n",
  "      const targets = rooms.filter((room) => {\n",
  "        const roomId = String(room?.id || \"\").trim();\n",
  "        return roomId && (!room.name || room.name === roomId) && !roomNameCache.has(roomId);\n",
  "      }).slice(0, DASHBOARD_LIST_PAGE_SIZE).map((room) => ({\n",
  "        roomId: String(room.id || \"\"),\n",
  "        platform: String(room.platform || (String(room.id || \"\").startsWith(\"oc_\") ? \"feishu\" : \"wecom\")),\n",
  "      }));\n",
  "      if (!targets.length) {\n",
  "        return;\n",
  "      }\n",
  "      roomNameLookupBusy = true;\n",
  "      try {\n",
  "        const response = await fetch(\"/flowbot/wecom-login/room-details\", {\n",
  "          method: \"POST\",\n",
  "          headers: { \"Content-Type\": \"application/json\" },\n",
  "          body: JSON.stringify({ rooms: targets }),\n",
  "        });\n",
  "        const data = await response.json();\n",
  "        const roomNames = data?.roomNames || {};\n",
  "        Object.entries(roomNames).forEach(([roomId, name]) => {\n",
  "          if (roomId && name && name !== roomId) {\n",
  "            roomNameCache.set(roomId, name);\n",
  "          }\n",
  "        });\n",
  "        if (roomNameCache.size) {\n",
  "          lastRooms = lastRooms.map((room) => {\n",
  "            const name = roomNameCache.get(String(room.id || \"\"));\n",
  "            return name ? { ...room, name } : room;\n",
  "          });\n",
  "          if (dashboardView === \"list\") {\n",
  "            renderDashboardList(lastRooms);\n",
  "          } else if (dashboardView === \"detail\") {\n",
  "            renderRoomSelector(lastRooms, lastScope);\n",
  "            renderRoomList(lastRooms, lastScope);\n",
  "            renderRoomDetailHeader(lastRooms.find((room) => String(room.id || \"\") === String(selectedRoomId || \"\")), lastScope);\n",
  "          }\n",
  "        }\n",
  "      } catch {}\n",
  "      finally {\n",
  "        roomNameLookupBusy = false;\n",
  "      }\n",
  "    }\n",
  "\n",
  "    function renderDashboardList(rooms) {\n",
  "      if (!dashboardListBody) {\n",
  "        return;\n",
  "      }\n",
  "      const query = String(dashboardListSearch?.value || \"\").trim().toLowerCase();\n",
  "      const status = dashboardListStatus?.value || \"all\";\n",
  "      let rows = getDashboardRows(rooms);\n",
  "      rows = rows.filter((row) => {\n",
  "        const matchesQuery = !query || [row.name, row.id].join(\" \").toLowerCase().includes(query);\n",
  "        const matchesStatus =\n",
  "          status === \"all\"\n",
  "          || (status === \"attention\" && row.attentionCount > 0)\n",
  "          || (status === \"knowledge\" && row.knowledgeCount > 0)\n",
  "          || (status === \"case\" && row.caseCount > 0);\n",
  "        return matchesQuery && matchesStatus;\n",
  "      });\n",
  "      const totalPages = Math.max(1, Math.ceil(rows.length / DASHBOARD_LIST_PAGE_SIZE));\n",
  "      dashboardListPageNo = Math.min(Math.max(1, dashboardListPageNo), totalPages);\n",
  "      const start = (dashboardListPageNo - 1) * DASHBOARD_LIST_PAGE_SIZE;\n",
  "      const pageRows = rows.slice(start, start + DASHBOARD_LIST_PAGE_SIZE);\n",
  "      if (!pageRows.length) {\n",
  "        dashboardListBody.innerHTML = '<tr><td colspan=\"7\">暂无匹配后台。</td></tr>';\n",
  "      } else {\n",
  "        dashboardListBody.innerHTML = pageRows.map((row) => {\n",
  "          const statusText = row.attentionCount > 0\n",
  "            ? \"需要关注\"\n",
  "            : (row.knowledgeCount > 0 ? \"待审核知识\" : \"正常\");\n",
  "          const statusClass = row.attentionCount > 0 ? \"danger\" : (row.knowledgeCount > 0 ? \"warn\" : \"ok\");\n",
  "          return `\n",
  "            <tr>\n",
  "              <td>\n",
  "                <div class=\"room-name\">\n",
  "                  <div class=\"room-title-row\"><span class=\"platform-badge ${escapeHtml(row.platform)}\">${escapeHtml(platformLabel(row.platform))}</span><strong>${escapeHtml(row.name)}</strong></div>\n",
  "                  <small>${escapeHtml(row.hasName ? (row.id || \"-\") : \"群名称暂无\")}</small>\n",
  "                </div>\n",
  "              </td>\n",
  "              <td>${escapeHtml(row.messageCount)}</td>\n",
  "              <td>${escapeHtml(row.caseCount)}</td>\n",
  "              <td>${escapeHtml(row.threadCount)}</td>\n",
  "              <td>${escapeHtml(row.knowledgeCount)}</td>\n",
  "              <td><span class=\"badge ${statusClass}\">${escapeHtml(statusText)}</span></td>\n",
  "              <td><button class=\"table-action\" type=\"button\" data-open-detail=\"${escapeHtml(row.id)}\">详情</button></td>\n",
  "            </tr>\n",
  "          `;\n",
  "        }).join(\"\");\n",
  "      }\n",
  "      if (dashboardListPageInfo) {\n",
  "        dashboardListPageInfo.textContent = \"第 \" + dashboardListPageNo + \" / \" + totalPages + \" 页，共 \" + rows.length + \" 条\";\n",
  "      }\n",
  "      if (dashboardListPrev) dashboardListPrev.disabled = dashboardListPageNo <= 1;\n",
  "      if (dashboardListNext) dashboardListNext.disabled = dashboardListPageNo >= totalPages;\n",
  "      dashboardListBody.querySelectorAll(\"[data-open-detail]\").forEach((button) => {\n",
  "        button.addEventListener(\"click\", () => openRoomDetail(button.getAttribute(\"data-open-detail\") || \"\"));\n",
  "      });\n",
  "      enrichDashboardRoomNames(pageRows).catch(() => {});\n",
  "    }\n",
  "\n",
  "    function renderRoomList(rooms, scope) {\n",
  "      lastRooms = (Array.isArray(rooms) ? rooms : []).map((room) => {\n",
  "        const name = roomNameCache.get(String(room.id || \"\"));\n",
  "        return name ? { ...room, name } : room;\n",
  "      });\n",
  "      lastScope = scope || {};\n",
  "      if (!roomListRoot) {\n",
  "        return;\n",
  "      }\n",
  "      const query = String(roomSearchInput?.value || \"\").trim().toLowerCase();\n",
  "      const allItem = {\n",
  "        id: \"\",\n",
  "        name: \"全部群\",\n",
  "        messageCount: lastRooms.reduce((sum, room) => sum + Number(room.messageCount || 0), 0),\n",
  "        caseCount: lastRooms.reduce((sum, room) => sum + Number(room.caseCount || 0), 0),\n",
  "        threadCount: lastRooms.reduce((sum, room) => sum + Number(room.threadCount || 0), 0),\n",
  "      };\n",
  "      const visibleRooms = [allItem, ...lastRooms].filter((room) => {\n",
  "        if (!query) return true;\n",
  "        return [room.name, room.id].join(\" \").toLowerCase().includes(query);\n",
  "      });\n",
  "      if (!visibleRooms.length) {\n",
  "        roomListRoot.innerHTML = '<div class=\"empty\">没有匹配的群。</div>';\n",
  "        return;\n",
  "      }\n",
  "      roomListRoot.innerHTML = visibleRooms.map((room) => {\n",
  "        const active = String(scope?.selectedRoomId || \"\") === String(room.id || \"\");\n",
  "        const name = roomDisplayName(room);\n",
  "        return `\n",
  "          <button type=\"button\" class=\"room-item ${active ? \"active\" : \"\"}\" data-room-id=\"${escapeHtml(room.id || \"\")}\">\n",
  "            <strong>${escapeHtml(name)}</strong>\n",
  "            <small>${escapeHtml(room.id || \"全部已接入群\")}</small>\n",
  "            <span class=\"room-counts\">\n",
  "              <span>消息 ${escapeHtml(room.messageCount || 0)}</span>\n",
  "              <span>Case ${escapeHtml(room.caseCount || 0)}</span>\n",
  "              <span>Thread ${escapeHtml(room.threadCount || 0)}</span>\n",
  "            </span>\n",
  "          </button>\n",
  "        `;\n",
  "      }).join(\"\");\n",
  "      roomListRoot.querySelectorAll(\"[data-room-id]\").forEach((button) => {\n",
  "        button.addEventListener(\"click\", () => selectRoomFromList(button.getAttribute(\"data-room-id\") || \"\"));\n",
  "      });\n",
  "      const selectedRoom = lastRooms.find((room) => String(room.id || \"\") === String(scope?.selectedRoomId || \"\"));\n",
  "      renderRoomDetailHeader(selectedRoom, scope);\n",
  "      renderDashboardList(lastRooms);\n",
  "    }\n",
  "\n",
  "    function formatDurationMs(value) {\n",
  "      const ms = Number(value);\n",
  "      if (!Number.isFinite(ms) || ms < 0) {\n",
  "        return \"-\";\n",
  "      }\n",
  "      if (ms < 1000) {\n",
  "        return ms + \" ms\";\n",
  "      }\n",
  "      const seconds = ms / 1000;\n",
  "      if (seconds < 60) {\n",
  "        return seconds.toFixed(seconds >= 10 ? 1 : 2) + \" s\";\n",
  "      }\n",
  "      const minutes = Math.floor(seconds / 60);\n",
  "      const remainSeconds = Math.round(seconds % 60);\n",
  "      return minutes + \"m \" + remainSeconds + \"s\";\n",
  "    }\n",
  "\n",
  "    function renderAgentOverview(agentOverview, scope) {\n",
  "      const tasks = agentOverview?.tasks || {};\n",
  "      const sessionInfo = agentOverview?.session || {};\n",
  "      const latency = agentOverview?.latency || {};\n",
  "      const latencyBreakdown = agentOverview?.latencyBreakdown || {};\n",
  "      const routingReasons = Array.isArray(agentOverview?.routingReasons) ? agentOverview.routingReasons : [];\n",
  "      const toolBreakdown = Array.isArray(agentOverview?.tools?.breakdown) ? agentOverview.tools.breakdown : [];\n",
  "      const latestOutcome = agentOverview?.latestOutcome || null;\n",
  "      const recentFailures = Array.isArray(agentOverview?.recentFailures) ? agentOverview.recentFailures : [];\n",
  "      const latestOutcomeHtml = latestOutcome\n",
  "        ? `\n",
  "          <div class=\"agent-list-item\">\n",
  "            <div class=\"title\">${escapeHtml(latestOutcome.senderName || latestOutcome.senderId || \"unknown\")} · ${escapeHtml(latestOutcome.statusLabel || latestOutcome.status || \"-\")}</div>\n",
  "            <div class=\"desc\">\n",
  "              traceId: ${escapeHtml(latestOutcome.traceId || \"-\")} · 耗时: ${escapeHtml(formatDurationMs(latestOutcome.durationMs))}<br>\n",
  "              时间: ${escapeHtml(latestOutcome.completedAt || latestOutcome.updatedAt || latestOutcome.sendTimeIso || \"-\")}<br>\n",
  "              结果: ${escapeHtml(latestOutcome.responseSummary || latestOutcome.note || \"无额外说明\")}\n",
  "            </div>\n",
  "          </div>\n",
  "        `\n",
  "        : '<div class=\"empty\">当前范围内还没有已完成的智能体处理结果。</div>';\n",
  "      const sessionHtml = `\n",
  "        <div class=\"agent-list-item\">\n",
  "          <div class=\"title\">当前策略</div>\n",
  "          <div class=\"desc\">\n",
  "            会话键策略: ${escapeHtml(sessionInfo.strategy || \"wake\")}<br>\n",
  "            仅在明确唤醒时创建新会话: ${sessionInfo.wakeOnly ? \"是\" : \"否\"}<br>\n",
  "            对话激活续聊: ${sessionInfo.activationEnabled ? \"开启\" : \"关闭\"}\n",
  "          </div>\n",
  "        </div>\n",
  "      `;\n",
  "      const failureHtml = recentFailures.length\n",
  "        ? recentFailures.map((item) => `\n",
  "          <div class=\"agent-list-item\">\n",
  "            <div class=\"title\">${escapeHtml(item.senderName || item.senderId || \"unknown\")} · 失败</div>\n",
  "            <div class=\"desc\">\n",
  "              traceId: ${escapeHtml(item.traceId || \"-\")} · 耗时: ${escapeHtml(formatDurationMs(item.durationMs))}<br>\n",
  "              时间: ${escapeHtml(item.completedAt || item.updatedAt || \"-\")}<br>\n",
  "              原因: ${escapeHtml(item.note || \"未知错误\")}\n",
  "            </div>\n",
  "          </div>\n",
  "        `).join(\"\")\n",
  "        : '<div class=\"empty\">当前范围内最近没有失败任务。</div>';\n",
  "      const routingHtml = routingReasons.length\n",
  "        ? routingReasons.slice(0, 5).map((item) => `\n",
  "          <div class=\"agent-list-item\">\n",
  "            <div class=\"title\">${escapeHtml(item.label)}</div>\n",
  "            <div class=\"desc\">命中 ${escapeHtml(item.count)} 次</div>\n",
  "          </div>\n",
  "        `).join(\"\")\n",
  "        : '<div class=\"empty\">当前范围内没有路由触发记录。</div>';\n",
  "      const toolHtml = toolBreakdown.length\n",
  "        ? toolBreakdown.slice(0, 6).map((item) => `\n",
  "          <div class=\"agent-list-item\">\n",
  "            <div class=\"title\">${escapeHtml(item.label)}</div>\n",
  "            <div class=\"desc\">调用 ${escapeHtml(item.count)} 次</div>\n",
  "          </div>\n",
  "        `).join(\"\")\n",
  "        : '<div class=\"empty\">当前范围内还没有工具调用记录。</div>';\n",
  "      return `\n",
  "        <div class=\"agent-grid\">\n",
  "          <div class=\"agent-card\">\n",
  "            <strong>Agent 运行状态</strong>\n",
  "            <div class=\"agent-kpis\">\n",
  "              <div class=\"agent-kpi\"><div class=\"label\">待处理</div><div class=\"value\">${escapeHtml(tasks.pending || 0)}</div></div>\n",
  "              <div class=\"agent-kpi\"><div class=\"label\">处理中</div><div class=\"value\">${escapeHtml(tasks.claimed || 0)}</div></div>\n",
  "              <div class=\"agent-kpi\"><div class=\"label\">已发出</div><div class=\"value\">${escapeHtml(tasks.replied || 0)}</div></div>\n",
  "              <div class=\"agent-kpi\"><div class=\"label\">已回复</div><div class=\"value\">${escapeHtml(tasks.completed || 0)}</div></div>\n",
  "              <div class=\"agent-kpi\"><div class=\"label\">已忽略</div><div class=\"value\">${escapeHtml(tasks.ignored || 0)}</div></div>\n",
  "              <div class=\"agent-kpi\"><div class=\"label\">失败</div><div class=\"value\">${escapeHtml(tasks.failed || 0)}</div></div>\n",
  "              <div class=\"agent-kpi\"><div class=\"label\">平均耗时</div><div class=\"value\">${escapeHtml(formatDurationMs(latency.avgMs))}</div></div>\n",
  "            </div>\n",
  "            <div class=\"meta-note\">当前范围：${escapeHtml(scope?.selectedRoomLabel || \"全部群\")} · 耗时样本数：${escapeHtml(latency.sampleCount || 0)} · 最快/最慢：${escapeHtml(formatDurationMs(latency.minMs))} / ${escapeHtml(formatDurationMs(latency.maxMs))}</div>\n",
  "          </div>\n",
  "          <div class=\"agent-card\">\n",
  "            <strong>会话策略与最近结果</strong>\n",
  "            <div class=\"agent-list\">${sessionHtml}${latestOutcomeHtml}</div>\n",
  "          </div>\n",
  "          <div class=\"agent-card\">\n",
  "            <strong>最近失败任务</strong>\n",
  "            <div class=\"agent-list\">${failureHtml}</div>\n",
  "          </div>\n",
  "          <div class=\"agent-card\">\n",
  "            <strong>触发原因分布</strong>\n",
  "            <div class=\"agent-list\">${routingHtml}</div>\n",
  "          </div>\n",
  "          <div class=\"agent-card\">\n",
  "            <strong>工具调用观测</strong>\n",
  "            <div class=\"agent-kpis\" style=\"margin-bottom: 10px;\">\n",
  "              <div class=\"agent-kpi\"><div class=\"label\">总调用次数</div><div class=\"value\">${escapeHtml(agentOverview?.tools?.totalCalls || 0)}</div></div>\n",
  "              <div class=\"agent-kpi\"><div class=\"label\">命中工具种类</div><div class=\"value\">${escapeHtml(toolBreakdown.length || 0)}</div></div>\n",
  "            </div>\n",
  "            <div class=\"agent-list\">${toolHtml}</div>\n",
  "          </div>\n",
  "          <div class=\"agent-card\">\n",
  "            <strong>端到端耗时拆分</strong>\n",
  "            <div class=\"agent-kpis\">\n",
  "              <div class=\"agent-kpi\"><div class=\"label\">排队等待</div><div class=\"value\">${escapeHtml(formatDurationMs(latencyBreakdown.queueWaitAvgMs))}</div></div>\n",
  "              <div class=\"agent-kpi\"><div class=\"label\">模型处理</div><div class=\"value\">${escapeHtml(formatDurationMs(latencyBreakdown.processingAvgMs))}</div></div>\n",
  "              <div class=\"agent-kpi\"><div class=\"label\">发送回复</div><div class=\"value\">${escapeHtml(formatDurationMs(latencyBreakdown.replySendAvgMs))}</div></div>\n",
  "              <div class=\"agent-kpi\"><div class=\"label\">总耗时</div><div class=\"value\">${escapeHtml(formatDurationMs(latencyBreakdown.totalAvgMs))}</div></div>\n",
  "            </div>\n",
  "            <div class=\"meta-note\">这里展示的是当前范围内最近已完成任务的平均耗时拆分，用于看慢点是在队列、模型还是发消息阶段。</div>\n",
  "          </div>\n",
  "        </div>\n",
  "      `;\n",
  "    }\n",
  "\n",
  "    function renderNeedsAttention(needsAttention) {\n",
  "      const items = Array.isArray(needsAttention?.items) ? needsAttention.items : [];\n",
  "      if (!items.length) {\n",
  "        return `\n",
  "          <div class=\"flow-summary\">\n",
  "            <strong>当前没有需要立刻处理的事项</strong>\n",
  "            <span>待处理队列、Agent 失败和知识候选都处于干净状态。这个时候 dashboard 可以主要用来看流量和回归验证。</span>\n",
  "          </div>\n",
  "        `;\n",
  "      }\n",
  "      const html = items.slice(0, 6).map((item) => {\n",
  "        const severity = item.severity === \"danger\" ? \"danger\" : (item.severity === \"warn\" ? \"warn\" : \"info\");\n",
  "        return `\n",
  "          <div class=\"attention-card ${severity}\">\n",
  "            <div class=\"topline\">\n",
  "              <div class=\"title\">${escapeHtml(item.title || \"待处理事项\")}</div>\n",
  "              <div class=\"count\">${escapeHtml(item.count || 0)}</div>\n",
  "            </div>\n",
  "          </div>\n",
  "        `;\n",
  "      }).join(\"\");\n",
  "      return `\n",
  "        <div class=\"attention-grid\">${html}</div>\n",
  "      `;\n",
  "    }\n",
  "\n",
  "    function renderDailySummary(summary) {\n",
  "      if (!summary) {\n",
  "        return \"\";\n",
  "      }\n",
  "      const cards = [\n",
  "        {\n",
  "          label: \"群消息\",\n",
  "          value: summary.messages?.accepted || 0,\n",
  "          desc: \"回调 \" + (summary.messages?.callbacks || 0) + \" · 标准化 \" + (summary.messages?.normalized || 0) + \" · 拦截 \" + (summary.messages?.rejected || 0),\n",
  "        },\n",
  "        {\n",
  "          label: \"Case\",\n",
  "          value: summary.cases?.created || 0,\n",
  "          desc: \"归档事件 \" + (summary.cases?.archivedEvents || 0) + \" · 未成 Case \" + (summary.cases?.nonCaseEvents || 0),\n",
  "        },\n",
  "        {\n",
  "          label: \"知识动作\",\n",
  "          value: summary.knowledge?.decisions || 0,\n",
  "          desc: \"新增 \" + (summary.knowledge?.published || 0) + \" · 更新 \" + (summary.knowledge?.updatedExisting || 0) + \" · 拒绝 \" + (summary.knowledge?.rejected || 0) + \" · 当前待审 \" + (summary.knowledge?.pendingNow || 0),\n",
  "        },\n",
  "        {\n",
  "          label: \"Agent\",\n",
  "          value: summary.agent?.finished || 0,\n",
  "          desc: \"完成 \" + (summary.agent?.completed || 0) + \" · 已发出 \" + (summary.agent?.replied || 0) + \" · 失败 \" + (summary.agent?.failed || 0) + \" · 忽略 \" + (summary.agent?.ignored || 0),\n",
  "        },\n",
  "      ];\n",
  "      const notes = Array.isArray(summary.healthNotes) ? summary.healthNotes : [];\n",
  "      return `\n",
  "        <div class=\"flow-summary\">\n",
  "          <div class=\"daily-notes\">\n",
  "            ${notes.map((item) => `<span class=\"chip\">${escapeHtml(item)}</span>`).join(\"\")}\n",
  "          </div>\n",
  "        </div>\n",
  "        <div class=\"daily-grid\">\n",
  "          ${cards.map((item) => `\n",
  "            <div class=\"daily-card\">\n",
  "              <div class=\"label\">${escapeHtml(item.label)}</div>\n",
  "              <div class=\"value\">${escapeHtml(item.value)}</div>\n",
  "              <div class=\"desc\">${escapeHtml(item.desc)}</div>\n",
  "            </div>\n",
  "          `).join(\"\")}\n",
  "        </div>\n",
  "      `;\n",
  "    }\n",
  "\n",
  "    function renderStats(progress, scope, agentOverview, needsAttention, dailySummary) {\n",
  "      const flowItems = [\n",
  "        { label: \"收到回调\", value: progress.callbackTotal },\n",
  "        { label: \"标准化\", value: progress.normalizedTotal },\n",
  "        { label: \"待处理\", value: Number(progress.pendingTotal || 0) + Number(progress.processingTotal || 0) },\n",
  "        { label: \"归档线索\", value: progress.candidateThreadTotal },\n",
  "        { label: \"正式 Case\", value: progress.caseTotal },\n",
  "        { label: \"知识候选\", value: progress.knowledgePendingReviewTotal },\n",
  "      ];\n",
  "      let currentIndex = 0;\n",
  "      for (let index = 0; index < flowItems.length; index += 1) {\n",
  "        if (Number(flowItems[index].value || 0) > 0) {\n",
  "          currentIndex = index;\n",
  "        }\n",
  "      }\n",
  "      const currentLabel = flowItems[currentIndex]?.label || \"收到回调\";\n",
  "      const nextLabel = flowItems[currentIndex + 1]?.label || \"流程完成\";\n",
  "      const flowParts = [];\n",
  "      flowItems.forEach((item, index) => {\n",
  "        const stateClass = index < currentIndex ? \"done\" : (index === currentIndex ? \"current\" : \"pending\");\n",
  "        flowParts.push(`\n",
  "        <div class=\"pipeline-node ${stateClass}\">\n",
  "          <div class=\"pipeline-index\">${index + 1}</div>\n",
  "          <div class=\"pipeline-label\">${escapeHtml(item.label)}</div>\n",
  "          <div class=\"pipeline-value\">${escapeHtml(item.value)}</div>\n",
  "        </div>\n",
  "      `);\n",
  "        if (index < flowItems.length - 1) {\n",
  "          const connectorClass = index <= currentIndex ? \"pipeline-connector active\" : \"pipeline-connector\";\n",
  "          flowParts.push(`<div class=\"${connectorClass}\" aria-hidden=\"true\"></div>`);\n",
  "        }\n",
  "      });\n",
  "      const flowHtml = flowParts.join(\"\");\n",
  "      document.getElementById(\"stats\").innerHTML = `\n",
  "        ${renderNeedsAttention(needsAttention)}\n",
  "        <div class=\"pipeline\">${flowHtml}</div>\n",
  "      `;\n",
  "    }\n",
  "\n",
  "    function renderBreakdown(id, items, emptyText) {\n",
  "      const root = document.getElementById(id);\n",
  "      if (!items.length) {\n",
  "        root.innerHTML = '<div class=\"empty\">' + escapeHtml(emptyText) + '</div>';\n",
  "        return;\n",
  "      }\n",
  "      root.innerHTML = items.map((item) => `\n",
  "        <div class=\"breakdown-row\">\n",
  "          <span>${escapeHtml(item.label)}</span>\n",
  "          <strong>${escapeHtml(item.count)}</strong>\n",
  "        </div>\n",
  "      `).join(\"\");\n",
  "    }\n",
];
