"use strict";

module.exports = [
  "        </section>\n",
  "\n",
  "        <section class=\"panel\">\n",
  "          <h2>标准化后的消息</h2>\n",
  "          <p class=\"hint\">这一步是把第三方回调整理成统一结构，便于后面做聚合、分类、case 识别和归档。</p>\n",
  "          <div class=\"list\" id=\"normalized-list\"></div>\n",
  "        </section>\n",
  "\n",
  "        <section class=\"panel\">\n",
  "          <h2>待批处理消息</h2>\n",
  "          <p class=\"hint\">新消息先进入消息池，等待批处理扫描器统一分组、甄别和归档。这里会同时显示待处理和处理中状态。</p>\n",
  "          <div class=\"list\" id=\"pending-list\"></div>\n",
  "        </section>\n",
  "\n",
  "        <section class=\"panel\">\n",
  "          <h2>已扫描并处理</h2>\n",
  "          <p class=\"hint\">这些数据已经进入“分类/归档判定”阶段。你可以看到它当前是被跳过、留在候选 thread，还是已经归档并进 case。</p>\n",
  "          <div class=\"list\" id=\"processed-list\"></div>\n",
  "        </section>\n",
  "      </div>\n",
  "\n",
  "      <div class=\"col\">\n",
  "        <section class=\"panel\">\n",
  "          <h2>知识矫正审核</h2>\n",
  "          <div class=\"knowledge-kpis\" id=\"knowledge-kpis\"></div>\n",
  "          <div class=\"config-actions\" style=\"margin-bottom: 12px;\">\n",
  "            <button class=\"action-btn\" id=\"process-knowledge-now\" type=\"button\">立即扫描知识</button>\n",
  "            <button class=\"action-btn primary\" id=\"open-knowledge-governance\" type=\"button\">去知识矫正审核</button>\n",
  "          </div>\n",
  "          <div class=\"muted\" id=\"knowledge-scan-flash\" style=\"margin-bottom: 12px;\">等待扫描</div>\n",
  "        </section>\n",
  "\n",
  "        <section class=\"panel\">\n",
  "          <h2>已归纳为 Case</h2>\n",
  "          <p class=\"hint\">正式 case 会显示摘要、优先级、参与人、消息数和对应的 case id。</p>\n",
  "          <div class=\"list\" id=\"case-list\"></div>\n",
  "        </section>\n",
  "\n",
  "        <section class=\"panel\">\n",
  "          <h2>未归纳成 Case 的数据</h2>\n",
  "          <p class=\"hint\">这里会把没有变成 case 的项目拆开说明，例如：未命中三类业务、仍是候选 thread、证据不足等。</p>\n",
  "          <div class=\"list\" id=\"non-case-list\"></div>\n",
  "        </section>\n",
  "\n",
  "        <section class=\"panel\">\n",
  "          <h2>候选 Thread 与当前进度</h2>\n",
  "          <p class=\"hint\">这部分主要看哪些内容已经进入候选 thread，但还没升级为 case。</p>\n",
  "          <div class=\"list\" id=\"thread-list\"></div>\n",
  "        </section>\n",
  "\n",
  "        <section class=\"panel\">\n",
  "          <h2>过滤拦截摘要</h2>\n",
  "          <p class=\"hint\">不展开噪音原文，只显示最近一批被过滤掉的原因分布，方便确认入口规则是否过严。</p>\n",
  "          <div class=\"breakdown\" id=\"ignored-reasons\"></div>\n",
  "        </section>\n",
  "      </div>\n",
  "    </div>\n",
  "  </div>\n",
  "\n",
  "  <script>\n",
  "    const LIMIT = __FLOWBOT_DASHBOARD_DEFAULT_LIMIT__;\n",
  "    const CATEGORY_LABELS = __FLOWBOT_JSON_CATEGORY_LABELS__;\n",
  "    const THREAD_TYPE_LABELS = __FLOWBOT_JSON_THREAD_TYPE_LABELS__;\n",
  "    const MESSAGE_ROLE_LABELS = __FLOWBOT_JSON_MESSAGE_ROLE_LABELS__;\n",
  "    const BATCH_ACTION_LABELS = __FLOWBOT_JSON_BATCH_ACTION_LABELS__;\n",
  "    const CASE_STATUS_LABELS = __FLOWBOT_JSON_CASE_STATUS_LABELS__;\n",
  "    const LOGIN_REGION_OPTIONS = __FLOWBOT_JSON_LOGIN_REGION_OPTIONS__;\n",
  "    const DEFAULT_LOGIN_REGION = __FLOWBOT_JSON_DEFAULT_LOGIN_REGION__;\n",
  "    const DEFAULT_NOTIFY_URL = __FLOWBOT_JSON_DEFAULT_NOTIFY_URL__;\n",
  "    const LOGIN_BRIDGE_STORAGE_KEY = \"flowbot-upstream-login-bridge\";\n",
  "    const roomSelector = document.getElementById(\"room-selector\");\n",
  "    const processPendingButton = document.getElementById(\"process-pending-now\");\n",
  "    const processKnowledgeButton = document.getElementById(\"process-knowledge-now\");\n",
  "    const refreshNowButton = document.getElementById(\"refresh-now\");\n",
  "    const dashboardDetailRefreshButton = document.getElementById(\"dashboard-detail-refresh\");\n",
  "    const roomCompactSessionButton = document.getElementById(\"room-compact-session\");\n",
  "    const roomCleanNoiseButton = document.getElementById(\"room-clean-noise\");\n",
  "    const roomClearSessionButton = document.getElementById(\"room-clear-session\");\n",
  "    const roomClearMemoryButton = document.getElementById(\"room-clear-memory\");\n",
  "    const roomClearArchiveButton = document.getElementById(\"room-clear-archive\");\n",
  "    const roomActionFlash = document.getElementById(\"meta-room-action\");\n",
  "    const roomSearchInput = document.getElementById(\"room-search\");\n",
  "    const roomListRoot = document.getElementById(\"room-list\");\n",
  "    const roomListRefreshButton = document.getElementById(\"room-list-refresh\");\n",
  "    const roomListProcessButton = document.getElementById(\"room-list-process\");\n",
  "    const roomListKnowledgeButton = document.getElementById(\"room-list-knowledge\");\n",
  "    const roomListCleanNoiseButton = document.getElementById(\"room-list-clean-noise\");\n",
  "    const roomListCompactButton = document.getElementById(\"room-list-compact\");\n",
  "    const roomListClearSessionButton = document.getElementById(\"room-list-clear-session\");\n",
  "    const roomListClearMemoryButton = document.getElementById(\"room-list-clear-memory\");\n",
  "    const roomListClearArchiveButton = document.getElementById(\"room-list-clear-archive\");\n",
  "    const dashboardListPage = document.getElementById(\"dashboard-list-page\");\n",
  "    const dashboardDetailPage = document.getElementById(\"dashboard-detail-page\");\n",
  "    const dashboardListBody = document.getElementById(\"dashboard-list-body\");\n",
  "    const dashboardListSearch = document.getElementById(\"dashboard-list-search\");\n",
  "    const dashboardListStatus = document.getElementById(\"dashboard-list-status\");\n",
  "    const dashboardListRefresh = document.getElementById(\"dashboard-list-refresh\");\n",
  "    const dashboardListPrev = document.getElementById(\"dashboard-list-prev\");\n",
  "    const dashboardListNext = document.getElementById(\"dashboard-list-next\");\n",
  "    const dashboardListPageInfo = document.getElementById(\"dashboard-list-page-info\");\n",
  "    const openDashboardSettingsSystemButton = document.getElementById(\"open-dashboard-settings-system\");\n",
  "    const openDashboardSettingsLoginButton = document.getElementById(\"open-dashboard-settings-login\");\n",
  "    const backToDashboardList = document.getElementById(\"back-to-dashboard-list\");\n",
  "    const dashboardSettingsPage = document.getElementById(\"dashboard-settings-page\");\n",
  "    const configForm = document.getElementById(\"config-form\");\n",
  "    const configFlash = document.getElementById(\"config-flash\");\n",
  "    const configTestButton = document.getElementById(\"config-test\");\n",
  "    const configRagflowRefreshButton = document.getElementById(\"config-ragflow-refresh\");\n",
  "    const configRagflowStatus = document.getElementById(\"config-ragflow-status\");\n",
  "    const loginForm = document.getElementById(\"wecom-login-form\");\n",
  "    const loginStartButton = document.getElementById(\"login-start\");\n",
  "    const loginOpenProviderButton = document.getElementById(\"login-open-provider\");\n",
  "    const loginSetNotifyButton = document.getElementById(\"login-set-notify\");\n",
  "    const loginVerifyButton = document.getElementById(\"login-verify\");\n",
  "    const loginFlash = document.getElementById(\"login-flash\");\n",
  "    const loginStatus = document.getElementById(\"login-status\");\n",
  "    const knowledgeFlash = document.getElementById(\"knowledge-scan-flash\");\n",
  "    const loginQrcodeBox = document.getElementById(\"login-qrcode-box\");\n",
  "    const loginMetaGrid = document.getElementById(\"login-meta-grid\");\n",
  "    const loginRegionSelect = document.getElementById(\"login-region-select\");\n",
  "    const loginRegionInput = document.getElementById(\"login-region\");\n",
  "    const loginProxyRawInput = document.getElementById(\"login-proxy-raw\");\n",
  "    const openKnowledgeGovernanceButton = document.getElementById(\"open-knowledge-governance\");\n",
  "    const initialParams = new URLSearchParams(window.location.search);\n",
  "    const initialView = initialParams.get(\"view\");\n",
  "    let currentSettingsTab = initialParams.get(\"settingsTab\") === \"login\" ? \"login\" : \"system\";\n",
  "    let dashboardView = initialView === \"detail\" || initialView === \"settings\" ? initialView : \"list\";\n",
  "    let selectedRoomId = dashboardView === \"detail\" ? (initialParams.get(\"roomId\") || \"\") : \"\";\n",
  "    let configBusy = false;\n",
  "    let loginBusy = false;\n",
  "    let roomActionBusy = false;\n",
  "    let roomActionFlashSticky = false;\n",
  "    let knowledgeScanBusy = false;\n",
  "    let lastRooms = [];\n",
  "    let lastScope = null;\n",
  "    let currentWecomGuid = \"\";\n",
  "    let roomNameLookupBusy = false;\n",
  "    const roomNameCache = new Map();\n",
  "    let dashboardListPageNo = 1;\n",
  "    const DASHBOARD_LIST_PAGE_SIZE = 12;\n",
  "\n",
  "    function buildEndpoint() {\n",
  "      const params = new URLSearchParams();\n",
  "      params.set(\"limit\", dashboardView === \"list\" ? \"1\" : String(LIMIT));\n",
  "      if (dashboardView === \"detail\" && selectedRoomId) {\n",
  "        params.set(\"roomId\", selectedRoomId);\n",
  "      }\n",
  "      return \"/flowbot/dashboard/data?\" + params.toString();\n",
  "    }\n",
  "\n",
  "    function setConfigFlash(message, tone = \"normal\") {\n",
  "      if (!configFlash) {\n",
  "        return;\n",
  "      }\n",
  "      configFlash.textContent = message;\n",
  "      configFlash.style.color = tone === \"error\"\n",
  "        ? \"var(--danger)\"\n",
  "        : (tone === \"ok\" ? \"var(--ok)\" : \"var(--muted)\");\n",
  "    }\n",
  "\n",
  "    function setKnowledgeFlash(message, tone = \"normal\") {\n",
  "      if (!knowledgeFlash) {\n",
  "        return;\n",
  "      }\n",
  "      knowledgeFlash.textContent = message;\n",
  "      knowledgeFlash.style.color = tone === \"error\"\n",
  "        ? \"var(--danger)\"\n",
  "        : (tone === \"ok\" ? \"var(--ok)\" : \"var(--muted)\");\n",
  "    }\n",
  "\n",
  "    function setLoginFlash(message, tone = \"normal\") {\n",
  "      if (!loginFlash) {\n",
  "        return;\n",
  "      }\n",
  "      loginFlash.textContent = message;\n",
  "      loginFlash.style.color = tone === \"error\"\n",
  "        ? \"var(--danger)\"\n",
  "        : (tone === \"ok\" ? \"var(--ok)\" : \"var(--muted)\");\n",
  "    }\n",
  "\n",
  "    function setRoomActionFlash(message, tone = \"normal\", { sticky = false, resetSticky = false } = {}) {\n",
  "      if (!roomActionFlash) {\n",
  "        return;\n",
  "      }\n",
  "      if (resetSticky) {\n",
  "        roomActionFlashSticky = false;\n",
  "      }\n",
  "      if (sticky) {\n",
  "        roomActionFlashSticky = true;\n",
  "      }\n",
  "      roomActionFlash.textContent = message;\n",
  "      roomActionFlash.style.color = tone === \"error\"\n",
  "        ? \"var(--danger)\"\n",
  "        : (tone === \"ok\" ? \"var(--ok)\" : \"var(--muted)\");\n",
  "    }\n",
  "\n",
  "    function updateRoomActionButtons() {\n",
  "      const disabled = roomActionBusy || !selectedRoomId;\n",
  "      [roomCompactSessionButton, roomClearSessionButton, roomClearMemoryButton, roomClearArchiveButton]\n",
  "        .filter(Boolean)\n",
  "        .forEach((button) => {\n",
  "          button.disabled = disabled;\n",
  "        });\n",
  "      if (roomCleanNoiseButton) {\n",
  "        roomCleanNoiseButton.disabled = roomActionBusy;\n",
  "      }\n",
  "      if (!selectedRoomId) {\n",
  "        setRoomActionFlash(\"房间操作：请选择一个群\", \"normal\", { resetSticky: true });\n",
  "      } else if (!roomActionBusy && !roomActionFlashSticky) {\n",
  "        setRoomActionFlash(\"房间操作：将作用于当前选中的群\");\n",
  "      }\n",
  "    }\n",
  "\n",
  "    async function performRoomAction(action, confirmText, pendingText, successText) {\n",
  "      const allowAllScope = action === \"cleanup_noise\";\n",
  "      if (!selectedRoomId && !allowAllScope) {\n",
  "        setRoomActionFlash(\"请先选择一个群\", \"error\");\n",
  "        return;\n",
  "      }\n",
  "      if (roomActionBusy) {\n",
  "        return;\n",
  "      }\n",
  "      if (confirmText && !window.confirm(confirmText)) {\n",
  "        return;\n",
  "      }\n",
  "      roomActionBusy = true;\n",
  "      updateRoomActionButtons();\n",
  "      setRoomActionFlash(pendingText, \"normal\", { sticky: true });\n",
  "      try {\n",
  "        const response = await fetch(\"/flowbot/dashboard/room-action\", {\n",
  "          method: \"POST\",\n",
  "          headers: {\n",
  "            \"Content-Type\": \"application/json\",\n",
  "          },\n",
  "          body: JSON.stringify({\n",
  "            roomId: selectedRoomId || \"__all__\",\n",
  "            action,\n",
  "          }),\n",
  "        });\n",
  "        const data = await response.json();\n",
  "        if (!data.ok) {\n",
  "          throw new Error(data.error || \"room_action_failed\");\n",
  "        }\n",
  "        setRoomActionFlash(successText + \"：\" + JSON.stringify(data.result || {}), \"ok\", { sticky: true });\n",
  "        await load(true);\n",
  "      } catch (error) {\n",
  "        setRoomActionFlash(\"操作失败：\" + String(error?.message || error), \"error\", { sticky: true });\n",
  "      } finally {\n",
  "        roomActionBusy = false;\n",
  "        updateRoomActionButtons();\n",
  "      }\n",
  "    }\n",
  "\n",
  "    function renderLoginRegions() {\n",
  "      if (!loginRegionSelect || !loginRegionInput) {\n",
  "        return;\n",
  "      }\n",
  "      loginRegionSelect.innerHTML = LOGIN_REGION_OPTIONS.map((item) => (\n",
  "        '<option value=\"' + escapeHtml(item.value) + '\">' + escapeHtml(item.label + ' (' + item.value + ')') + '</option>'\n",
  "      )).join(\"\");\n",
  "      loginRegionSelect.value = DEFAULT_LOGIN_REGION;\n",
  "      loginRegionInput.value = DEFAULT_LOGIN_REGION;\n",
  "    }\n",
  "\n",
  "    function getLoginPayload() {\n",
  "      return {\n",
  "        guid: document.getElementById(\"login-guid\").value.trim(),\n",
  "        region: loginRegionInput.value.trim() || loginRegionSelect.value || DEFAULT_LOGIN_REGION,\n",
  "        proxy: document.getElementById(\"login-proxy\").value.trim(),\n",
  "        proxyFetchResult: loginProxyRawInput ? loginProxyRawInput.value.trim() : \"\",\n",
  "        notifyUrl: document.getElementById(\"login-notify-url\").value.trim() || DEFAULT_NOTIFY_URL,\n",
  "        code: document.getElementById(\"login-code\").value.trim(),\n",
  "      };\n",
  "    }\n",
  "\n",
  "    function buildLoginProviderUrl() {\n",
  "      const region = loginRegionInput.value.trim() || loginRegionSelect.value || DEFAULT_LOGIN_REGION;\n",
  "      const base = \"http://api.tianqiip.com/getip\";\n",
  "      const target = new URL(base);\n",
  "      target.searchParams.set(\"mr\", \"1\");\n",
  "      target.searchParams.set(\"num\", \"1\");\n",
  "      target.searchParams.set(\"port\", \"3\");\n",
  "      target.searchParams.set(\"region\", region);\n",
  "      target.searchParams.set(\"secret\", \"2schw4v5\");\n",
  "      target.searchParams.set(\"sign\", \"1ed82290cb7b764ac17f1b5104d90989\");\n",
  "      target.searchParams.set(\"time\", \"3\");\n",
  "      target.searchParams.set(\"type\", \"json\");\n",
  "      return target.toString();\n",
  "    }\n",
  "\n",
  "    async function fetchLoginProviderResult() {\n",
  "      const region = loginRegionInput.value.trim() || loginRegionSelect.value || DEFAULT_LOGIN_REGION;\n",
  "      const target = new URL(\"/flowbot/wecom-login/proxy-provider\", window.location.origin);\n",
  "      target.searchParams.set(\"region\", region);\n",
  "      const response = await fetch(target.toString(), { cache: \"no-store\" });\n",
  "      const data = await response.json();\n",
  "      if (!data.ok) {\n",
  "        throw new Error(data.error || \"proxy_provider_failed\");\n",
  "      }\n",
  "      const proxyInput = document.getElementById(\"login-proxy\");\n",
  "      if (proxyInput && data.proxy) {\n",
  "        proxyInput.value = data.proxy;\n",
  "      }\n",
  "      if (loginProxyRawInput) {\n",
  "        loginProxyRawInput.value = \"\";\n",
  "      }\n",
  "      renderLoginStatus(\"已获取公司代理\", [data.proxy || \"已填入代理地址\"], \"ok\");\n",
  "      setLoginFlash(\"已获取代理结果，可以直接开始登录。\", \"ok\");\n",
  "    }\n",
  "\n",
  "    function consumePendingLoginBridge() {\n",
  "      try {\n",
  "        const raw = window.localStorage.getItem(LOGIN_BRIDGE_STORAGE_KEY);\n",
  "        if (!raw) {\n",
  "          return null;\n",
  "        }\n",
  "        window.localStorage.removeItem(LOGIN_BRIDGE_STORAGE_KEY);\n",
  "        const parsed = JSON.parse(raw);\n",
  "        if (!parsed || typeof parsed !== \"object\") {\n",
  "          return null;\n",
  "        }\n",
  "        return parsed;\n",
  "      } catch {\n",
  "        return null;\n",
  "      }\n",
  "    }\n",
  "\n",
  "    function applyPendingLoginBridge(pending) {\n",
  "      if (!pending) {\n",
  "        return;\n",
  "      }\n",
  "      if (pending.guid) {\n",
  "        document.getElementById(\"login-guid\").value = pending.guid;\n",
  "      }\n",
  "      if (pending.region) {\n",
  "        loginRegionInput.value = pending.region;\n",
  "        if (loginRegionSelect) {\n",
  "          loginRegionSelect.value = pending.region;\n",
  "        }\n",
  "      }\n",
  "      if (pending.notifyUrl) {\n",
  "        document.getElementById(\"login-notify-url\").value = pending.notifyUrl;\n",
  "      }\n",
  "      if (pending.proxyFetchResult && loginProxyRawInput) {\n",
  "        loginProxyRawInput.value = pending.proxyFetchResult;\n",
  "      }\n",
  "      setLoginFlash(\"已带回代理结果，可以直接继续登录。\", \"ok\");\n",
  "    }\n",
  "\n",
  "    function renderLoginMeta(cards) {\n",
  "      if (!loginMetaGrid) {\n",
  "        return;\n",
  "      }\n",
  "      if (!cards.length) {\n",
  "        loginMetaGrid.innerHTML = \"\";\n",
  "        return;\n",
  "      }\n",
  "      loginMetaGrid.innerHTML = cards.map((item) => (\n",
  "        '<div class=\"login-meta-card\">'\n",
  "        + '<div class=\"label\">' + escapeHtml(item.label) + '</div>'\n",
  "        + '<div class=\"value\">' + escapeHtml(item.value) + '</div>'\n",
  "        + '</div>'\n",
  "      )).join(\"\");\n",
  "    }\n",
  "\n",
  "    function renderLoginQrcode(data) {\n",
  "      if (!loginQrcodeBox) {\n",
  "        return;\n",
  "      }\n",
  "      const dataUri = data?.qrcodeDataUri || \"\";\n",
  "      if (!dataUri) {\n",
  "        loginQrcodeBox.innerHTML = '<div class=\"muted\">当前响应里没有二维码图片。</div>';\n",
  "        return;\n",
  "      }\n",
  "      loginQrcodeBox.innerHTML =\n",
  "        '<div>'\n",
  "        + '<img src=\"' + escapeHtml(dataUri) + '\" alt=\"企微登录二维码\">'\n",
  "        + '<div class=\"muted\" style=\"margin-top: 10px;\">请直接扫码登录；若扫码后提示验证码，再在上方输入验证码并点击“提交验证码”。</div>'\n",
  "        + '</div>';\n",
  "    }\n",
  "\n",
  "    function renderLoginStatus(title, lines, tone = \"normal\") {\n",
  "      if (!loginStatus) {\n",
  "        return;\n",
  "      }\n",
  "      const color = tone === \"error\" ? \"var(--danger)\" : (tone === \"ok\" ? \"var(--ok)\" : \"var(--muted)\");\n",
  "      loginStatus.innerHTML =\n",
  "        '<strong>' + escapeHtml(title) + '</strong>'\n",
  "        + lines.map((line) => (\n",
  "          '<div class=\"muted\" style=\"color: ' + color + ';\">' + escapeHtml(line) + '</div>'\n",
  "        )).join(\"\");\n",
  "    }\n",
  "\n",
  "    function renderLoginStartResult(data) {\n",
  "      renderLoginQrcode(data);\n",
  "      renderLoginMeta([\n",
  "        { label: \"GUID\", value: data?.guid || \"-\" },\n",
  "        { label: \"地区\", value: data?.region || \"-\" },\n",
  "        { label: \"代理来源\", value: data?.proxyInfo?.source === \"manual\" ? \"手动填写\" : \"自动获取\" },\n",
  "        { label: \"代理\", value: data?.proxyInfo?.proxy || \"-\" },\n",
  "        { label: \"回调地址\", value: data?.notifyUrl || document.getElementById(\"login-notify-url\").value || \"-\" },\n",
  "        { label: \"回调写入\", value: Number(data?.notifyResponse?.error_code) === 0 ? \"已写入三方实例\" : \"未确认\" },\n",
  "        { label: \"二维码 Key\", value: data?.qrcodeKey || \"-\" },\n",
  "      ]);\n",
  "      renderLoginStatus(\"登录流程已启动\", [\n",
  "        \"页面里的回调地址已先写入三方实例，随后已设置代理并获取二维码。\",\n",
  "        \"如果扫码后需要验证码，请在上方填写后提交。\",\n",
  "      ], \"ok\");\n",
  "    }\n",
  "\n",
  "    async function submitLoginStart(event) {\n",
  "      event.preventDefault();\n",
  "      if (loginBusy) {\n",
  "        return;\n",
  "      }\n",
  "      const payload = getLoginPayload();\n",
  "      if (!payload.guid) {\n",
  "        setLoginFlash(\"请先填写 GUID\", \"error\");\n",
  "        renderLoginStatus(\"登录流程未开始\", [\"缺少 GUID\"], \"error\");\n",
  "        return;\n",
  "      }\n",
  "      if (!payload.notifyUrl) {\n",
  "        setLoginFlash(\"请先填写回调地址\", \"error\");\n",
  "        renderLoginStatus(\"登录流程未开始\", [\"缺少回调地址\"], \"error\");\n",
  "        return;\n",
  "      }\n",
  "      loginBusy = true;\n",
  "      loginStartButton.disabled = true;\n",
  "      loginOpenProviderButton.disabled = true;\n",
  "      loginSetNotifyButton.disabled = true;\n",
  "      loginVerifyButton.disabled = true;\n",
  "      setLoginFlash(\"正在获取代理并生成二维码...\");\n",
  "      try {\n",
  "        const response = await fetch(\"/flowbot/wecom-login/start\", {\n",
  "          method: \"POST\",\n",
  "          headers: {\n",
  "            \"Content-Type\": \"application/json\",\n",
  "          },\n",
  "          body: JSON.stringify({\n",
  "            guid: payload.guid,\n",
  "            region: payload.region,\n",
  "            proxy: payload.proxy,\n",
  "            proxyFetchResult: payload.proxyFetchResult,\n",
  "            notifyUrl: payload.notifyUrl,\n",
  "          }),\n",
  "        });\n",
  "        const data = await response.json();\n",
  "        if (!data.ok) {\n",
  "          throw new Error(data.error || \"login_start_failed\");\n",
  "        }\n",
  "        renderLoginStartResult(data);\n",
  "        setLoginFlash(\"二维码已生成\", \"ok\");\n",
  "      } catch (error) {\n",
  "        renderLoginStatus(\"登录流程失败\", [String(error?.message || error)], \"error\");\n",
  "        setLoginFlash(\"登录失败：\" + String(error?.message || error), \"error\");\n",
  "      } finally {\n",
  "        loginBusy = false;\n",
  "        loginStartButton.disabled = false;\n",
  "        loginOpenProviderButton.disabled = false;\n",
  "        loginSetNotifyButton.disabled = false;\n",
  "        loginVerifyButton.disabled = false;\n",
  "      }\n",
  "    }\n",
  "\n",
  "    async function submitLoginVerify() {\n",
  "      if (loginBusy) {\n",
  "        return;\n",
  "      }\n",
  "      const payload = getLoginPayload();\n",
  "      if (!payload.guid) {\n",
  "        setLoginFlash(\"请先填写 GUID\", \"error\");\n",
  "        renderLoginStatus(\"验证码提交失败\", [\"缺少 GUID\"], \"error\");\n",
  "        return;\n",
  "      }\n",
  "      if (!payload.code) {\n",
  "        setLoginFlash(\"请填写验证码\", \"error\");\n",
  "        renderLoginStatus(\"验证码提交失败\", [\"缺少验证码\"], \"error\");\n",
  "        return;\n",
  "      }\n",
  "      loginBusy = true;\n",
  "      loginStartButton.disabled = true;\n",
  "      loginOpenProviderButton.disabled = true;\n",
  "      loginSetNotifyButton.disabled = true;\n",
  "      loginVerifyButton.disabled = true;\n",
  "      setLoginFlash(\"正在提交验证码...\");\n",
  "      try {\n",
  "        const response = await fetch(\"/flowbot/wecom-login/verify\", {\n",
  "          method: \"POST\",\n",
  "          headers: {\n",
  "            \"Content-Type\": \"application/json\",\n",
  "          },\n",
  "          body: JSON.stringify({\n",
  "            guid: payload.guid,\n",
  "            code: payload.code,\n",
  "          }),\n",
  "        });\n",
  "        const data = await response.json();\n",
  "        if (!data.ok) {\n",
  "          throw new Error(data.error || \"login_verify_failed\");\n",
  "        }\n",
  "        renderLoginStatus(\"验证码已提交\", [\n",
  "          \"验证码提交请求已发送到上游实例。\",\n",
  "          JSON.stringify(data.verifyResponse || {}),\n",
  "        ], \"ok\");\n",
  "        setLoginFlash(\"验证码提交成功\", \"ok\");\n",
  "      } catch (error) {\n",
  "        renderLoginStatus(\"验证码提交失败\", [String(error?.message || error)], \"error\");\n",
  "        setLoginFlash(\"验证码提交失败：\" + String(error?.message || error), \"error\");\n",
  "      } finally {\n",
  "        loginBusy = false;\n",
  "        loginStartButton.disabled = false;\n",
  "        loginOpenProviderButton.disabled = false;\n",
  "        loginSetNotifyButton.disabled = false;\n",
  "        loginVerifyButton.disabled = false;\n",
  "      }\n",
  "    }\n",
  "\n",
  "    async function submitLoginSetNotify() {\n",
  "      if (loginBusy) {\n",
  "        return;\n",
  "      }\n",
  "      const payload = getLoginPayload();\n",
  "      if (!payload.guid) {\n",
  "        setLoginFlash(\"请先填写 GUID\", \"error\");\n",
  "        renderLoginStatus(\"设置回调地址失败\", [\"缺少 GUID\"], \"error\");\n",
  "        return;\n",
  "      }\n",
  "      if (!payload.notifyUrl) {\n",
  "        setLoginFlash(\"请先填写回调地址\", \"error\");\n",
  "        renderLoginStatus(\"设置回调地址失败\", [\"缺少回调地址\"], \"error\");\n",
  "        return;\n",
  "      }\n",
  "      loginBusy = true;\n",
  "      loginStartButton.disabled = true;\n",
  "      loginOpenProviderButton.disabled = true;\n",
  "      loginSetNotifyButton.disabled = true;\n",
  "      loginVerifyButton.disabled = true;\n",
  "      setLoginFlash(\"正在设置回调地址...\");\n",
  "      try {\n",
  "        const response = await fetch(\"/flowbot/wecom-login/set-notify\", {\n",
  "          method: \"POST\",\n",
  "          headers: {\n",
  "            \"Content-Type\": \"application/json\",\n",
  "          },\n",
  "          body: JSON.stringify({\n",
  "            guid: payload.guid,\n",
  "            notifyUrl: payload.notifyUrl,\n",
  "          }),\n",
  "        });\n",
  "        const data = await response.json();\n",
  "        if (!data.ok) {\n",
  "          throw new Error(data.error || \"set_notify_failed\");\n",
  "        }\n",
  "        renderLoginStatus(\"回调地址已设置\", [\n",
  "          \"上游实例已写入新的回调地址。\",\n",
  "          payload.notifyUrl,\n",
  "        ], \"ok\");\n",
  "        setLoginFlash(\"回调地址设置成功\", \"ok\");\n",
  "      } catch (error) {\n",
  "        renderLoginStatus(\"设置回调地址失败\", [String(error?.message || error)], \"error\");\n",
  "        setLoginFlash(\"设置回调地址失败：\" + String(error?.message || error), \"error\");\n",
  "      } finally {\n",
  "        loginBusy = false;\n",
  "        loginStartButton.disabled = false;\n",
  "        loginOpenProviderButton.disabled = false;\n",
  "        loginSetNotifyButton.disabled = false;\n",
  "        loginVerifyButton.disabled = false;\n",
  "      }\n",
  "    }\n",
  "\n",
  "    function parseMysqlUrl(value) {\n",
  "      const text = String(value || \"\").trim();\n",
  "      if (!text) return {};\n",
  "      try {\n",
  "        const parsed = new URL(text.includes(\"://\") ? text : \"mysql://\" + text);\n",
  "        return {\n",
  "          mysqlHost: parsed.hostname || \"127.0.0.1\",\n",
  "          mysqlPort: parsed.port || \"3306\",\n",
  "          mysqlDatabase: decodeURIComponent(parsed.pathname.replace(/^\\//, \"\")),\n",
  "          mysqlUser: decodeURIComponent(parsed.username || \"\"),\n",
  "          mysqlPassword: parsed.password ? decodeURIComponent(parsed.password) : document.getElementById(\"cfg-mysql-password\")?.value || \"\",\n",
  "          mysqlBin: \"mysql\",\n",
  "        };\n",
  "      } catch {\n",
  "        return {};\n",
  "      }\n",
  "    }\n",
  "\n",
  "    function buildMysqlUrl(config) {\n",
  "      const host = config.mysqlHost || \"127.0.0.1\";\n",
  "      const port = config.mysqlPort || 3306;\n",
  "      const user = encodeURIComponent(config.mysqlUser || \"flowbot_app\");\n",
  "      const database = encodeURIComponent(config.mysqlDatabase || \"flowbot_runtime\");\n",
  "      return `mysql://${user}@${host}:${port}/${database}`;\n",
  "    }\n",
  "\n",
  "    async function loadRagflowChats(selectedId = \"\") {\n",
  "      const select = document.getElementById(\"cfg-ragflow-chat-id\");\n",
  "      if (!select) return;\n",
  "      if (configRagflowStatus) configRagflowStatus.textContent = \"正在加载...\";\n",
  "      const response = await fetch(\"/flowbot/config/ragflow-chats\", { cache: \"no-store\" });\n",
  "      const data = await response.json();\n",
  "      if (!data.ok) throw new Error(data.error || \"ragflow_chats_load_failed\");\n",
  "      const currentValue = selectedId || select.value || data.selectedBotId || \"\";\n",
  "      const options = [\"<option value=\\\"\\\">未选择，使用旧检索链路</option>\"];\n",
  "      for (const bot of data.bots || []) {\n",
  "        const label = [bot.name || bot.id, (bot.kbNames || []).join(\" / \")].filter(Boolean).join(\" - \");\n",
  "        options.push(\"<option value=\\\"\" + escapeHtml(bot.id) + \"\\\">\" + escapeHtml(label) + \"</option>\");\n",
  "      }\n",
  "      select.innerHTML = options.join(\"\");\n",
  "      select.value = currentValue;\n",
  "      if (configRagflowStatus) {\n",
  "        configRagflowStatus.textContent = data.enabled ? (\"已加载 \" + (data.bots || []).length + \" 个机器人\") : \"RAGFlow 未配置\";\n",
  "      }\n",
  "    }\n",
  "\n",
  "    function getConfigPayload() {\n",
  "      const targetRoomsField = document.getElementById(\"cfg-target-rooms\");\n",
  "      const feishuTargetChatsField = document.getElementById(\"cfg-feishu-target-chats\");\n",
  "      const knowledgeHarvestRoomsField = document.getElementById(\"cfg-knowledge-harvest-rooms\");\n",
  "      return {\n",
  "        targetRoomIds: targetRoomsField ? targetRoomsField.value : undefined,\n",
  "        feishuTargetChatIds: feishuTargetChatsField ? feishuTargetChatsField.value : undefined,\n",
  "        feishuAppId: document.getElementById(\"cfg-feishu-app-id\")?.value || \"\",\n",
  "        feishuAppSecret: document.getElementById(\"cfg-feishu-app-secret\")?.value || \"\",\n",
  "        feishuVerificationToken: document.getElementById(\"cfg-feishu-verification-token\")?.value || \"\",\n",
  "        feishuOauthRedirectUri: document.getElementById(\"cfg-feishu-oauth-redirect-uri\")?.value || \"\",\n",
  "        feishuOauthScope: document.getElementById(\"cfg-feishu-oauth-scope\")?.value || \"\",\n",
  "        archiveEnabled: document.getElementById(\"cfg-archive-enabled\").value,\n",
  "        caseArchiveNotifyEnabled: document.getElementById(\"cfg-case-archive-notify-enabled\").value,\n",
  "        agentWakeNames: document.getElementById(\"cfg-agent-wake-names\").value,\n",
  "        llmClassifyEnabled: document.getElementById(\"cfg-llm-enabled\").value,\n",
  "        llmApiUrl: document.getElementById(\"cfg-llm-url\").value,\n",
  "        llmModel: document.getElementById(\"cfg-llm-model\").value,\n",
  "        llmApiKey: document.getElementById(\"cfg-llm-key\").value,\n",
  "        llmTimeoutMs: document.getElementById(\"cfg-llm-timeout\").value,\n",
  "        llmMaxRepairAttempts: document.getElementById(\"cfg-llm-repair\").value,\n",
  "        imageSummaryEnabled: document.getElementById(\"cfg-image-summary-enabled\").value,\n",
  "        imageSummaryModel: document.getElementById(\"cfg-image-summary-model\").value,\n",
  "        imageSummaryTimeoutMs: document.getElementById(\"cfg-image-summary-timeout\").value,\n",
  "        transcribeEnabled: document.getElementById(\"cfg-transcribe-enabled\").value,\n",
  "        transcribeTimeoutMs: document.getElementById(\"cfg-transcribe-timeout\").value,\n",
  "        storageBackend: \"mysql\",\n",
  "        dataDir: document.getElementById(\"cfg-data-dir\").value,\n",
  "        ...parseMysqlUrl(document.getElementById(\"cfg-mysql-url\")?.value || \"\"),\n",
  "        mysqlAutoMigrate: \"1\",\n",
  "        knowledgeHarvestEnabled: document.getElementById(\"cfg-knowledge-harvest-enabled\").value,\n",
  "        knowledgeHarvestRoomIds: knowledgeHarvestRoomsField ? knowledgeHarvestRoomsField.value : undefined,\n",
  "        knowledgeHarvestReadyAgeMs: document.getElementById(\"cfg-knowledge-harvest-ready-age\").value,\n",
  "        knowledgeHarvestScanIntervalMs: document.getElementById(\"cfg-knowledge-harvest-interval\").value,\n",
  "        knowledgeHarvestMaxPerScan: document.getElementById(\"cfg-knowledge-harvest-max\").value,\n",
  "        ragflowChatId: document.getElementById(\"cfg-ragflow-chat-id\")?.value || \"\",\n",
  "      };\n",
  "    }\n",
  "\n",
  "    function applyConfigToForm(data) {\n",
  "      const config = data?.config || {};\n",
  "      const targetRoomsField = document.getElementById(\"cfg-target-rooms\");\n",
  "      const feishuTargetChatsField = document.getElementById(\"cfg-feishu-target-chats\");\n",
  "      const knowledgeHarvestRoomsField = document.getElementById(\"cfg-knowledge-harvest-rooms\");\n",
  "      if (targetRoomsField) {\n",
  "        targetRoomsField.value = String(config.targetRoomIds || \"\").replaceAll(\",\", \"\\n\");\n",
  "      }\n",
  "      if (feishuTargetChatsField) {\n",
  "        feishuTargetChatsField.value = String(config.feishuTargetChatIds || \"\").replaceAll(\",\", \"\\n\");\n",
  "      }\n",
  "      document.getElementById(\"cfg-feishu-app-id\").value = config.feishuAppId || \"\";\n",
  "      document.getElementById(\"cfg-feishu-oauth-redirect-uri\").value = config.feishuOauthRedirectUri || \"\";\n",
  "      document.getElementById(\"cfg-feishu-oauth-scope\").value = config.feishuOauthScope || \"\";\n",
  "      const feishuSecretInput = document.getElementById(\"cfg-feishu-app-secret\");\n",
  "      feishuSecretInput.value = \"\";\n",
  "      feishuSecretInput.placeholder = config.feishuAppSecretConfigured\n",
  "        ? (\"已配置：\" + (config.feishuAppSecretMasked || \"******\") + \"，留空则保持不变\")\n",
  "        : \"未配置；如需飞书回调和群回复请填写\";\n",
  "      const feishuTokenInput = document.getElementById(\"cfg-feishu-verification-token\");\n",
  "      feishuTokenInput.value = \"\";\n",
  "      feishuTokenInput.placeholder = config.feishuVerificationTokenConfigured\n",
  "        ? (\"已配置：\" + (config.feishuVerificationTokenMasked || \"******\") + \"，留空则保持不变\")\n",
  "        : \"未配置；飞书事件订阅校验用，可按需填写\";\n",
  "      if (knowledgeHarvestRoomsField) {\n",
  "        knowledgeHarvestRoomsField.value = String(config.knowledgeHarvestRoomIds || \"\").replaceAll(\",\", \"\\n\");\n",
  "      }\n",
  "      document.getElementById(\"cfg-archive-enabled\").value = config.archiveEnabled ? \"1\" : \"0\";\n",
  "      document.getElementById(\"cfg-case-archive-notify-enabled\").value = config.caseArchiveNotifyEnabled ? \"1\" : \"0\";\n",
  "      document.getElementById(\"cfg-agent-wake-names\").value = String(config.agentWakeNames || \"\");\n",
  "      document.getElementById(\"cfg-llm-enabled\").value = config.llmClassifyEnabled ? \"1\" : \"0\";\n",
  "      document.getElementById(\"cfg-llm-url\").value = config.llmApiUrl || \"\";\n",
  "      document.getElementById(\"cfg-llm-model\").value = config.llmModel || \"\";\n",
  "      document.getElementById(\"cfg-llm-timeout\").value = config.llmTimeoutMs || \"\";\n",
  "      document.getElementById(\"cfg-llm-repair\").value = config.llmMaxRepairAttempts || 0;\n",
  "      document.getElementById(\"cfg-image-summary-enabled\").value = config.imageSummaryEnabled ? \"1\" : \"0\";\n",
  "      document.getElementById(\"cfg-image-summary-model\").value = config.imageSummaryModel || \"\";\n",
  "      document.getElementById(\"cfg-image-summary-timeout\").value = config.imageSummaryTimeoutMs || \"\";\n",
  "      document.getElementById(\"cfg-transcribe-enabled\").value = config.transcribeEnabled ? \"1\" : \"0\";\n",
  "      document.getElementById(\"cfg-transcribe-timeout\").value = config.transcribeTimeoutMs || \"\";\n",
  "      document.getElementById(\"cfg-data-dir\").value = config.dataDir || \"\";\n",
  "      document.getElementById(\"cfg-mysql-url\").value = buildMysqlUrl(config);\n",
  "      const mysqlPasswordInput = document.getElementById(\"cfg-mysql-password\");\n",
  "      mysqlPasswordInput.value = \"\";\n",
  "      mysqlPasswordInput.placeholder = config.mysqlPasswordConfigured\n",
  "        ? (\"已配置：\" + (config.mysqlPasswordMasked || \"******\") + \"，留空则保持不变\")\n",
  "        : \"未配置；如 MySQL 不需要密码可留空\";\n",
  "      document.getElementById(\"cfg-knowledge-harvest-enabled\").value = config.knowledgeHarvestEnabled ? \"1\" : \"0\";\n",
  "      document.getElementById(\"cfg-knowledge-harvest-ready-age\").value = config.knowledgeHarvestReadyAgeMs || \"\";\n",
  "      document.getElementById(\"cfg-knowledge-harvest-interval\").value = config.knowledgeHarvestScanIntervalMs || \"\";\n",
  "      document.getElementById(\"cfg-knowledge-harvest-max\").value = config.knowledgeHarvestMaxPerScan || \"\";\n",
  "      loadRagflowChats(config.ragflowChatId || \"\").catch((error) => {\n",
  "        if (configRagflowStatus) configRagflowStatus.textContent = \"机器人列表加载失败：\" + String(error?.message || error);\n",
  "      });\n",
  "      const keyInput = document.getElementById(\"cfg-llm-key\");\n",
  "      keyInput.value = \"\";\n",
  "      keyInput.placeholder = config.llmApiKeyConfigured\n",
  "        ? (\"已配置：\" + (config.llmApiKeyMasked || \"******\") + \"，留空则保持不变\")\n",
  "        : \"未配置，保存时请填入新的 API Key\";\n",
  "    }\n",
  "\n",
  "    async function loadConfig() {\n",
  "      const response = await fetch(\"/flowbot/config\", { cache: \"no-store\" });\n",
  "      const data = await response.json();\n",
  "      if (!data.ok) {\n",
  "        throw new Error(data.error || \"config_load_failed\");\n",
  "      }\n",
  "      applyConfigToForm(data);\n",
  "      setConfigFlash(\"配置已载入\");\n",
  "      return data;\n",
  "    }\n",
  "\n",
  "    async function submitConfigTest() {\n",
  "      if (configBusy) {\n",
  "        return;\n",
  "      }\n",
  "      configBusy = true;\n",
  "      setConfigFlash(\"正在测试模型连接...\");\n",
  "      try {\n",
  "        const response = await fetch(\"/flowbot/config/test\", {\n",
  "          method: \"POST\",\n",
  "          headers: {\n",
  "            \"Content-Type\": \"application/json\",\n",
  "          },\n",
  "          body: JSON.stringify(getConfigPayload()),\n",
  "        });\n",
  "        const data = await response.json();\n",
  "        if (!data.ok) {\n",
  "          throw new Error(data.error || \"config_test_failed\");\n",
  "        }\n",
  "        const statusText = data?.testResult?.overall?.llmStatus || \"测试完成\";\n",
  "        setConfigFlash(\"连通性测试完成：\" + statusText, data?.testResult?.overall?.llmConnected ? \"ok\" : \"normal\");\n",
  "      } catch (error) {\n",
  "        setConfigFlash(\"测试失败：\" + String(error?.message || error), \"error\");\n",
  "      } finally {\n",
  "        configBusy = false;\n",
  "      }\n",
  "    }\n",
  "\n",
  "    async function submitConfigSave(event) {\n",
  "      event.preventDefault();\n",
  "      if (configBusy) {\n",
  "        return;\n",
  "      }\n",
  "      configBusy = true;\n",
  "      setConfigFlash(\"正在保存配置并应用...\");\n",
  "      try {\n",
  "        const response = await fetch(\"/flowbot/config\", {\n",
  "          method: \"POST\",\n",
  "          headers: {\n",
  "            \"Content-Type\": \"application/json\",\n",
  "          },\n",
  "          body: JSON.stringify(getConfigPayload()),\n",
  "        });\n",
  "        const data = await response.json();\n",
  "        if (!data.ok) {\n",
  "          throw new Error(data.error || \"config_save_failed\");\n",
  "        }\n",
  "        setConfigFlash(\"配置已写入，服务正在重启，大约几秒后刷新\", \"ok\");\n",
  "        setTimeout(() => {\n",
  "          loadConfig().catch((error) => setConfigFlash(\"重载配置失败：\" + String(error?.message || error), \"error\"));\n",
  "          load(true).catch(() => {});\n",
  "        }, 5000);\n",
  "      } catch (error) {\n",
  "        setConfigFlash(\"保存失败：\" + String(error?.message || error), \"error\");\n",
  "      } finally {\n",
  "        configBusy = false;\n",
  "      }\n",
  "    }\n",
  "\n",
  "    function escapeHtml(value) {\n",
  "      return String(value ?? \"\")\n",
  "        .replaceAll(\"&\", \"&amp;\")\n",
  "        .replaceAll(\"<\", \"&lt;\")\n",
  "        .replaceAll(\">\", \"&gt;\")\n",
  "        .replaceAll('\"', \"&quot;\")\n",
];
